### ISSUE TITLE
Mobile: Edit mode false positive after archive

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1005]
## Steps to Reproduce

- a
- b
- c

1. Set the cursor on `c`
1. Tap `c` to activate edit mode. 
1. Activate the archive shortcut
1. Tap `a`

## Current Behavior

The cursor moves to `a` and edit mode is activated. 

## Expected Behavior

The cursor should move to `a` but not activate edit mode. Edit mode should be disabled when the keyboard is closed.

**Comment by shresthabijay** [comment]
@raineorshine After tapping `c`, activating edit mode and then activating archive, the cursor moves to `b` and is in edit mode. Since cursor is in edit mode, tapping on `a` will still be edit mode. Is not this the desired behavior ?

**Comment by raineorshine** [comment]
Yes, the current behavior is correct now! I was losing the keyboard on archive before, so I guess the root of the problem has been fixed.
