### ISSUE TITLE
iOS: Edit mode false positive on move

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1006]
Related: #1005

## Steps to Reproduce

- a
- b

1. Set the cursor on `b`
1. Tap `b` to activate edit mode. 
1. Drag `b` into `a`
1. Tap `a`

## Current Behavior

The cursor moves to `a` and edit mode is activated. 

## Expected Behavior

The cursor should move to `a` but not activate edit mode. Edit mode should be disabled when the keyboard is closed.

**Comment by shresthabijay** [comment]
@raineorshine  The first one is the correct behavior and the second one is not expected right ?

![Screen Capture_select-area_20210121202248](https://user-images.githubusercontent.com/25879100/105365780-bd566300-5c26-11eb-960a-b1ea018bf369.gif)

![Screen Capture_select-area_20210121202421](https://user-images.githubusercontent.com/25879100/105365792-c1828080-5c26-11eb-99ec-f3810a15534f.gif)

**Comment by raineorshine** [comment]
Sorry for the confusion! The step "Drag `b` into `a`" means a drag-and-drop action that results in the following structure:

- a
  - b

I was getting inconsistent results with dragging, so try the indent command instead. Then it happens every time.

**Comment by shresthabijay** [comment]
> so try the indent command instead. Then it happens every time

How can we indent in mobile. I couldn't find the gesture in the help modal ?

**Comment by shresthabijay** [comment]
@raineorshine Here the cursor is set on a thought but editing mode is not enabled. So when I am tap another thought it shouldn't enter editing mode as well right ? 

https://user-images.githubusercontent.com/25879100/105380054-96535d80-5c35-11eb-811a-d8ccefca976e.mp4

**Comment by raineorshine** [comment]
> > so try the indent command instead. Then it happens every time
> 
> How can we indent in mobile. I couldn't find the gesture in the help modal ?

It's toolbar only:

![image](https://user-images.githubusercontent.com/750276/105382565-6f614100-5bcd-11eb-844b-6ec86f368e65.png)

> @raineorshine Here the cursor is set on a thought but editing mode is not enabled. So when I am tap another thought it shouldn't enter editing mode as well right ?

Correct, it should only enter editing mode when the cursor is already on the tapped though. Edit mode is also activated automatically with some commands, such as New Thought.

Could you make a separate issue for this? I haven't experienced it on iOS so it's probably Android only.

**Comment by shresthabijay** [comment]
@raineorshine I took following steps:
- I tapped `b` to activate edit mode.
- Activate indent.

However for me the keyboard is still open and thought `b` is in editing mode. The expected behavior you defined makes me understand that keyboard gets closed after indent.

**Comment by raineorshine** [comment]
> However for me the keyboard is still open and thought `b` is in editing mode. The expected behavior you defined makes me understand that keyboard gets closed after indent.

Okay, that confirms that it's iOS only.

**Comment by shresthabijay** [comment]
@raineorshine  Can you please check this PR https://github.com/cybersemics/em/pull/1011 and test if this issue persists ?

**Comment by raineorshine** [comment]
> @raineorshine Can you please check this PR #1011 and test if this issue persists ?

It's still a problem unfortunately.

Do you have access to an iPhone? There are lots of bugs that occur on mobile Safari, so it would be helpful.

**Comment by shresthabijay** [comment]
> Do you have access to an iPhone? There are lots of bugs that occur on mobile Safari, so it would be helpful.

I am planning to get one soon. Maybe in few weeks and I will start working ios specific bugs.

**Comment by raineorshine** [comment]
The behavior has changed enough that I'm going to open a new issue for it.
