### ISSUE TITLE
Hidden thoughts should always be shown under meta attributes

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1015]
## Steps to Reproduce

1. Create thought `=a`
2. Create subthought `=b` within `=a`
3. Move cursor to `=a`

i.e.

- `=a` [cursor]
  - `=b`

## Current Behavior

`=b` is hidden and `=a` appears to be a leaf.

## Expected Behavior

Do not hide metaprogramming descendants when the cursor is on a metaprogramming attribute:

- `=a` [cursor]
  - `=b` [shown]
  
The current behavior should still be used if the cursor is not on a metaprogramming attribute:

- `a` [cursor]
  - `=b` [hidden]

**Comment by shresthabijay** [comment]
@raineorshine Let's say we have following structure.

- `=a` [cursor]
  - `c`
    - `= b`
    
Should `=b` be visible ? The cursor on a meta attribute but `=b`.

**Comment by raineorshine** [comment]
Honestly I'm not sure. It's an odd case, although I suppose it could happen. We may need more real-world use before we know the best design for that, so let's leave it as-is for now.
