### ISSUE TITLE
Nested duplicate thoughts on exisitingThoughtMove doesn't work

### ISSUE THREAD

**Issue by shresthabijay** [cybersemics/em#1017]
# Steps to Reproduce

-  Paste the following:
  ```
  - a
    - b
     - c
       - q
     - y
  - b
    - c
      - w
    - x
  ```
- Drag `b` inside `a.b`.

# Current Behavior
   
Throws error

# Expected Behavior
  ```
  - a
    - b
     - c
       - q
       - w
     - y
     - x
  ```

**Comment by raineorshine** [comment]
Thanks for reporting!

> * Drag `b` inside `a.b`.

I think you mean drag `b` inside `a` (or drag `b` *to* `a.b`). Drag *inside* means to drag into the context of.
