### ISSUE TITLE
importText: Missing context on root child lexeme

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1018]
## Steps to Reproduce

Paste the following:

```
- a
  - b
- b
```

## Current Behavior

`b` has no superscript. `getContext('b')` is missing context `a`.

## Expected Behavior

`b` should have superscript "2". `getContexts('b')` should return two contexts: `ROOT` and `a`.

**Comment by anmolarora1** [comment]
@raineorshine, I was not able to replicate this one. Can you please confirm if the issue persists?

**Comment by raineorshine** [comment]
It's working! Look at that
