### ISSUE TITLE
Cursor moves to thought hidden by autofocus

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1029]
This is a regression. It would be helpful to identify the originating commit. 

## Steps to Reproduce

```
- a
  - b
    - c
- d
``` 

1. Set the cursor on `c` so `d` disappears
2. Tap 1 line height below `c`, to the right of where `d` would be. 

## Current Behavior

Cursor moves to `d`. 

## Expected Behavior

Cursor should move to `b`. 

Tapping on empty space with no visible thoughts to the left or right should always activate `cursorUp`.

**Comment by raineorshine** [comment]
Only occurs on mobile, but you can reproduce it on desktop by forcing `isTouch = true`.

**Comment by raineorshine** [comment]
@shresthabijay Thank you for the solution! We should still do some forensic work to understand the bigger picture of this. When there is a discrete regression, it's important to identify the commit that broken to inform our fix. I have often fixed a regression only to realize I compromised the original behavior in some way. Usually it's better to identify why something stopped working rather than adding additional code to make it work again.

I put it softly in the description, but I probably should have made it clear that it was a requirement :). Could you find out which commit broke this and why? Thanks!

**Comment by shresthabijay** [comment]
@raineorshine Understood. I opted to go with the fix as it was fairly easy. I will get back to you after I identify the commit that created the regression.

**Comment by shresthabijay** [comment]
@raineorshine The regression seems to have been introduced from this commit 
https://github.com/cybersemics/em/commit/e12699e3524da5ee9bdcd9714e3429a59683fba7. 

`onTap` replaced `onMouseDown` for device with touch screens. Previously `cursorBack` was being called even on touch screen devices because `onMouseDown` was being called after `onTapEnd`. This is because touch events also emit artificial mouse events on succession unless touch events are prevented.

`onTap` doesn't have `cursorBack` logic. With this commit `onTap` is being called on `onmousedown` event for touch screens, thus this regression was introduced.

**Comment by raineorshine** [comment]
> @raineorshine The regression was introduced from this commit [e12699e](https://github.com/cybersemics/em/commit/e12699e3524da5ee9bdcd9714e3429a59683fba7).

Great, thanks! 

Reference: #946

> `onTap` replaced `onMouseDown` for device with touch screens. Previously both `onTapEnd` and `onMouseDown` was being called on touch screen devices. This is because touch events emit artificial mouse events on succession unless touch events are prevented. Since `onMouseDown` had `cursorBack` logic, it was working for mobile devices prior to this commit.

Makes sense

> Instead we need to add `cursorBack` logic to `onTap` and pass noop to `onMouseDown` for touch screen devices.

That sounds reasonable. I see you added the `cursorBack` logic to `onTap`. Do you want to add the noop in the PR as well?

**Comment by raineorshine** [comment]
Regression prevention checklist: https://github.com/cybersemics/em/issues/946#issuecomment-801331251

**Comment by raineorshine** [comment]
Issue still occurs when in edit mode :(

**Comment by onurpolattimur** [comment]
Hi! Is there any specific reason for not hiding the editable element for hidden thoughts?

**Comment by raineorshine** [comment]
Maybe setting ‘visibility: hidden` would work. I hadn't tried that. That would be less logic.

**Comment by raineorshine** [comment]
Here are steps to reproduce the regression from #1128. Tested on iOS. 

I’m concerned about trying to continue to add fixes for regressions. I would start over with what we know now and see if we can solve this issue by creating a precise fix. 

## Steps to Reproduce

1. Create a thought. 
2. Close the keyboard 
2. Activate `cursorUp` (`cursor` becomes null)
3. Tap on the thought

## Current Behavior

The cursor moves to the thought and enters edit mode. 

## Expected Behavior

Should not enter edit mode when the cursor changes.

**Comment by onurpolattimur** [comment]
Fixed and explained in #1135
