### ISSUE TITLE
Pull: Context View 

### ISSUE THREAD

**Issue by shresthabijay** [cybersemics/em#1032]
There is a problem with `pullQueue` not being able to correctly pull for thoughts inside context view. The reason for the issue is that we are using context that includes context view. Instead we need to use simple context that doesn't include context view.

For example:
- a
  - b 
   - c  ~ (cursor)
      - a.k
        - i 
Here a.b.c.k is the context of the cursor. Since this context includes context view, we cannot use it to pull from the sever or indexed db. We need to convert this context to context chain and use last simple context to pull the data.

One possible solution would be to use `splitChain`  for each context in `pullQueue` index. But `splitChain` uses `Path` instead of `Context`. It also use `rankThoughtsFirstMatch` which may not work properly because all the required thoughts may not have loaded yet.

**Comment by shresthabijay** [comment]
@raineorshine I think we can extend `expandThoughts` to return both indexes of `Path` and `SimplePath`. `Index<Path>` can be used for rendering and `Index<SimplePath>` for `pullQueue`. Since `expandThoughts` already has most of the logic, so it may be easier and faster way to solve this. I am pretty sure we can get `SimplePath` from the current logic of `expandThoughts`. What do you think ?

**Comment by raineorshine** [comment]
Including both `Path` and `SimplePath` in the index is pretty ugly. `SimplePath` is derivable from `Path` so the redundancy is only for performance. Changing an interface for performance is usually a bad idea. That said, I can’t think of a cleaner approach off the top of my head. I will need to take a closer look once I have my computer back and can move around the source code better. Are there any other options?

**Comment by shresthabijay** [comment]
> Including both `Path` and `SimplePath` in the index is pretty ugly. `SimplePath` is derivable from `Path` so the redundancy is only for performance. Changing an interface for performance is usually a bad idea. That said, I can’t think of a cleaner approach off the top of my head. I will need to take a closer look once I have my computer back and can move around the source code better. Are there any other options?

I meant `expandThoughts` could return something like this 
```
  {
   expanded: {}
   expandedSimple: {}
  }
```.

I cannot think of any other solution right now.

**Comment by raineorshine** [comment]
Yes, I understood.

Okay, I’ll take a deeper look!

**Comment by shresthabijay** [comment]
> Yes, I understood.
> 
> Okay, I’ll take a deeper look!

Sure. I will try to come up with cleaner solution. I will let you know.

**Comment by shresthabijay** [comment]
@raineorshine Did you take a look into this ?

**Comment by raineorshine** [comment]
Yes! `pullQueue` only needs expanded `Contexts`, not `Paths` at all. How about adding a `returnContexts: Boolean` optional parameter? Then we don't have to change the default signature.

https://github.com/cybersemics/em/blob/dev/src/redux-middleware/pullQueue.ts#L33
