### ISSUE TITLE
Use of setTimeout outside a function

### ISSUE THREAD

**Issue by anmolarora1** [cybersemics/em#1035]
In our current code, we're using a hack to load whitelisted thoughts on the app startup - using [setTimeout](https://github.com/cybersemics/em/blob/b2bfc9e110185c4a823ff81e716a64cf25b19169/src/reducers/updateThoughts.ts#L31) outside a function

The main issue is that the util imports are undefined at load time for some reason. However, the whitelisted thoughts need to be loaded on app startup. The setTimeout ensures that the util functions are imported before importHTML is called.

**Comment by raineorshine** [comment]
Suspect `raw.macro`
