### ISSUE TITLE
collapseContext creates invalid rank

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1057]
## Steps to Reproduce

- a
  - =x
  - b
    - c

1. Set the cursor on `a/b`
2. Activate `collapseContext`
3. (With the cursor now in `a/c`) Activate `newThoughtAbove`

## Current Behavior

A new thought is added below `c`. 

## Expected Behavior

A new thought should be added above `c`. 

## Note

If instead of using `collapseContext` we manually move `a/b/c` to `a/c` and then archive `a/b`, the issues does not occur. This suggests that the bug is in `collapseContext`.

**Comment by shresthabijay** [comment]
@raineorshine I couldn't reproduce the issue. I tested it in Chrome, Safari Desktop, and IOS Safari(Simulator). New empty thought is added above `C`. Which device are you testing this?

**Comment by raineorshine** [comment]
Can't reproduce now! Maybe it got fixed :).
