### ISSUE TITLE
Fix bullet positioning

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#106]
The bullet positioning looks good, but the text should be in the same place regardless of the three bullet types:

- open
- closed
- leaf

Adjust the bullet margin to fix the text. 

Apples to both desktop and mobile.

**Comment by KarlaChen** [comment]
Hi, @raineorshine Can I try it?

**Comment by raineorshine** [comment]
Sure! Kindly open a new Pull Request rather than reusing an existing one. The title of the PR should be "Fix bullet positioning" and the description/comment should reference "#106". Thanks!
