### ISSUE TITLE
Sort descending

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1078]
## Steps to Reproduce

Toggle `sortContext`

## Current Behavior

Toggles between `Alphabetical` and none. 

## New Behavior

3-way toggle between `Alphabetical`, `Alphabetical/desc`, and none. 

Add the appropriate logic for sorting in descending order with `Alphabetical/desc`.

Duplicate the sort icon and reverse the direction of the arrow. Or parameterize the current component. 

## Tests

- [ ] [None] → Alphabetical
- [ ] Alphabetical → Alphabetical/desc
- [ ] Alphabetical/desc → [None]
- [ ] Alphabetical/asc (should work the same as Alphabetical)

**Comment by onurpolattimur** [comment]
Should we reverse the direction of the arrow or bars? I think it seems better when we change the order of bars. 

For ascending order:
![image](https://user-images.githubusercontent.com/23136437/115916858-0e703000-a47e-11eb-869e-14a1633fcc32.png)

For descending order:
![image](https://user-images.githubusercontent.com/23136437/115916754-e4b70900-a47d-11eb-84dd-bef8191ac287.png)

**Comment by raineorshine** [comment]
Sure, I’d be happy either way!
