### ISSUE TITLE
importText: does not import nested html tags properly

### ISSUE THREAD

**Issue by onurpolattimur** [cybersemics/em#1091]
## Steps to Reproduce

- Copy `<b><i>Hi</i></b>` 
- Paste copied item.

## Current Behavior

 <b>undefined<b> 
 (`<b>undefined<b> ` )

## Expected Behavior

<b><i>Hi</i></b> 
(`<b><i>Hi</i></b>` )

**Comment by onurpolattimur** [comment]
Actually, there are two problems.

- The first problem is in `importText.ts`
When we import `<b><i>Hi</i></b>` , we are getting number of line using `regexpListItem`
So there is no matching item with this regex, we set lineNumbers to 0 but it should be 1. Because lineNumbers is 0, it goes into else block whose purpose is to handle multi-line inputs. If we change the condition of the if, it will solve the problem for single-line inputs.
- The second problem is in `convertHTMLtoJSON.ts`
When we import the text below, it goes into else block mentioned above because lineNumbers is 2.

    ```
    <li><i><b>A</b></i></li>
    <li><i><b>B</b></i></li>
    ```

    In `formattingNodeToHtml` function, we are keeping only the root tag and trying to get children of this root tag as a text for each content of `<li>. ` 
    To make it clear here is an example;
    For `<i><b>B</b></i>` element; keep `<i>` tag and get children of `<i>` element as Text that is undefined. So the result will be <i>undefined</i>. We need to call `formattingNodeToHtml` recursively for its children.

**Comment by raineorshine** [comment]
Thanks for the explanation! That's very helpful.

> * When we import `<b><i>Hi</i></b>` , we are getting number of line using `regexpListItem`
>   So there is no matching item with this regex, we set lineNumbers to 0 but it should be 1. Because lineNumbers is 0, it goes into else block whose purpose is to handle multi-line inputs. If we change the condition of the if, it will solve the problem for single-line inputs.

I don't think there's ever a reason to set `numLines` to `0`, so yes let's change the conditional to `<= 1` or add `|| 1` as a default.

> * For `<i><b>B</b></i>` element; keep `<i>` tag and get children of `<i>` element as Text that is undefined. So the result will be `<i>undefined</i>`. We need to call `formattingNodeToHtml` recursively for its children.

Yes, I agree!
