### ISSUE TITLE
Allow empty Algolia config

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1092]
Currently the app cannot load any thoughts from the remote when the Algolia config is left empty. This makes it harder for new developers to get started on the project or to stand up staging sites.

Instead, if the Algolia config is missing, everything should still work except the search. If the user attempts to search, an alert should be shown that says that search functionality is not enabled.

**Comment by shresthabijay** [comment]
> Instead, if the Algolia config is missing, everything should still work except the search. If the user attempts to search, an alert should be shown that says that search functionality is not enabled.

I think we could allow local search instead of disabling search altogether. What do you think?

**Comment by raineorshine** [comment]
Yes, absolutely!
