### ISSUE TITLE
Caret not set after subcategorizeOne

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1103]
Tested on iOS. 

Note that it is only an issue with `subcategorizeOne`, not `subcategorizeAll` for some reason. 

This regression has occurred a couple times, so it’ll be good to get test coverage now that we have caret testing with Puppeteer. 

## Steps to Reproduce

- a
  - b

1. Set the cursor on `b`
2. Close the keyboard to disable edit mode
3. Activate `subcategorizeOne` via the toolbar or gesture

## Current Behavior

New parent thought is created and caret is not set. 

## Expected Behavior

Caret should be set and edit mode enabled on the new thought.

**Comment by onurpolattimur** [comment]
I think the problem is that we don't set editing true in subCategorizeOne.ts. When I add `editing: true`, the keyboard is opened. I tested on iOS/Safari.

https://github.com/cybersemics/em/blob/9768232839b32511828bc22a2fab8ed1f29d5bcf/src/reducers/subCategorizeOne.ts#L61-L64

**Comment by onurpolattimur** [comment]
Also, this problem occurs only on touchable platforms because we set editing to `false` only for the touchable platforms.

https://github.com/cybersemics/em/blob/9768232839b32511828bc22a2fab8ed1f29d5bcf/src/components/Editable.tsx#L574-L579

**Comment by raineorshine** [comment]
> I think the problem is that we don't set editing true in subCategorizeOne.ts. When I add `editing: true`, the keyboard is opened. I tested on iOS/Safari.

Yup, that should work. `subCategorizeOne` should always enter edit mode. I guess `subCategorizeAll` doesn't suffer from the same problem because `newThought` handles the caret.
