### ISSUE TITLE
Missing oldThoughtRanked in Settings update: Tutorial Off

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1113]
> > Does the error occur when clicking on the skip tutorial link, or after clicking?
> 
> It occurs after clicking on the skip tutorial link.
> 
> > Does this happen consistently or intermittently?
> 
> As I see, this happen consistently.
> 
> > What do you mean by "related states"?
> 
> When we click the link, `[EM_TOKEN, 'Settings', 'Tutorial]` context and its children are not loaded at this time properly. So it can not get old value in `settings.ts `
> 
> https://github.com/cybersemics/em/blob/f55a4b2d9f011b3a98a6446b12a41a31238f8b3b/src/reducers/settings.ts#L15
> 
> And UI becomes this:
> 
> ![image](https://user-images.githubusercontent.com/23136437/116285007-623c8b00-a796-11eb-9822-3a6c41fd9cb9.png)
> 
> Maybe you cannot reproduce this issue in your local environment, to reproduce this issue you need to change
> await `page.click('#skip-tutorial') ` line to
> `await page.evaluate(() => document.getElementById('skip-tutorial')?.click())`
> 
> Because, page.click() is slightly different from document.getElementById(..).click(). You can see details at [here](https://stackoverflow.com/questions/49979069/puppeteer-element-click-not-working-and-not-throwing-an-error). But, if you don't change this line, it will be stuck on Welcome Modal, not the screen I added above.

**Comment by onurpolattimur** [comment]
I think it is related to timing issues. This is really an edge case and I don't think that users can be fast as much as e2e test. But of course, we need to solve this and I will give some details below.

This issue occurs when the user clicked the skip tutorial link before thoughts related to settings are loaded into the state. I think we can not simulate this problem without any change and here are the steps to reproduce this issue. 

### How to re-produce?

1- Add the below code to AppCompenent.tsx to simulate clicking the skip-tutorial link when it is visible.

```jsx
  useEffect(() => {
    document.getElementById('skip-tutorial')?.click()
  }, [isLoading])
```

2- Open your em on browser and open devtools console. In the console, paste the code below and run.

```jsx
 await window.em.testHelpers.clearAll()
 localStorage.clear()
 location.reload()
```

You should be able to see the warning in the console.
![image](https://user-images.githubusercontent.com/23136437/116742005-7505c880-a9ff-11eb-977b-1d23f8784063.png)

### Solution idea

We should not render the Modal until the isLoading state becomes true. We can add isLoading as a condition to the place shown below.

[cybersemics/em](https://github.com/cybersemics/em/blob/5dd662f05eb454bb1d7da91d97f45896a3e40ab9/src/components/AppComponent.tsx#L130)

**Comment by raineorshine** [comment]
I like your overall analysis and points about this not being realistically reproducible by the end user.

I don't think we want to delay rendering the modal itself. That's not quite the right semantics; a modal should display instantly when `showModal` is set.

What about disabling or hiding the skip link until the `[EM_TOKEN, 'Settings', 'Tutorial]` context itself is loaded?

```js
const isTutorialSettingsLoaded = useSelector(
  state => getAllChildren(state, [EM_TOKEN, 'Settings', 'Tutorial]).length > 0
)
```

**Comment by onurpolattimur** [comment]
Hi @raineorshine, I have made the changes in #1117. Can you review it, please?
