### ISSUE TITLE
Import Error: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1131]
## Steps to Reproduce

Paste the following:

```
- a
- b
- <span>c
- d
```
or:

```
- a
 - b
 - b
 - <em>c</em>
```

or:

```
- a
- b
- c<br>
```

## Current Behavior

![image](https://user-images.githubusercontent.com/750276/117586059-0e556e80-b0d3-11eb-9f57-35ccafaa837c.png)

## Expected Behavior

- a
- b
- c
- d

**Comment by shresthabijay** [comment]
@raineorshine Is this issue fixed ?

**Comment by raineorshine** [comment]
No, the referenced commits are workarounds for a script that diffs database snapshots.
