### ISSUE TITLE
Export: Advanced options

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1140]
Add an "Advanced" toggle to the Export screen that displays more advanced export options. The Export screen can be activated with the last icon on the right of the toolbar.

- Move "Copy to clipboard" above the download message.
- Add an "Advanced" link below the download message.
- Clicking the Advanced link should open up a div below it where advanced options can go.

![image](https://user-images.githubusercontent.com/750276/118134002-b1053a00-b3be-11eb-9416-3344114c376f.png)

**Comment by raineorshine** [comment]
## Part II

- Add `ArrowDownWhite` (or `ArrowDownWhite` if `dark` is true) to the right of the "Advanced" link to show the user that it expands content.
- When expanded, the arrow should point up.
- Currently there are two plaintext options in the dropdown menu: "Plain Text (lossless)" and "Plain Text". Actually, lossless should be an advanced option that applies to any content type.
  - Remove "Plain Text (lossless)" from the dropdown menu
  - Add a "Lossless" checkbox to the Advanced section as shown below. Default to checked.
  - Rewire the "Plain Text (lossless)" functionality to use the "Lossless" checkbox.

<img width="1068" alt="Screen Shot 2021-05-14 at 3 12 51 PM" src="https://user-images.githubusercontent.com/750276/118319441-03765180-b4b8-11eb-8e92-b4d1c4b3f48e.png">

**Comment by ruchijn** [comment]
Based on current functionality, user can either select `Plain Text(Lossless)`or `Plain Text`. Moving forward when `Plain Text (Lossless)` is moved to advanced with auto-selected, should I go ahead and make sure nothing is auto-checked in the existing dropdown?

**Comment by raineorshine** [comment]
The new options in the dropdown menu will be `Plain Text` and `HTML`, with `Plain Text` selected by default.

**Comment by ruchijn** [comment]
My main question is, can we have user download as `Plain Text` and `Lossless` both selected at same time? If so, then will they download 2 files?

**Comment by raineorshine** [comment]
`Plain Text` is the file format and `Lossless` corresponds to the `excludeMeta` option that is passed to `getDescendants` and `exportContext`, e.g.:

https://github.com/cybersemics/em/blob/7ff12d46358d2942fafb8a5604d06994aaa5a8b0/src/components/ModalExport.tsx#L53-L55

If the user has `Plain Text` selected from the dropdown and `Lossless` checked (which is the default situation) then `exportContext` will be called with `text/plain` and `excludeMeta: false`. It will still download one file.

Does that make sense?

**Comment by ruchijn** [comment]
Yeah. Thats what I was asking. So `Lossless` takes precedence over `Plain Text`. Thanks for clarifying.

**Comment by raineorshine** [comment]
> So `Lossless` takes precedence over `Plain Text`.

No, I wouldn't say that. They are independent variables. These are all valid:

- Plain Text x Lossless (default)
- Plain Text x Lossy
- HTML x Lossless
- HTML x Lossy

**Comment by ruchijn** [comment]
So if they have `HTML` in dropdown and `Lossless` in advanced setting, then the download will be `HTML Lossless`. Got it.

**Comment by ruchijn** [comment]
I can see the difference when I do it on chrome. But on FF, I don't see any difference. Is it supposed to work on FF?

**Comment by raineorshine** [comment]
Personally I haven't tested on Firefox, just Chrome and Safari. I imagine there are some Firefox specific bugs across the app.

**Comment by raineorshine** [comment]
Done in #1142
