### ISSUE TITLE
Context View: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by onurpolattimur** [cybersemics/em#1149]
I encountered this issue while working on #1141 

## Steps to Reproduce

- Paste the following:

```
- a
  - b
    - c
      - x
    - d
      - x
```

- Set the cursor on a/b/c/x
- Toggle context view
- Set cursor on c in context view

## Current Behavior

![image](https://user-images.githubusercontent.com/23136437/118377710-94901a00-b5d7-11eb-99d0-b2109114d8d2.png)

## Expected Behavior

The cursor should be on c in context view.

**Comment by raineorshine** [comment]
Confirmed resolved.
