### ISSUE TITLE
Mobile: Do not outdent during clearThought

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1150]
Mobile only

https://user-images.githubusercontent.com/750276/118383704-60fcc200-b5ce-11eb-8ec0-c380f2661b35.mov

## Steps to Reproduce

1. Create thought `A`
2. Create subthought `B`
2. Activate `clearThought` by swiping right-left. 
3. Hit Backspace

## Current Behavior

`B` is outdented

## Expected Behavior

`B` should be deleted. 

## Notes

In `newThoughtOrOutdent`, activate `outdent` only if the placeholder attribute of the Editable does not equal the innerHTML stripped of tags. 

https://github.com/cybersemics/em/blob/cdeabad628dda0219ff34a751d5c0735cf55a1c7/src/shortcuts/newThoughtOrOutdent.tsx#L27-L30

Factor out the code that strips the innerHTML of tags into a helper function `toPlaceholder: string → string` since `newThoughtOrOutdent` must check for the exact value set at the placeholder in `clearThought`:

https://github.com/cybersemics/em/blob/cdeabad628dda0219ff34a751d5c0735cf55a1c7/src/shortcuts/clearThought.ts#L15

**Comment by ruchijn** [comment]
I was looking into this. I am not sure if I am doing it wrong, but it doesn't seem to be going to https://github.com/cybersemics/em/blob/cdeabad628dda0219ff34a751d5c0735cf55a1c7/src/shortcuts/newThoughtOrOutdent.tsx#L27-L30. It seems to be dispatching `outdent` from https://github.com/cybersemics/em/blob/cdeabad628dda0219ff34a751d5c0735cf55a1c7/src/shortcuts/deleteEmptyThoughtOrOutdent.tsx#L111. 

Just wanted to confirm if I am right track before I go in deeper.

**Comment by raineorshine** [comment]
Good catch! You're right, it's in `deleteEmptyThoughtOrOutdent`, not `newThoughtOrOutdent`.
