### ISSUE TITLE
Toolbar: Do not select text on toolbar tooltip

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1153]
- When pressing and holding a toolbar icon to show the tip, do not select any text. 
- Preserve the haptic feedback on tap and hold 
- Do not activate command on release after a toolbar tip is shown 

https://user-images.githubusercontent.com/750276/118384370-9526b180-b5d3-11eb-884a-49dcccb9b7a9.mov

**Comment by shresthabijay** [comment]
@onurpolattimur Can you look at this issue ?

**Comment by shresthabijay** [comment]
@onurpolattimur Any updates ?

**Comment by raineorshine** [comment]
Toolbar tip has been removed, and behavior is no longer reproducible.
