### ISSUE TITLE
Scrollable Content and properly fixed toolbar/navigation components

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1156]
`position: fixed/sticky` is choppy when the keyboard is up on mobile Safari. The current solution for the `Toolbar` is choppy, and the same problem would exist for the `NavBar` and `LatestShortcutsDiagram`.

- Refactor the layout so that `<Content>` scrolls instead of the `<body>`
- Preserve scroll bounce at top and bottom (default iOS behavior)
- `Toolbar` - `position: fixed` with gradient mask
- `NavBar` - `position: sticky` above `Footer`. We may still want to hide this during editing so the user can be more focused.
- `LatestShortcutsDiagram` - `position: sticky` above `NavBar`

**Comment by raineorshine** [comment]
I realized today that we probably want to move the toolbar to the bottom of the screen instead of the top of the screen (closer to fingers, avoids fingers getting in the way of tooltips). We're going to need to figure out how to position it correctly with the on-screen keyboard to make that happen. Feel free to spend some more time on this.

**Comment by raineorshine** [comment]
On second thought… the React Native app will likely use a native control that won’t suffer any of these problems. It may not be worth putting time into this if we think the mobile app will have that part of the UI covered.

**Comment by shresthabijay** [comment]
> On second thought… the React Native app will likely use a native control that won’t suffer any of these problems. It may not be worth putting time into this if we think the mobile app will have that part of the UI covered.

I agree with this.

> I realized today that we probably want to move the toolbar to the bottom of the screen instead of the top of the screen (closer to fingers, avoids fingers getting in the way of tooltips). We're going to need to figure out how to position it correctly with the on-screen keyboard to make that happen. Feel free to spend some more time on this.

In IOS safari keeping the component fixed at the bottom on the keyboard up is the same problem as keeping it fixed at the top as we discussed earlier. However, we can use some other tricks to make it less choppy to the user. On IOS safari when keyboard is up we can hide the toolbar when screen is scrolled and show it again as soon as the scroll is stopped. If done properly with good transition we maye be able make it less choppy experience for the IOS safari user.

**Comment by raineorshine** [comment]
Great. I'll close this, because I think the mobile app will cover it.
