### ISSUE TITLE
Preserve (limited) <style> attributes

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1158]
> we properly import text that is copied from the IOS notes app. But there is one issue about the text that contains formatting copied from IOS notes. IOS notes app doesn't add `<b>, <i>` tags for text formatting. IOS Notes app uses the style attribute to style texts. Here is an example that contains bold text that is copied from the app.
> 
> ```
> <meta charset="UTF-8"><p class="p1"
>                          style="margin: 0px; font-style: normal; font-variant-caps: normal; font-weight: normal; font-stretch: normal; font-size: 14px; line-height: normal; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">
>     <span class="s1" style="font-weight: bold; font-style: normal; font-size: 14px;">A</span></p><p class="p1"
>                                                                                                     style="margin: 0px; font-style: normal; font-variant-caps: normal; font-weight: normal; font-stretch: normal; font-size: 14px; line-height: normal; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">
>     <span class="s1" style="font-weight: bold; font-style: normal; font-size: 14px;"><span class="Apple-converted-space"> </span>B</span></p>
> ```
> 
> We import the text properly for the above input but we are losing formatting. I will look into this problem on another issue because before fixing this issue we need to discuss about this.

## Possible Solutions

1. Convert `<span>` style attributes to `<b>` and `<i>`
2. Render inline `<span>` in Editable

## Discussion

I prefer solution #<b></b>2 because a) it does not require any special conversions, just making the HTML stripping a bit smarter, and b) it allows any style to be applied inline not just `<b>` and `<i>`.

**Comment by onurpolattimur** [comment]
I prefer solution 2 too.

Do you think there are some points that we need to be careful about span tags?

**Comment by raineorshine** [comment]
What, you think this is excessive? 😂

```html
<span style="
  margin: 0px;
  font-style: normal;
  font-variant-caps: normal;
  font-weight: normal;
  font-stretch: normal;
  font-size: 14px;
  line-height: normal;
  caret-color: rgb(0, 0, 0);
  color: rgb(0, 0, 0);
  letter-spacing: normal;
  orphans: auto;
  text-align: start;
  text-indent: 0px;
  text-transform: none;
  white-space: normal;
  widows: auto;
  word-spacing: 0px;
  -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3);
  -webkit-text-size-adjust: auto;
  -webkit-text-stroke-width: 0px;
  text-decoration: none;
">
```

I suppose white-listing css properties is the safest bet. After going through *all* css properties, here's what I think should be allowed. "*" indicates any css property that starts with that string.

- background*
- border*
- box-shadow
- color
- font*
- opacity
- padding*
- text*
- white-space
- word*


> Do you think there are some points that we need to be careful about span tags?

Not exactly sure what you mean, can you clarify if this is a separate question or is referring to the question about which properties to include? We want to remove all non-style attributes.

**Comment by raineorshine** [comment]
I would take one extra step to make the user's life a little easier when pasting formatted text: If a span has `color` set to white or black (which is possible in a variety of ways: `#000`, `black`, `rgb(0, 0, 0)`, etc) and no `background`, then remove the `color` property. If they are copying from a white background we don't want to make the text invisible, and if they are copying from a black background we can omit the white color since that's the default. We can avoid in-between shades since they involve contrast calculations and it is ambiguous whether the user wanted to preserve them or not.

**Comment by raineorshine** [comment]
After some use, I'm sad to say that preserving style attributes is not as nice as I thought it would be! Most of the time it is unintentional, and the result is ugly at best and confusing at commonly worst. 

At the very least, it should be a special command and not the default. 

Let's disable this feature for now, only preserving bold, italic, and underline.

**Comment by raineorshine** [comment]
After some use, I'm sad to say that preserving style attributes is not as nice as I thought it would be 😅. Most of the time it is unintentional, and the result is ugly at best and confusing at commonly worst. 

At the very least, it should be a special command and not the default. 

Let's disable this feature for now, only preserving bold, italic, and underline.

**Comment by raineorshine** [comment]
The following case is still incorrectly preserving formatting:

## Steps to Reproduce

Paste the following:

`<span style="caret-color:rgb(255, 255, 255);color:rgb(255, 255, 255);font-family:Helvetica;font-size:13px;font-style:normal;font-variant-caps:normal;font-weight:300;letter-spacing:normal;orphans:auto;text-align:left;text-indent:0px;text-transform:none;white-space:pre-wrap;widows:auto;word-spacing:0px;-webkit-tap-highlight-color:rgba(0, 0, 0, 0);-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;background-color:rgb(0, 0, 0);text-decoration:none;display:inline;float:none">Atonement</span>`

## Current Behavior

All style rules are preserved.

## Expected Behavior

All style rules besides bold, italic, and underline should be removed.

**Comment by raineorshine** [comment]
The following case is still incorrectly preserving formatting:

## Steps to Reproduce

Paste the following:

`<span style="caret-color:rgb(255, 255, 255);color:rgb(255, 255, 255);font-family:Helvetica;font-size:13px;font-style:normal;font-variant-caps:normal;font-weight:300;letter-spacing:normal;orphans:auto;text-align:left;text-indent:0px;text-transform:none;white-space:pre-wrap;widows:auto;word-spacing:0px;-webkit-tap-highlight-color:rgba(0, 0, 0, 0);-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;background-color:rgb(0, 0, 0);text-decoration:none;display:inline;float:none">Atonement</span>`

## Current Behavior

All style rules are preserved.

## Expected Behavior

All style rules besides bold, italic, and underline should be removed.

**Comment by ruchijn** [comment]
When I copy pasted above, it is not even executing the code that strips the styles. It calls `updateThoughts` from [here](https://github.com/cybersemics/em/blob/dev/src/action-creators/pull.ts#L75) . [Here](https://github.com/cybersemics/em/blob/dev/src/reducers/updateThoughts.ts#L141) `thoughtIndexUpdates` has value as 
```
{
    "e836edfe697337e7150c5212df645410": {
        "id": "e836edfe697337e7150c5212df645410",
        "contexts": [
            {
                "context": [
                    "__ROOT__"
                ],
                "rank": 0,
                "id": "20dd15c5-d015-41f6-9e0a-f4fc7d946689"
            }
        ],
        "created": "2021-10-03T10:47:24.791Z",
        "lastUpdated": "2021-10-03T10:47:24.791Z",
        "updatedBy": "2b3c28d4-3468-47a4-ab93-b66783f0c285",
        "value": "<span style=\"caret-color:rgb(255, 255, 255);color:rgb(255, 255, 255);font-family:Helvetica;font-size:13px;font-style:normal;font-variant-caps:normal;font-weight:300;letter-spacing:normal;orphans:auto;text-align:left;text-indent:0px;text-transform:none;white-space:pre-wrap;widows:auto;word-spacing:0px;-webkit-tap-highlight-color:rgba(0, 0, 0, 0);-webkit-text-size-adjust:none;-webkit-text-stroke-width:0px;background-color:rgb(0, 0, 0);text-decoration:none;display:inline;float:none\">Atonement</span>"
    }
}
```

But `thoughtIndexInvalidated` is empty array. Since `thoughtIndexInvalidated` is empty, these [lines](https://github.com/cybersemics/em/blob/dev/src/reducers/updateThoughts.ts#L149-L153) doesn't execute. 

And hence the code that actually strips the styles doesn't get executed. 

Please let me know if this makes sense. Else we can jump on quick call to discuss further.

**Comment by raineorshine** [comment]
`pull` and `updateThoughts` are not related to stripping styles. Pasted text is passed to `importText`. `updateThoughts` is called after the pasted content has been converted to thoughts.

**Comment by ruchijn** [comment]
If I am understanding the code right, `stripStyleAttribute` is the function that strips out the unneeded style. And this is being called from `formattingNodeToHtml` [here](https://github.com/cybersemics/em/blob/dev/src/util/htmlToJson.ts#L21). Thin is in turn called from `handleFormattingTags` which is called from `himalayaToBlock`. And this is being called [here](https://github.com/cybersemics/em/blob/dev/src/util/htmlToJson.ts#L206). 

`htmlToJson` is being called in `ImportText` [here](https://github.com/cybersemics/em/blob/dev/src/reducers/importText.ts#L121). And when we copy paste the above code, it does execute `importText`. With the above copied code, it comes [here](https://github.com/cybersemics/em/blob/dev/src/reducers/importText.ts#L84) with values as 
```
numLines: 1 
!isRoam: ture
!isRoot(path): true
```

And because of these values, it executes the `if` condition and not `else`. And hence it never executes the function that actually does the stripping of un-wanted styles. 


Please let me know if this makes sense.
