### ISSUE TITLE
Desktop safari shows Share instead of Download

### ISSUE THREAD

**Issue by ruchijn** [cybersemics/em#1170]
### Steps to Reproduce:

Open app in safari. 
Add thoughts and then toggle Export content

<img width="1436" alt="Screen Shot 2021-05-22 at 2 31 28 PM" src="https://user-images.githubusercontent.com/18288628/119237462-eae6e680-bb0a-11eb-9343-e341d9a521ba.png">

### Current Behavior
User is seeing `Share` on desktop safari

### Expected Behavior
User should see `Download` on desktop browsers

**Comment by raineorshine** [comment]
Also we can remove "Copy to clipboard" from mobile since the OS provides that option on the Share popup.
