### ISSUE TITLE
setSelection fails to focus on proper offset.

### ISSUE THREAD

**Issue by shresthabijay** [cybersemics/em#1202]
# Steps to reproduce

```
- guardians <strong>of the </strong><strong>galaxy </strong>
- volume 1
```

- Paste the following
- Set cursor at `volume 1` at offset 0.
- Hit backspace.

# Current behavior

Two thoughts are merged but the cursor position is not after `galaxy` but is after `guardians`.

# Expected behavior

Two thoughts should merge and the cursor position should be at the point of merge i.e after `galaxy`.

# Cause of issue

The current `setSelection` assumes that selection should always be in the  `firstChild` of the editable node. But this assumption is wrong. It won't work properly as soon as there are other nodes introduced from format tags, just like in the example.

To understand the issue, we need to understand how the focus selection and range work.  At first, the editable node can contain more than one text node as `childNodes`. Let's break down the example.

For `guardians <strong>of the </strong><strong>galaxy </strong>`, the node structure would be something like this.

- editable node
  - text (guardians)
  - strong
    - text (of the)
  - strong
    - text (galaxy) 
 
Currently, the setSelection is trying to set focus on text (guardians) at offset which is the length of the full text. But it doesn't only get focused at the end of the `guardians`.

**Comment by shresthabijay** [comment]
# Possible solution.

The solution is to introduce a path to the actual node which needs to be focused. Let's say `focusNodePath`

- editable node
  - text (guardians)
  - strong
    - text (of the)
  - strong
    - text (galaxy) 
    
The path is an array of numbers, each number representing the index of the node respective to the parent node starting from root editable node.
  
If we want to set selection at the beginning of the `galaxy`, the `focusNodePath` must be `[3, 0]` which selects the node text(galaxy). And the offset must be 0.
  
Similarly, if we need to set selection at the end of the `of the` text, the `focusNodePath` can be `[2, 0]` with offset of `7`. It can also be done with `focusNodePath` set to `null` (means it will select `editable node`) and with an offset of 3. This will keep caret at the beginning second `strong` tag which is also the end of the `of the` text.

**Comment by raineorshine** [comment]
@shresthabijay The application is crashing as soon as I paste. Is that not happening for you? On Chrome?

**Comment by shresthabijay** [comment]
> @shresthabijay The application is crashing as soon as I paste. Is that not happening for you? On Chrome?
This seems to an issue with `imporText`. I tested it in the latest `dev`. It's crashing there too. I will create a separate issue for this. Meanwhile if you can continue with the test by manually typing.  You can type `guardians of the galaxy` and then bold `of the galaxy` portion by selection and hitting `command + b`.

**Comment by raineorshine** [comment]
Thanks. FYI the problem exists on v197 so it doesn't seem to be a recent regression.

I will test by pasting one line at a time.

**Comment by raineorshine** [comment]
> Similarly, if we need to set selection at the end of the `of the` text, the `focusNodePath` can be `[2, 0]` with offset of `7`.

"of the" only has 6 characters, so do you mean the offset would be `6`?

**Comment by shresthabijay** [comment]
@raineorshine Pasti

> "of the" only has 6 characters, so do you mean the offset would be `6`?
> 
> >

Yes. offset is basically index. So it should be 6.

**Comment by shresthabijay** [comment]
> I thought offset was the position of the caret within the node? Offset 3 within `editable node` would be `edi|table node`. Is that not what offset is?

By the editable node, I meant actual Editable HTML node. The example shows the dom structure. The editable node has three child nodes of type text, strong and strong respectively. 

 When the range is set at a text node then the offset would mean the position within the text. But when range is set at a node other than text node, the offset basically represents index of one of its child nodes.

**Comment by shresthabijay** [comment]
Here is a great resource on how selection and range work. You can check the dom structure example. https://javascript.info/selection-range

**Comment by raineorshine** [comment]
> > I thought offset was the position of the caret within the node? Offset 3 within `editable node` would be `edi|table node`. Is that not what offset is?
> 
> By the editable node, I meant actual Editable HTML node. The example shows the dom structure. The editable node has three child nodes of type text, strong and strong respectively.

Okay, got it.

> When the range is set at a text node then the offset would mean the position within the text. But when range is set at a node other than text node, the offset basically represents index of one of its child nodes.

I see. This polymorphism is confusing. I'm not sure I agree with the approach the official api took.

> Similarly, if we need to set selection at the end of the `of the` text, the `focusNodePath` can be `[2, 0]` with offset of `7`. It can also be done with `focusNodePath` set to `null` (means it will select `editable node`) and with an offset of 3. This will keep caret at the beginning second `strong` tag which is also the end of the `of the` text.

What is the difference between `focusNodePath: null` and `focusNodePath: [0]`?

Is `focusNodePath` always a 2-tuple or can it have any length? The last item represents a text offset if the second-to-last item is a text node?

**Comment by shresthabijay** [comment]
> What is the difference between `focusNodePath: null` and `focusNodePath: [0]`?
> 
> Is `focusNodePath` always a 2-tuple or can it have any length? The last item represents a text offset if the second-to-last item is a text node?

`focusNodePath` here represents the path to the actual focus node from the editable node. So if its `null` just select the editable node as `focusNode`, if `[0]` it means the `focusNode` should be the first child node of the editable node.

For example:

If we want to set the selection at the very end of the editable node, we can simply `focusNode` as editable node itself (i.e `focusNodePath` is `null`) and then offset should be the length of `childNodes` of `focusNode`.

**Comment by raineorshine** [comment]
Got it! Thank you :)
