### ISSUE TITLE
importText crashes on paste

### ISSUE THREAD

**Issue by shresthabijay** [cybersemics/em#1205]
# Steps to reproduce

```
- guardians <strong>of the </strong><strong>galaxy </strong>
- volume 1
```

- Paste the following.

# Current behavior

Crashes the application.

# Expected behavior

Should work without crashing.

**Comment by onurpolattimur** [comment]
Hi @shresthabijay, I think the problem is that the `<strong>` is not being considered as formatting tags.

https://github.com/cybersemics/em/blob/66855eafb13b103520aaee9d0a7a4a60f00346fd/src/util/convertHTMLtoJSON.ts#L15-L16

We support `<u>` tags, can you also add `<u>` tags too, please?

**Comment by shresthabijay** [comment]
Sure will do.

> Hi @shresthabijay, I think the problem is that the `<strong>` is not being considered as formatting tags.
> 
> https://github.com/cybersemics/em/blob/66855eafb13b103520aaee9d0a7a4a60f00346fd/src/util/convertHTMLtoJSON.ts#L15-L16
> 
> We support `<u>` tags, can you also add `<u>` tag too, please?

Thanks, @onurpolattimur! We do need to support both `strong` and `u` tags. However, I think that solves just a small part of the bigger problem.

If there are elements with `tagName` that are not recognized, it should not crash the application. We should either remove these tags or handle in other ways.

**Comment by shresthabijay** [comment]
https://github.com/cybersemics/em/blob/66855eafb13b103520aaee9d0a7a4a60f00346fd/src/util/convertHTMLtoJSON.ts#L201-L209

@raineorshine @onurpolattimur  `joinChildren` may not always return (Block | Block[]) as intended. In some edge cases, it can return `Block[][]` too. It is because `blocks` itself is of type `(Block | Block[])[]` but it is type asserted to `Block[]`  before it is passed to the `joinChildren`. If the returned data type of `convertHTMLToJSON` is `(Block | Block[])[]` then the `importJSON` will crash. This is exactly what happened when importing the above thoughts.

```
[
    {
        "scope": "guardians",
        "children": []
    },
    [
        {
            "scope": "of the",
            "children": []
        }
    ],
    [
        {
            "scope": "galaxy",
            "children": []
        }
    ]
]
```

Passing the above data to the `joinChildren` will return the following output:

```
[
    {
        "scope": "guardians",
        "children": [
            {
                "scope": "of the",
                "children": []
            }
        ]
    },
    [
        {
            "scope": "galaxy",
            "children": []
        }
    ]
]
```

The output is of type `(Block | Block[])[]` which causes the issue.

This specific issue can be solved by adding `strong` as a formatting tag just like @onurpolattimur mentioned. But there can be cases where we can miss handling some tags and end up in this situation. 

We should discuss how we should handle element tags other than `li`, `ul` and other allowed formatting tags.

**Comment by onurpolattimur** [comment]
> If there are elements with tagName that are not recognized, it should not crash the application. We should either remove these tags or handle in other ways.

We remove the unrecognized/not allowed tags in strip.ts I am not sure but It shouldn't be a problem.

https://github.com/cybersemics/em/blob/66855eafb13b103520aaee9d0a7a4a60f00346fd/src/util/strip.ts#L2

**Comment by shresthabijay** [comment]
> > If there are elements with tagName that are not recognized, it should not crash the application. We should either remove these tags or handle in other ways.
> 
> We remove the unrecognized/not allowed tags in strip.ts before `convertHTMLtoJSON`. I am not sure but It shouldn't be a problem.
> 
> https://github.com/cybersemics/em/blob/66855eafb13b103520aaee9d0a7a4a60f00346fd/src/util/strip.ts#L2

I don't think we can remove tags using `strip` before passing the `convertedText` to the `convertHTMLJSON`. `strip` is meant to used on thought values. It will strip out all the HTML tags except the formatting tags. 

We would want to preserve `li`, `ul`, and the formatting tags. So we may need to write another utility function to do that, that uses already available regex.

**Comment by onurpolattimur** [comment]
I couldn't catch you @shresthabijay. :/  We already preserve these li, ul tags. Can you give an example input that causes the app to crash after adding `strong` and `u` to the `isFormattingTag` condition

**Comment by shresthabijay** [comment]
> I couldn't catch you @shresthabijay. :/ We already preserve these li, ul tags. Can you give an example input that causes the app to crash after adding `strong` and `u` to the `isFormattingTag` condition?

Any tag that is not `li`, `ul` and the allowed formatting tags will crash the app. Let's say user made a type in the import text and typed `stron` instead of `strong`.  The text below will crash even if you add `strong` and `u` to the `isFormatTag` condition. 

```
- guardians <stron>of the </stron><strong>galaxy </strong>
- volume 1
```

**Comment by onurpolattimur** [comment]
Thanks, I got it now. 
As I can see, one of the problems is that the input that you wrote above is not considered as a html input in importText.ts.  
https://github.com/cybersemics/em/blob/a8b5ed6881797e78ff05a238f5c07f87307f6eb8/src/reducers/importText.ts#L111-L115
Because `isHTML` is not true, it doesn't call` parseBodyContent -> strip`  and doesn't remove the not allowed tags. If the isHTML would be true then the application wouldn't crash. But I am not sure whether the result of the imported text would be as we want. 

>  if there are typos it will just import them as text. 

Yes, I agree with you.

I am not sure but maybe we can also strip the decodedInputText preserving formatting and ul, li tags before parsing.

https://github.com/cybersemics/em/blob/a8b5ed6881797e78ff05a238f5c07f87307f6eb8/src/reducers/importText.ts#L118-L120
