### ISSUE TITLE
<u> with child does not import 

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1222]
## Steps to Reproduce

Paste the following:

``` js
- a <u>b</u>
  - c
``` 

## Current Behavior

Nothing happens. 

## Expected Behavior

Thoughts imported as expected, with `b` underlined.

**Comment by onurpolattimur** [comment]
Seems to be related to #1205 and will likely be fixed in #1215.

**Comment by raineorshine** [comment]
Fixed in #1215
