### ISSUE TITLE
Dim disabled toolbar buttons 

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1230]
Toolbar buttons should be dimmed if `canExecute` is false. 

For example: Archive should be dimmed when the `cursor` is null, since the command cannot be executed.

**Comment by ruchijn** [comment]
I was looking at this. But it seems even when `cursor` is `null`, `canExecute` is still set to true. It is not checking for `cursor` value. I think I might need to connect with you on this.

**Comment by raineorshine** [comment]
You're right. In the case of the `archive` shortcut, `canExecute` does not consider the `cursor` at all, though it should:

https://github.com/cybersemics/em/blob/f23343267e25271d900b8e741fb4ced14acaaac5/src/shortcuts/archive.tsx#L76

**Comment by raineorshine** [comment]
I went through all the shortcuts and made sure `canExecute` was correct. You should be good to know now.
