### ISSUE TITLE
Toolbar button animation tweaks

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1231]
## Steps to Reproduce

1. Create thought `a`.
2. Quickly click and release a toolbar button.

## Current Behavior

When the mouse button is quickly released, the dip animation is quickly reversed, showing little change.

In this video, there is a long click (correct) followed by a short click (incorrect).

https://github.com/cybersemics/em/assets/750276/ead547e6-98c8-4efd-b59d-5f8d0af446da

## Expected Behavior

- Complete the full dip animation even if only quickly tapping and releasing.
- Decrease the animation transition duration for a snappier effect.

**Comment by shresthabijay** [comment]
@linghong Any updates?
