### ISSUE TITLE
iOS Safari: =style not rendered on initial load

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1250]
Only occurs in iOS Safari.

## Steps to Reproduce

```js

- a
  - b
    - =style
      - color
        - pink
```

Refresh the page

## Current Behavior

`a/b` is white.

It turns pink after a re-render. 

## Expected Behavior

`a/b` should always be pink.

`=style` should be applied on the initial render.

**Comment by ruchijn** [comment]
@raineorshine I was looking into this and I am not able to replicate it. Am I doing the right steps? 

![render_style](https://user-images.githubusercontent.com/18288628/122621470-a4ca6780-d063-11eb-800b-85b494f82b06.gif)

**Comment by raineorshine** [comment]
Thanks! I tested it on a few different platforms and for some reason this is only occurring on iOS Safari.

**Comment by ruchijn** [comment]
@raineorshine  - I was looking into this more today. It seems the colour is correct depending on which thought is in focus when refreshing the page. 

When I refresh with cursor on `b`, it does render with appropriate colour. But when I have cursor on `a` and hit refresh, it doesn't render in appropriate colour. When I simple don't have any thought focused and refresh, then also `b` is not pink. 

So basically refreshing `http://localhost:3000/~/a/b` renders `b` in correct colour.
`http://localhost:3000/~/a` renders `b` in white
`http://localhost:3000` also renders `b` in white.

Can you please tell me what should be happening in each case or am I missing something. 🤔 

I noticed the same behaviour across chrome and safari. Please see attached. 

![colour_issue_chrome](https://user-images.githubusercontent.com/18288628/131265019-abd8bd8d-3185-481c-8e1c-0e673629d15a.gif)

![colour_issue_safari](https://user-images.githubusercontent.com/18288628/131265037-74a024ba-ab58-4cfa-8158-b53cd5b3dda7.gif)

**Comment by raineorshine** [comment]
3 hrs logged (unpaid)
