### ISSUE TITLE
Note is not rendered after load

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1255]
## Steps to Reproduce

```js
- a
  - b
    - c
      - =note
        - Note 
```

Refresh the page. 

## Current Behavior

Shows “Enter a note”

## Expected Behavior

Should show “Note”

**Comment by shresthabijay** [comment]
@raineorshine Does this issue still persists? I could not recreate it.

**Comment by raineorshine** [comment]
It seems to be working for me!
