### ISSUE TITLE
Strip html when exporting as Plain Text with excludeMeta true

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1284]
## Steps to Reproduce

```
- Hello <b>world</b>
```

Export the thought in Plain Text with Lossless unchecked (which will call exportContext with `excludeMeta: true`)

## Current Behavior

```
- Hello <b>world</b>
```

## Expected Behavior

```
- Hello world
```

**Comment by ruchijn** [comment]
Shouldn't this the HTML tag be controlled by `Plain text` vs `HTML` option and not by `Lossless`? 🤔

**Comment by raineorshine** [comment]
Exactly
