### ISSUE TITLE
Show table column 2 when table is pinned

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1290]
## Steps to Reproduce

```js
- 📱 em
  - Overview
    - =pin
      - true
    - =view
      - Table
    - Goals
      - =children
        - =bullet
          - None
      - =style
        - marginBottom
          - 5px
      - 🥁 Announcement
      - 🎉 Private Beta
    - Domains
      - =children
        - =bullet
          - None
      - 🛠 Development
      - 🏫 Onboarding & Education
      - 👧 Emma & Dot
  - Features
```

Set the cursor on `Features`

## Current Behavior

Table column 2 is hidden (Announcement, Private Beta, etc).

## Expected Behavior

Table column 2 should be dimmed. 

In general, column 2 should always be shown if column 1 is shown.

**Comment by shresthabijay** [comment]
@raineorshine Can you confirm if this issue still persists? It's working properly for me.

**Comment by raineorshine** [comment]
Working!
