### ISSUE TITLE
Scroll jumps on new subthought

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1348]
## Steps to Reproduce

1. Create many nested thoughts and siblings
2. Set the cursor on one of the later thoughts with lots of siblings such that there is a lot of scroll distance. 
3. Activate new subthought (→↓)

## Current Behavior

Scroll jumps to top before re-centering. 

## Expected Behavior

Scroll should not jump. 

## Notes

~It could be Safari's autofocus on the AsyncFocus element. Not sure if it's recentering from showVisibleContent (?) or from autofocus back to the cursor.~

It only seems occurs when the cursor thought has a large number number of previous siblings.  

If it is unavoidable, our best bet may be to improve render performance so we can decrease the delay to center visible content.

https://user-images.githubusercontent.com/750276/125548238-c4c90e03-8c57-4c94-b2ff-573a430687d3.MOV

**Comment by onurpolattimur** [comment]
I tried and I couldn't reproduce the issue. Can you share your thoughts as an example to reproduce the issue, please?

**Comment by raineorshine** [comment]
I tried to get sample data but this is proving to be difficult since it is so tied to performance. The issue was noticed in my personal thoughtspace which has about 30mb of thoughts, however many that is. Even when I duplicate **em** and all descendants (~2,000 thoughts), I still only barely see the problem. I don't see a discrete point of breakage. Rather, it gradually gets worse the worse the overall app performance is.

I think fixing the performance issues themselves will be a better use of our time. I'll keep this issue open until it's no longer a practical problem. Thanks!

**Comment by raineorshine** [comment]
This was caused by mobile Safari jumping to the top on `scrollCursorIntoView` when `scrollY` was 0. Also might be connected to `asyncFocus`. Bumping the scroll position by 1 solved the problem.
