### ISSUE TITLE
Superscript not re-rendered after archive

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1355]
## Steps to Reproduce

```js
- X
  - =pinChildren
    - true
  - Y
    - Z
  - M
    - Z
``` 

Archive one of the `z` thoughts

## Current Behavior

The remaining `z` still shows a superscript of 2. It is fixed as soon as it re-renders. 

## Expected Behavior

The remaining `z` superscript should re-render as soon as its Lexeme changes.

**Comment by onurpolattimur** [comment]
While 'toggle hidden thought' is disabled, after archiving one of the 'Z'  the remaining Z doesn't show superscript. But while 'toggle hidden thought' is enabled, the remaining Z shows superscript of 2 and I think it is expected behavior.

**Comment by raineorshine** [comment]
Yes, it looks like it was fixed somehow!
