### ISSUE TITLE
bumpThoughtDown: Duplicate lexeme context

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1364]
## Steps to Reproduce

```
- a
  - b
```

1. Set the cursor on `a`
2. Activate `bumpThoughtDown` - <kbd>Meta</kbd> + <kbd>Alt</kbd> + <kbd>d</kbd>
3. Move the cursor

## Current Behavior

`a` gets re-rendered with superscript "2"

## Expected Behavior

`a` should only exist in one context and have no visible superscript

**Comment by onurpolattimur** [comment]
I'm not good at this part of 'em' but I have some comments. In bumpThoughtDown recuders, we are creating a reducer flow that contains moveThought, editThought, and creating new thought respectively. After bumpThoughtDown, the state of pushQueue contains 3 items, and one of the thoughtIndexUpdates has value 'a' and context `[__ROOT__]`. So lexeme 'a' will have two contexts and one of them is `__ROOT__`, that's why the superscript value of thought 'a' is 2

As I understand, each of moveThought, editThought, and newThoughts add a new item to `pushQueue`. And the first item of pushQueue array has context `[__ROOT__]` and the current context of the 'a' is `[""]`. So, it adds `[__ROOT__]` to the context of the 'a'. 
Details : 
https://github.com/cybersemics/em/blob/4db13c0b6d84b3531684b6c65e51d4f86b42c409/src/redux-middleware/pushQueue.ts#L174-L180 

I'm not sure but maybe it can be related to the order of the recuders in the reducer flow.


______

I thought on this issue and  I realize that there are two steps to achieve bumpThoughtDown functionality.
- newSubThoughtOnTop with the value of the cursor.
- replace the current value of the thought with an empty string.

I tried and I couldn't see a problem and tests that are related to bumpThoughtDown passed.  What do you think?  These two steps aren't enough?

**Comment by raineorshine** [comment]
> I'm not good at this part of 'em' but I have some comments.

Sure! This is a complicated part of the codebase. Could be a good opportunity to learn (though the thought structure is changing somewhat with #495).

> After bumpThoughtDown, the state of pushQueue contains 3 items, and one of the thoughtIndexUpdates has value 'a' and context `[__ROOT__]`. So lexeme 'a' will have two contexts and one of them is `__ROOT__`, that's why the superscript value of thought 'a' is 2

`bumpThoughtDown` does result in 3 new batches added to the `pushQueue`, however none of them contain a lexeme with 2 contexts.

Notably, there are 2 more batches that are added to the `pushQueue` *after* `bumpThoughtDown` completes. They are triggered by the `pushQueue` middleware.

Here, I log `thoughtIndexUpdates` every time `updateThoughts` is called, and mark the start and end of `bumpThoughtDown`: (I have set `disableThoughtHashing = true` in `globals.ts` to make it easier to read the `thoughtIndex` directly; it doesn't change the functionality.)

![image](https://user-images.githubusercontent.com/750276/126880520-9b802b35-2707-4149-aeb1-ac8ef8280602.png)

As you can see, the very last batch contains lexeme `a` with 2 contexts (ROOT and empty thought). Unfortunately, this means that the bug is not in the `bumpThoughtDown` reducer, but rather in the push/pull mechanism. If I disable the `pushQueue` middleware, the issue is fixed, confirming this hypothesis, but of course that would break persistence. 

I'm not sure the exact relevance of the code you referenced but you seem to be looking in the right direction. @shresthabijay would be more familiar with that particular function than me. Unfortunately it's related to a tricky concurrency issue, and is undoubtedly a weak part of the codebase.

I would trace the invalid batch upstream as far as you can and identify the source. (Maybe you already did that and it is originating from the referenced code?) My best guess is that either there is a bug in `getSyncedThoughtsUpdate` or it is caused by the same concurrency issue behind https://github.com/cybersemics/em/issues/1071#issuecomment-814998712.

I hate to put another issue on hold, but it might be smart to wait for #1071 to be fixed in case it is related.

---

> I thought on this issue and I realize that there are two steps to achieve bumpThoughtDown functionality.
> 
> * newSubThoughtOnTop with the value of the cursor.
> * replace the current value of the thought with an empty string.
> 
> I tried and I couldn't see a problem and tests that are related to bumpThoughtDown passed. What do you think @raineorshine ? These two steps aren't enough?

Yes, that should work. If the `bumpThoughtDown` tests pass and this issue is fixed, then great. Though it will be leaving me a befuddled as to how an issue with the push/pull mechanism can be fixed with changing the `reducerFlow` 😅.

**Comment by onurpolattimur** [comment]
Here is what I have found so far. 

https://github.com/cybersemics/em/blob/4db13c0b6d84b3531684b6c65e51d4f86b42c409/src/reducers/updateThoughts.ts#L121

- moveThought calls updateThoughts and a batch is added to pushQueue in updateThoughts. Here is the thoughtIndexUpdates of the pushQueue[0] state after **moveThought** ends. 

```jsx
{
  "85555565f6597889e6b53a48510e895a": {
    "id": "85555565f6597889e6b53a48510e895a",
    "value": "a",
    "contexts": [
      {
        "context": [
          "__ROOT__"
        ],
        "rank": -1,
        "id": "9fd6b3af-51ee-463b-aa7e-23fd9be2838e"
      }
    ],
    "created": "2021-07-25T11:10:19.373Z",
    "lastUpdated": "2021-07-25T11:13:07.101Z"
  },
  "7a98a957b1d3d1eefa2e131e544e94e9": {
    "id": "7a98a957b1d3d1eefa2e131e544e94e9",
    "value": "b",
    "contexts": [
      {
        "context": [
          "a"
        ],
        "rank": 0,
        "id": "7cd0979b-89b3-4df2-8d84-42152d0f7620"
      }
    ],
    "created": "2021-07-25T11:10:19.630Z",
    "lastUpdated": "2021-07-25T11:13:58.568Z"
  }
}
```

- editThought also calls the updateThought and a batch is added to pushQueue.
Here is the thoughtIndexUpdates of the pushQueue[1] state after **editThought** ends.

```jsx
{
  "85555565f6597889e6b53a48510e895a": null,
  "00000000000000000000000000000000": {
    "value": "",
    "contexts": [
      {
        "context": [
          "a"
        ],
        "id": "7cd0979b-89b3-4df2-8d84-42152d0f7620",
        "rank": 0
      },
      {
        "context": [
          "__ROOT__"
        ],
        "id": "9fd6b3af-51ee-463b-aa7e-23fd9be2838e",
        "rank": 0
      },
      {
        "context": [
          "__ROOT__"
        ],
        "rank": -1,
        "id": "9fd6b3af-51ee-463b-aa7e-23fd9be2838e"
      }
    ],
    "created": "2021-07-25T11:10:19.385Z",
    "lastUpdated": "2021-07-25T11:31:57.696Z"
  },
  "7a98a957b1d3d1eefa2e131e544e94e9": {
    "id": "7a98a957b1d3d1eefa2e131e544e94e9",
    "value": "b",
    "contexts": [
      {
        "context": [
          ""
        ],
        "rank": 0,
        "id": "7cd0979b-89b3-4df2-8d84-42152d0f7620",
        "archived": "2021-07-25T11:31:57.697Z"
      }
    ],
    "created": "2021-07-25T11:10:19.630Z",
    "lastUpdated": "2021-07-25T11:31:57.697Z"
  }
}
```

- createThought also calls the updateThought and a batch is added to pushQueue. Here is the thoughtIndexUpdates of the pushQueue[2] state after **editThought** ends.

```jsx
{
  "85555565f6597889e6b53a48510e895a": {
    "value": "a",
    "contexts": [
      {
        "context": [
          ""
        ],
        "id": "2334ae9e-2676-46ff-9b48-91d2c5e79a61",
        "rank": -1
      }
    ],
    "created": "2021-07-25T11:40:58.615Z",
    "lastUpdated": "2021-07-25T11:40:58.615Z"
  }
}
```

After bumpThoughtDown ends, pushQueue is called after a while but before pushQueue, here is the state of the thought 'a'. As you can see, the thought 'a' has only one context.

```jsx
{
  "value": "a",
  "contexts": [
    {
      "context": [
        ""
      ],
      "id": "2334ae9e-2676-46ff-9b48-91d2c5e79a61",
      "rank": -1
    }
  ],
  "created": "2021-07-25T11:40:58.615Z",
  "lastUpdated": "2021-07-25T11:40:58.615Z"
}
```

Now there are 3 items in state.pushQueue and pushQueue will process these items. But the last item of the pushQueue state has **pendingLexeme** for thought 'a' (85555565f6597889e6b53a48510e895a) and it causes to call pullLexemes.

https://github.com/cybersemics/em/blob/4db13c0b6d84b3531684b6c65e51d4f86b42c409/src/redux-middleware/pushQueue.ts#L203-L206

And in pullLexemes it gets thought from DB and at this time, the thought 'a' has context `[__ROOT__]` in DB. And it updates the context of the thought 'a' as `[__ROOT__]`

While processing batches in pushQueue, on line #189 it concats batch context (`[""]`) with the current context (`["__ROOT__"]`)

https://github.com/cybersemics/em/blob/4db13c0b6d84b3531684b6c65e51d4f86b42c409/src/redux-middleware/pushQueue.ts#L189

So, lexeme 'a' will have two contexts.

**Comment by raineorshine** [comment]
Thanks! I have a couple questions.

> Now there are 3 items in state.pushQueue and pushQueue will process these items. But the last item of the pushQueue state has **pendingLexeme** for thought 'a' (85555565f6597889e6b53a48510e895a) and it causes to call pullLexemes.

Why are there `pendingLexemes`? Lexeme `a` should already be loaded.

> And in pullLexemes it gets thought from DB and at this time, the thought 'a' has context `[__ROOT__]` in DB. And it updates the context of the thought 'a' as `[__ROOT__]`

I think we have a problem here. Older lexemes (e.g. prematurely pulled from local storage) should never overwrite newer lexemes (that are already in Redux state). The `lastUpdated` field should be compared. This is normally handled by reconcile:

https://github.com/cybersemics/em/blob/4db13c0b6d84b3531684b6c65e51d4f86b42c409/src/reducers/reconcile.ts#L9-L10

But `reconcile` is only called if there are remote (Firebase) results. In both `pull` and `pullLexemes`, reconciliation is bypassed and `updateThoughts` is called directly:

https://github.com/cybersemics/em/blob/4db13c0b6d84b3531684b6c65e51d4f86b42c409/src/action-creators/pull.ts#L46-L55

https://github.com/cybersemics/em/blob/4db13c0b6d84b3531684b6c65e51d4f86b42c409/src/action-creators/pullLexemes.ts#L26-L37

`updateThoughts` does not compare timestamps, it just merges directly into State. This is a problem if `pull` returns older entries. I think we need to filter out older lexemes and contexts before passing them to `updateThoughts`. At least when given `local: false, remote: false`, which corresponds exclusively to the two call sites above.

**Comment by onurpolattimur** [comment]
> Why are there pendingLexemes? Lexeme a should already be loaded.

Actually, no. Here is the current reducer flow of bumpThoughtDown.
```
- moveThought 
- editThought 
- createThought
```
In step 2, we are changing the value of the lexeme. `a -> ""` So, 'a' doesn't seem loaded anymore.
In step 3, we are creating a thought with the value 'a'. createThought calls updateThought with thoughtIndexUpdates and in updateThoughts pendingLexemes contain 'a' because 'a' doesn't exist in the state.
_______

Yes, you are right. We should compare timestamps. If the updatedDate of thought in the state is lower than the localLexemes updatedDate, it should update the thought. I tried and it looks working. I added ` isNewer(localLexemes[index]!, thoughtIndex[thoughtHash])` condition to line 17.

https://github.com/cybersemics/em/blob/57c8d079a11eaee1105e328e03a17dfd848bc967/src/action-creators/pullLexemes.ts#L14-L19

Am I right, @raineorshine ?

**Comment by raineorshine** [comment]
> In step 2, we are changing the value of the lexeme. `a -> ""` So, 'a' doesn't seem loaded anymore.

Got it! Thanks!

> Yes, you are right. We should compare timestamps. If the updatedDate of thought in the state is lower than the localLexemes updatedDate, it should update the thought. I tried and it looks working. I added ` isNewer(localLexemes[index]!, thoughtIndex[thoughtHash])` condition to line 17.

That's right, however notice that `localLexemesIndex` is [also used passed to reconcile](https://github.com/cybersemics/em/blob/57c8d079a11eaee1105e328e03a17dfd848bc967/src/action-creators/pullLexemes.ts#L48). If you filter out lexemes before passing them to `reconcile`, then `reconcile` will incorrectly think that local storage does not have the lexemes and will try to push them to local storage.

Instead, you need to only perform the `isNewer` check when `reconcile` is bypassed. That is, when `!remoteLexemes`. You should be able to do `(remoteLexemes || isNewer(localLexemes[index]!, thoughtIndex[thoughtHash]))`.

**Comment by onurpolattimur** [comment]
I made changes but the test '`editing thoughts to new value with related pending lexeme`' is broken.
https://github.com/cybersemics/em/blob/57c8d079a11eaee1105e328e03a17dfd848bc967/src/redux-middleware/__tests__/pushQueue.ts#L23-L24

I tested it manually and verified the issue. We are filtering thoughts that are coming from DB because lastUpdated value is lower than the lastUpdated of the loaded thought. We need to merge them, I think we missed this case.

What do you think? It seems we shouldn't compare the lastUpdated in pullLexeme.

**Comment by raineorshine** [comment]
How do we distinguish the case where lexemes should be merged (#1074) from the case where a lexeme should be overwritten (this issue)?

**Comment by onurpolattimur** [comment]
I am not sure but it doesn't seem a general problem to me. Do you have any cases that cause this issue?

**Comment by raineorshine** [comment]
The case would be the one originally described in this issue. A related case is a race condition where push outraces pull. A last-write-wins strategy (isNewer) would potentially mitigate the race condition so it at least wouldn't do any damage. We will be removing the pull-before-push behavior though once subscriptions are working. That will either solve the problem or give it a new face 😄. 

The correctness of an update should not depend on the order of operations. That's why I would consider it a general problem with the pull mechanism, which incorrectly merges Lexemes in cases like this. 

You found a specific solution to this issue, so perhaps that is the best route to take for now. To remove the ordering issues and race conditions would require a more sophisticated syncing mechanism, which isn't something I want to build myself (a second time 😅). We need just enough duct tape to make the current implementation work for the beta 😂.

**Comment by onurpolattimur** [comment]
Yes, because it is related to race conditions the issue doesn't seem much possible to occur from the end-users perspective. I mean, if I do the 3 steps manually that bumpThoughtDown do, I won't see this issue.

> You found a specific solution to this issue, so perhaps that is the best route to take for now. To remove the ordering issues and race conditions would require a more sophisticated syncing mechanism, which isn't something I want to build myself (a second time 😅). We need just enough duct tape to make the current implementation work for the beta 😂.

Okay, I will apply the solution for now 😂
