### ISSUE TITLE
Superscript position is wrong at smaller font size

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1365]
## Steps to Reproduce

```
- A
  - I am in continuous creative response to everything that arises
- B
  - I am in continuous creative response to everything that arises
```

- Use mobile device or set screen width so that the subthought text breaks after "response to".
- Set Font Size to 14 using the footer controls.

## Current Behavior

Superscript appears in the middle of the second line. 

![image](https://user-images.githubusercontent.com/750276/126855203-daa59178-5161-41c0-be58-a6d57646d8b9.jpeg)

## Expected Behavior

Superscript should appear at the end of the thought.

**Comment by ruchijn** [comment]
I am not sure but seems we are rendering `ThoughtAnnotation` [here](https://github.com/cybersemics/em/blob/dev/src/components/Thought.tsx#L450). And then `StaticThought` at [here](https://github.com/cybersemics/em/blob/dev/src/components/Thought.tsx#L461). And we render thought inside `ThoughtAnnotation` but hide it. We render superscript in `ThoughtAnnotation` and it is not set to hidden. 

Then we also render thought in `StaticThought` And this thought is visible but superscript is not. So we are rendering thought in separate tag than superscript. Hence the position issue comes up. If thought and superscript are rendered from same tag then the misalignment doesn't happen.

**Comment by raineorshine** [comment]
Awesome thanks!

> It seems we are rendering `ThoughtAnnotation` [here](https://github.com/cybersemics/em/blob/dev/src/components/Thought.tsx?rgh-link-date=2021-09-14T10%3A23%3A14Z#L450). And then `StaticThought` at [here](https://github.com/cybersemics/em/blob/dev/src/components/Thought.tsx?rgh-link-date=2021-09-14T10%3A23%3A14Z#L461). And we render thought inside `ThoughtAnnotation` but hide it. We render superscript in `ThoughtAnnotation` and it is not set to hidden.

Yes, the component hierarchy is like this:

- ThoughtContainer (Thought.tsx)
  - Bullet
  - ThoughtAnnotation
    - StaticSuperscript
  - StaticThought
    - BulletCursorOverlay
    - Editable
    - Superscript
  - Subthoughts
    - ...

> Then we also render thought in `StaticThought` And this thought is visible but superscript is not. So we are rendering thought in separate tag than superscript. Hence the position issue comes up. If thought and superscript are rendered from same tag then the misalignment doesn't happen.

Yes, that's right. Unfortunately, rendering them in the same tag changes the click area, which causes the regression that occurred. Let me explain the purpose of `Thought` and `ThoughtAnnotation` and why the editable thought and superscript are rendered the way they are.

Here is `StaticThought`. I have hidden `ThoughtAnnotation` for clarity. You can see that it takes up the full container width. This allows the user to click anywhere to the right of the thought text to select it. We could try to do make an artificial "click area" element to the right, but it would require a bit more positioning logic to ensure that it fit the space, and we would have to add custom click logic to ensure that the selection behaved as if you were clicking on the thought itself.

![image](https://user-images.githubusercontent.com/750276/133469945-c8cc3644-f828-4421-899e-5683d0792493.png)

Here is `ThoughtAnnotation`. I have hidden `StaticThought` for clarity. As you can see, the hidden thought text is rendered inline rather than full width:

![image](https://user-images.githubusercontent.com/750276/133469951-38b6be24-2070-4808-84e8-24f9bf091e29.png)

When they overlap, the superscript is positioned correctly:

![image](https://user-images.githubusercontent.com/750276/133470303-7b7c3114-1147-473d-a368-cc1b6ce071d3.png)

The thought text is hidden but still rendered in `ThoughtAnnotation` in order to shift the superscript over to the correct position. If we rendered the superscript was rendered at the end of `StaticThought`, it wouldn't be rendered inline.

It may be possible to restructure the component hierarchy so that the visible thought and visible superscript are rendered in the same tag, but we would have to come up with a solution for the extended click area. This approach seems riskier to me since it involves more significant changes.

I think it would be worth first investigating if the current approach is fundamentally flawed, or if it can be salvaged. In principle, `StaticThought` and `ThoughtAnnotation` should render to exactly the same measurements and break in exactly the same place, just with the thought text visible in one and the superscript visible in the other. That's the intention with the current implementation.

I wonder if `superscript={false}` was supposed to render the Superscript only hidden. That would produce the situation described above.

What do you think?

**Comment by ruchijn** [comment]
**Current render:** 
```
<div class="thought-container">
  <span class="bullet">
    <span class="glyph">•</span>
  </span>
  <span class="drop-hover" style="display: none;"></span>
  <div class="thought-annotation">
    <div class="subthought">
      <span class="subthought-text">I am in continuous creative response to everything that arises</span>
      <span class="superscript-container">
        <span class="num-contexts"><sup>2</sup></span>
      </span>
    </div>
  </div>
  <div class="thought">
    <span class="bullet-cursor-overlay">•</span>
    <div class="preventAutoscroll editable editable-957e5548ec622ae38523ad760f6566b7" placeholder="This is an empty thought" contenteditable="true" style="opacity: 1;">
      I am in continuous creative response to everything that arises
    </div>
    <span class="superscript-container"></span>
  </div>
</div>
```

**After change render:**
```
<div class="thought-container">
  <span class="bullet">
    <span class="glyph">•</span>
  </span>
  <span class="drop-hover" style="display: none;"></span>
  <div class="thought-annotation">
    <div class="subthought">
      <span class="subthought-text">I am in continuous creative response to everything that arises</span>
      <span class="superscript-container" style="visibility: hidden;">
        <span class="num-contexts"><sup>2</sup></span>
      </span>
    </div>
  </div>
  <div class="thought">
    <span class="bullet-cursor-overlay">•</span>
    <div class="preventAutoscroll editable editable-957e5548ec622ae38523ad760f6566b7" placeholder="This is an empty thought" contenteditable="true" style="opacity: 1;">
      I am in continuous creative response to everything that arises
      <span class="superscript-container">
        <span class="num-contexts"><sup>2</sup></span>
      </span>
    </div>
  </div>
</div>
```

After making this change, it seems that the extended click area remains as what it should be which is full width and the superscript is rendering correctly. I have made this change in the browser itself to test. This will be a big change to implement as it will modify how we are using `ContentEditable`. In addition to what thought it renders, it will also need to take a child that gets append to the thought. I have tested this with long thought as well as small thought. 

Currently the width of hidden thought is not full width. It is flexible based on the thought that gets rendered. Hence the `superscript` is also flexible. And that is what is causing the issue of it not being rendered properly. 

Ideally, the tags that needs to render in parallel, should be under same HTML tag. Else we might find a way to fix it on one browser or device but it won't be universal fix across all. We can discuss this further on Monday call.

**Comment by raineorshine** [comment]
> After making this change, it seems that the extended click area remains as what it should be which is full width and the superscript is rendering correctly. I have made this change in the browser itself to test. This will be a big change to implement as it will modify how we are using `ContentEditable`. In addition to what thought it renders, it will also need to take a child that gets append to the thought. I have tested this with long thought as well as small thought.

Wouldn't that unintentionally make the superscript editable?

> Currently the width of hidden thought is not full width. It is flexible based on the thought that gets rendered. Hence the `superscript` is also flexible. And that is what is causing the issue of it not being rendered properly.

I think we need to go a little further to explain the problem in the specific case. You suggest that having an inline thought and an inline superscript causes the rendering problem, but why only in this one case? It works correctly for single and multiline strings of many other font sizes. What is special about this case? When we can isolate the specific case where the problem occurs, we can formulate a specific solution. Maybe you have already identified this, and just need to explain it at a greater level of detail for me.
