### ISSUE TITLE
Export Markdown (basic)

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1381]
Add Markdown as an export option. Start with a basic implementation that is the same as Plain Text but converts `<b>` and `<strong>` to `**`, and `<i>` and `<em>` to `*`.

**Comment by ruchijn** [comment]
I was looking at if there are any readily available package for this. Seems `https://github.com/thetutlage/html-to-markdown` is a good candidate. 

Before I go down deeper, do you want to have a custom function in our codebase for this or should we entertain over the shelf option that we can find?

**Comment by raineorshine** [comment]
I think a 3rd party library is a great idea. 

`html-to-markdown` only has 9 stars and hasn't been updated in 6 years ago. The main candidates appear to be [showdown](https://github.com/showdownjs/showdown), [turndown](https://github.com/mixmark-io/turndown), and [breakdance](https://github.com/breakdance/breakdance). You can use a tool like [npmcompare](https://npmcompare.com/compare/breakdance,html-to-markdown,showdown,turndown) to get an overview of popularity and activity levels of multiple npm packages. I think `turndown` is the best choice since it has the most recent activity.

**Comment by ruchijn** [comment]
I was playing with different libraries. 

If my HTML export is 
```
<ul>
  <li>__ROOT__  
    <ul>
      <li>a</li>
      <li><b>b</b></li>
      <li><i>c</i></li>
      <li><b><i>d</i></b></li>
    </ul>
  </li>
</ul>
```

it generates output as belwo when I use `html-to-markdown`
```
__ROOT__
  a
  ** b **
  * c *
  ** * d ** *
```

But if I use `turndown`, it generates output as 
```
\_\_ROOT\_\_ a \*\*b\*\* \*c\* \*\*\*d\*\*\*
```

This is with the setting that comes out of box. If you have a preference then plz let me know else I will keep looking if there is a better lib.

**Comment by raineorshine** [comment]
In Markdown, `li`'s are represented as lines starting with `-`, e.g. `- a`, `- b`, `- c`, etc. Our Plain Text export type already exports nested thoughts in this way. We just need to convert each thought's content to markdown.

e.g.

```md
- Normal text
  - <b>Bold</b> text
```

Should output the following Markdown:

```md
- Normal text
  - **Bold** text
```

I could see it being useful to convert up to 6 levels of nested thoughts to headings, but that's out of scope of this feature.

**Comment by raineorshine** [comment]
We need to convert one thought at a time to markdown, not the exported HTML. 

It's not relevant for us, but `turndown` is correctly escaping `- `. The only reason `html-to-markdown` ignores them is because it doesn't properly handle dashes. Inactiveness aside, we generally don't want to design around what could be considered a bug.
