### ISSUE TITLE
Render Markdown formatting

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1382]
Render `**bold**` and `*italic*` as **bold** and *italic* when not editing.

Render `**bold**` and `*italic*` as-is while editing (when the caret is on the thought; not just when the cursor is on the thought). 

You can see how the rendered value is conditionally modified here:

https://github.com/cybersemics/em/blob/06012202024a2a6734abcc950669ea0a8aa880cf/src/components/Editable.tsx#L717-L725

**Comment by ankitkarna99** [comment]
@raineorshine, I have a query. Let's say on a thought on some parts I use `CTRL + B` to make the text bold and in some parts I wrap with double asterisks ( `**` ) like markdown to make the text bold. Now, when I go back to the thought, should the text which was made bold with `CTRL + B` be wrapped with double asterisks?

**Comment by raineorshine** [comment]
Text that was made bold with <kbd>CTRL</kbd> + <kbd>B</kbd> would not be wrapped in `**`. I imagined them as two different ways to do the same thing. Note that using <kbd>CTRL</kbd> + <kbd>B</kbd> is the same as wrapping the selected text in `<b>` and `</b>`.

I could see the argument to convert `**` to `<b>` in order to have a single syntax for bold text.
