### ISSUE TITLE
Extend droppable area when there is empty space below a thought

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1386]
If there is empty space below a thought, extend the droppable area of the drop target to make it easier to drop where desired.

## Steps to Reproduce

```
- a
  - b
    - c
    - d
- x
```

1. Set the cursor on `d`
2. Drag `c` and drop it below `d`

## Current Behavior

There is a very small amount of space differentiating the `x`, `a`, and `b` drop targets, making it hard to choose the correct one.

<img width="403" alt="image" src="https://github.com/cybersemics/em/assets/750276/90d83dc8-1247-4684-8aff-b33c28dea547">

## Expected Behavior

We should take advantage of the empty space and increase the size of the drop targets at the bottom of the visible thoughts.

- Extend the height of `b` and `d` by 1em.
- Extend the height of `a` by 1.2em
- Extend the height of `x` by 1.4em
- etc

There can only be one child (`d`) and one sibling (`b`), but many cliff drop targets (`x` and `a`).

![Image 6-20-24 at 1 11 PM](https://github.com/cybersemics/em/assets/750276/87b194f3-9ee9-4cc0-91db-6e1cfac7f854)

**Comment by Zubair286** [comment]
Let me confirm, we need to increase the height of `DropEnd` relative to the depth starting from deepest like b`b`and `d`, do I understand this right?

**Comment by raineorshine** [comment]
I'm not sure exactly if it's `DropEnd`, but yes, the height of the drop targets at the cliff should be increased relative to depth.
