### ISSUE TITLE
Undo/Redo: Cursor restored incorrectly after undo archive

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1389]
## Steps to Reproduce

1. Create thought `a`
2. Set the cursor to `null`
3. Refresh the page
4. Set the cursor to `a`
5. archiveThought
6. undo

## Current Behavior

Cursor disappears. 

## Expected Behavior

Cursor should be on `a`, since that is where the cursor was before `archiveThought` was activated.

Navigation actions immediately _after_ the last edit should be grouped and undone with the edit. 

Navigation actions immediately _before_ the last edit should not be undone.  

(The reverse is true for redo.)

**Comment by karunkop** [comment]
Are you sure the current behavior just that cursor disappears ? When I press undo after the mentioned steps , nothing happens.
