### ISSUE TITLE
Superscript of root grandchild not visible on refresh

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1401]
Tested on iOS Safari. 

## Steps to Reproduce

```js
- a
  - b
    - c
- d
  - c
``` 

1. Set the cursor on `d`. 
2. Refresh

## Current Behavior

`c` has no superscript. 

It is fixed when there is a re-render. 

## Expected Behavior

`c` should have a superscript of 2.

**Comment by ruchijn** [comment]
Fix for #1419 also fixes this issue.

**Comment by ruchijn** [comment]
@raineorshine - I tested this one against `dev` after https://github.com/cybersemics/em/pull/1437 was merged. This is fixed.
