### ISSUE TITLE
Context View does not show Settings contexts

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1412]
Thoughts that exist in Settings, e.g. "Tutorial", "on", "off", do not show up in the Context View of a thought with the same Lexeme.

## Steps to Reproduce

Create thought "Tutorial"

## Current Behavior

Tutorial superscript shows "2", incorrectly including the `EM/Settings/Tutorial` context which is `=hidden`.

## Expected Behavior

Tutorial should not have a superscript in this case. Hidden contexts should not count towards the number of contexts in a superscript.

**Comment by ruchijn** [comment]
I was looking into this. And in [here](https://github.com/cybersemics/em/blob/dev/src/selectors/isAncestorsVisible.ts#L16), we are checking for if the context has a child with `value` as `=hidden`. If so, filter that context based on check done [here](https://github.com/cybersemics/em/blob/dev/src/selectors/getContextsSortedAndRanked.ts#L8). 

And context `['__EM__', 'Settings', 'Tutorial']` does have a child with `value` `=hidden`. Hence it is filtered. And we do not see 2 contexts.

**Comment by raineorshine** [comment]
Ah, okay. I guess it was intentional! In that case, let's preserve that behavior, but bring the superscript into alignment with it. i.e. Do not count hidden thoughts in the number of contexts rendered in the superscript. I will update the original post.
