### ISSUE TITLE
Log out of all tabs

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1413]
When a user logs out of one tab, log them out of all tabs.

**Comment by ruchijn** [comment]
Hi Raine, I was looking at this one. I had the app opened in 2 tabs. I noticed different behaviours in chrome and safari. I wasn't able to test in FF. 

**Chrome:** I logged in the app. I opened the app in 2nd tab. In 2nd tab, it did recognize me as logged in user too. When I logged out in one of the tabs, it logged me out from all tabs. But the tab I logged out in, shows me welcome screen. But the other tab still considers me as logged out but shows my thoughts. 
![logout_em_chrome](https://user-images.githubusercontent.com/18288628/131251205-2d5b1889-84e7-496e-8aa0-642513be5463.gif)


**Safari:** In here, the 2nd tab doesn't even take me as logged in user even when I am logged in 1st tab. 
![logout_em_safari](https://user-images.githubusercontent.com/18288628/131251038-2ca97711-9bc4-43cb-ad17-1ec94060d931.gif)

**Comment by raineorshine** [comment]
Thanks Ruchi, good observations. We will need to synchronize log-in state across all tabs eventually.

**Comment by ruchijn** [comment]
So once they log out, all tabs should should welcome screen, right. I have tried above in private mode for both chrome and safari as regular browsers still gives me error, even after clearing local storage. 😞

**Comment by raineorshine** [comment]
Yes, that's right.
