### ISSUE TITLE
Superscript not re-rendered on archive

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1420]
## Steps to Reproduce

```
- a
  - b
- b
```

Archive `a/b`

## Current Behavior

`a/b` still shows superscript 2. 

## Expected Behavior

`a/b` should have no superscript after `b` is removed.

**Comment by ruchijn** [comment]
I am not able to replicate this. But I am suspecting that this might get fixed with #1419 as well.

**Comment by raineorshine** [comment]
I am unable to reproduce as well.
