### ISSUE TITLE
Sort order changes when editing a thought to empty

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1435]
This is a bug in [resortEmptyInPlace](https://github.com/cybersemics/em/blob/dev/src/selectors/getChildren.ts#L105-L146) or related logic.

## Steps to Reproduce

```js
- test
  - =sort
    - Alphabetical
      - Asc
  - c
  - b
  - a
```

Edit `a` to the empty thought.

## Current Behavior

- test
  - b
  - [empty]
  - c

## Expected Behavior

Sort order should not change:

- test
  - [empty]
  - b
  - c

**Comment by ruchijn** [comment]
Currently, when the values are there, they are sorted based on `value`. But when the value becomes empty, what should the thoughts be sorted by? `rank` won't be the right one to use. 🤔 

I tested with
```
- test
  - =sort
    - Alphabetical
      - Asc
  - c
  - w
  - q
  - b
  - a
  ```

But the ranking was not in order. I tried getting the value of `sorted` at [here](https://github.com/cybersemics/em/blob/dev/src/selectors/getChildren.ts#L100). And it came back as:
<img width="602" alt="Screen Shot 2021-09-26 at 4 58 04 PM" src="https://user-images.githubusercontent.com/18288628/134824014-3fa48cb2-bb9f-4c39-9f56-e35c8b94aa00.png">


So rank is based on how the thoughts were entered.

**Comment by raineorshine** [comment]
`resortEmptyInPlace` moves empty thoughts to the place where they were created, even when the rest of the list is sorted by value. This allows new thoughts to be intuitively placed in a sorted list, and then become autosorted into place once they are non-empty.

**Comment by raineorshine** [comment]
As far as I can tell, we will have to set a flag on an empty thought that has not been edited. Otherwise there is no way to differentiate a new empty thought (which should be sorted to the point of creation) and an edited empty thought (which should be sorted in the same place it was before its last character was deleted).

Thus, some empty thoughts may be sorted with one algorithm, and some with the other.

**Comment by raineorshine** [comment]
A better solution would be to sort empty thoughts according to a hidden `sortValue`. It can be set on creation and updated on edit.
