### ISSUE TITLE
Implement cursor persistence with independent editing

### ISSUE THREAD

**Issue by shresthabijay** [cybersemics/em#1445]
# Issue

We only get context from the URL.  With independent editing #1349 , the path is now an array of thought ids. Since we have only context, we don't have an actual path to pull the thoughts for cursor persistence from the URL.

**Comment by shresthabijay** [comment]
@raineorshine  One solution would be to start from the root and recursively find and pull the thoughts for the given context. Then set the cursor to initialized. If not found initialize the cursor with `HOME_CONTEXT`.

**Comment by shresthabijay** [comment]
> We should be able to load the cursor in a single pull, at least to display its children immediately. If we need to load its ancestors recursively in the background we can do that.
> 
> I'm not sure I'm fully addressing the issue though. Feel free to expand if there is more to the problem. I probably need to get reacquainted with the details anyway. The previous implementation was nontrivial since the URL did not contain enough information for a proper cursor `Path`.

We are storing `context` in the URL. However, we need to recursively pull the entire context from the root to get the `cursor` actual thought.

**Comment by shresthabijay** [comment]
@raineorshine  Why don't we store the cursor on the `localStorage`, that way we can pull the cursor in a single pull on app load. Do we really need to use `URL` for cursor persistence?

**Comment by raineorshine** [comment]
## Requirements

- URL consists of context + id, e.g. `/~/a/b/c/3a519db4-9893-4c9e-a693-84dd9fea4174`
- The URL is persisted to local storage when the cursor changes
- On page refresh, the URL is decoded and the cursor is set
- If a different URL is pasted in the address bar, the page will navigate to the correct context
