### ISSUE TITLE
Export real-time count is too high

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1450]
The real-time count estimate is too high, causing a jump back when it is fully loaded. It would be better to be more conservative and jump forward at the end than have to jump back.

**Comment by shresthabijay** [comment]
Can you elaborate a little on this issue?

**Comment by raineorshine** [comment]
There are two different ways to count thoughts. 

1. sum up the thoughts passed to the [onLocalThoughts](https://github.com/cybersemics/em/blob/dev/src/action-creators/pull.ts#L93) callback. This is used as thoughts are being pulled:

https://github.com/cybersemics/em/blob/3dc1a9cf61f05a2a5f824f25173512fad3a90014/src/components/ModalExport.tsx#L58-L65

2. after all thoughts are pulled, count the thoughts in the export text:

https://github.com/cybersemics/em/blob/3dc1a9cf61f05a2a5f824f25173512fad3a90014/src/components/ModalExport.tsx#L280-L290

I've noticed some cases where #1 is a higher number than #2, causing the number to increase steadily and then drop suddenly at the end. My personal thought space is not causing the issue currently, so I will look out for another case and provide exact steps to reproduce.

**Comment by raineorshine** [comment]
Closing due to lack of exact steps to reproduce.
