### ISSUE TITLE
Table column 2 not visible with =focus parent

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1457]
## Steps to Reproduce

``` 
- a
  - =focus
    - Zoom
  - b
    - =pin
      - true
    - c
  - d
    - =pin
      - true
    - =view
      - Table
    - e
      - f
``` 

Set the cursor on `b`. 

## Current Behavior

`f` is hidden by the autofocus.  

## Expected Behavior

`f` should be visible. 

If a table is visible, column 2 should always be visible. 

## Notes

Only a problem with `=focus/Zoom`, `=pin/true`, and `=view/Table`. I suspect that `=focus/Zoom` is overriding the table visibility logic.

May be a duplicate of #1330. I would work on them together.

**Comment by ankitkarna99** [comment]
@raineorshine I cannot reproduce the issue using the text content provided above. But I can reproduce the issue stated in #1330. Also, the table rows seem a little off when I paste the above text into em.

**Comment by raineorshine** [comment]
The issue seems to be obscured by a regression! I'll create a new issue for it. Once that is fixed, this is likely reproducible.
