### ISSUE TITLE
Imported text when cleared throws an error

### ISSUE THREAD

**Issue by karunkop** [cybersemics/em#1494]
## Steps to reproduce
- Create any thought 'xyz'.
- Delete the text you just created completely but make sure you are still in edit mode
- Paste a random string
- Now try to delete the string you just pasted either by navigating the caret to the end and hitting backspace or just press delete 
   from where the cursor initially is.

## Current Behavior
- Error is shown as Cannot read properties of undefined (reading 'lastUpdated')

## Expected Behavior
- No error should be shown while clearing the imported text.

**Comment by raineorshine** [comment]
I'm not able to reproduce. I must be misinterpreting your instructions. Can you watch this and let me know what I'm doing wrong?

https://user-images.githubusercontent.com/750276/163715429-806c70b5-f5d2-4b9c-b083-bbcb716019a5.mov

**Comment by karunkop** [comment]
> I must be misinterpreting your instructions. Can you watch this and let me know what I'm doing wrong? I'm not getting the error.
> 
>  Screen.Recording.2022-04-17.at.8.58.42.AM.mov

https://user-images.githubusercontent.com/40414929/163716193-7eafa969-1c58-49e6-bede-0db3246d777b.mp4

**Comment by karunkop** [comment]
https://user-images.githubusercontent.com/40414929/163716303-631aee6f-6199-4bbc-986d-2beddb48f3b1.mp4

**Comment by karunkop** [comment]
> I must be misinterpreting your instructions. Can you watch this and let me know what I'm doing wrong? I'm not getting the error.
> 
>  Screen.Recording.2022-04-17.at.8.58.42.AM.mov

(https://www.loom.com/share/ba23f8c5193d40708bae7d16a2fdd127) 
I was unable to upload .mp4 media file

**Comment by raineorshine** [comment]
Thanks, I can reproduce now.
