### ISSUE TITLE
Context Layers (inner context)

### ISSUE THREAD

**Issue by rabbit** [cybersemics/em#15]
A thought can contain more than one context to view

example `Things I Like Todo` could hold two context views
* `Things I Like Todo`
* `Todo`

to differentiate between context views, the active context view is underlined. if "Todo" is underlined then "Things I Like Todo" is inactive. when entering context view mode, the most general assumption possible is the default. if "Things I Like Todo" is a valid context view, it is selected by default otherwise "Todo" is selected by default.

to toggle between context views, first enter context view mode then (if the desired context is not already selected by default) tap the thought until the correct context view is underlined. each tap cycles through the possibilities in a loop. for the example, tapping would flip between "Things I Like Todo" and "Todo". tapping is only available once in a context view mode. outside of context view mode, tapping enters edit mode as expected.

open questions
* should it matters where a user taps? I'm inclined to say it shouldn't so that tapping "Things" repeatedly toggles between "Things I Like Todo" and "Todo" which resolves ambiguous taps but then makes it maybe less intuitive that tapping the context the user wants to select won't necessarily select it?

**Comment by raineorshine** [comment]
> A thought can contain more than one context to view

> example Things I Like Todo could hold two context views

Yes. I would say it as, any substring/subphrase of a thought can serve as a thought itself, and thus be rendered in a context view.

> when entering context view mode, the most general assumption possible is the default

when switching to the context view, the longest substring/subphrase that exists as a full thought in at least one other context is the default

> to toggle between context views, first enter context view mode then (if the desired context is not already selected by default) tap the thought until the correct context view is underlined. each tap cycles through the possibilities in a loop. for the example, tapping would flip between "Things I Like Todo" and "Todo". tapping is only available once in a context view mode. outside of context view mode, tapping enters edit mode as expected.

Yes.

> should it matter where a user taps?

Hard to say until we can user test it. I would say yes, require the user to tap on the actual substring/subphrase. Spacial convergence/locality was one of the benefits this approach had over the "pagination" circles to the right which decouples the interaction point from the substring/subphrase.
