### ISSUE TITLE
Empty thought with formatting tags breaks caret

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1503]
## Steps to Reproduce

1. Paste `<b></b>` into a new thought.
2. Hit enter
3. Hit backspace

## Current Behavior

The caret disappears.

## Expected Behavior

The caret should be set on the previous thought after backspace.

**Comment by karunkop** [comment]
Does pasting empty formatting tag make any sense? When I paste `<b></b>` and then hit enter, '2' as a subscript appears on empty thought? Is this expected?

**Comment by raineorshine** [comment]
> Does pasting empty formatting tag make any sense?
Not really, but it is a user action so we have to be able to handle it.

One way of potentially solving this would be to strip empty tags from pasted text. Then the caret issue might not occur at all.

> When I paste `<b></b>` and then hit enter, '2' as a subscript appears on empty thought? Is this expected?

This also will go away if we strip empty tags. Otherwise I would consider this a bug.

**Comment by karunkop** [comment]
Yes i was also thinking of the same solution. Just wanted to confirm. Thanks!

**Comment by raineorshine** [comment]
I realize now that it's actually possible for users to manually type in `<b></b>` rather than just pasting it.

**Comment by raineorshine** [comment]
Fixed in #1515
