### ISSUE TITLE
importJSON error

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1520]
## Steps to Reproduce

```
a
b
c (<sup>d</sup>)
```

Paste the above thoughts.

## Current Behavior

```
Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'trim')
L138 importJSON.ts
```

## Expected Behavior

```
- a
- b
- c (d)
```

**Comment by karunkop** [comment]
`d` inside () should be a superscript of c right? I tested by removing brackets around `<sup>d</sup>` and pasting it `d` becomes children of `c`. This is not expected too ,right? or am I missing something here?
