### ISSUE TITLE
=note value not loaded on first load

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1533]
## Steps to Reproduce

```
- a
  - b
    - c
      - =note
        - Hello
```

Set the cursor on `a` and refresh the page. 

## Current Behavior

The note under `c` says "Enter a note", indicating that `=note` is pending. 

## Expected Behavior

Metaprogramming attributes should always be loaded with their descendants, and not left pending. 

The note placeholder should not be rendered while still pending.

**Comment by raineorshine** [comment]
All thought updates eventually go through the `updateThoughts` reducer, which adds the updates to `state.pushQueue`.

https://github.com/cybersemics/em/blob/dev/src/reducers/updateThoughts.ts

`pushQueue` then throttles saves to Firebase and IndexedDB.

https://github.com/cybersemics/em/blob/dev/src/redux-middleware/pushQueue.ts

When thoughts are loaded from IndexedDB, they are loaded through the `pullQueue`, which only loads visible thoughts and their children.

https://github.com/cybersemics/em/blob/dev/src/redux-middleware/pullQueue.ts

It is either not loading the `=note` child, or it is loading but not re-rendering. But I can pretty much confirm it's the latter, because when I put the cursor on a, the =note child re-renders correctly, even without any new thoughts expanded or loaded. 

It could be in the Subthought component's mapStateToProps: 
https://github.com/cybersemics/em/blob/023a90b2333debfd4f0b1e9bec0fe3d101951891/src/components/Subthoughts.tsx#L310

Or it could be in the Note component: 

https://github.com/cybersemics/em/blob/023a90b2333debfd4f0b1e9bec0fe3d101951891/src/components/Note.tsx#L49-L53

Be careful not to over-render. You want to re-render in exactly the case that's missing, but not in additional cases, which would affect performance.

**Comment by karunkop** [comment]
> All thought updates eventually go through the [updateThoughts](https://github.com/cybersemics/em/blob/dev/src/reducers/updateThoughts.ts) reducer, which adds the updates to `state.pushQueue`.
> 
> [pushQueue](https://github.com/cybersemics/em/blob/dev/src/redux-middleware/pushQueue.ts) then throttles saves to Firebase and IndexedDB.
> 
> When thoughts are loaded from IndexedDB, they are loaded through the [pullQueue](https://github.com/cybersemics/em/blob/dev/src/redux-middleware/pullQueue.ts), which only loads visible thoughts and their children.
> 
> It is either not loading the `=note` child, or it is loading but not re-rendering. But I can pretty much confirm it's the latter, because when I put the cursor on `a`, the `=note` child re-renders correctly, even without any new thoughts expanded or loaded.
> 
> It could be in the `Subthought` component's mapStateToProps:
> 
> https://github.com/cybersemics/em/blob/023a90b2333debfd4f0b1e9bec0fe3d101951891/src/components/Subthoughts.tsx#L310
> 
> Or it could be in the `Note` component:
> 
> https://github.com/cybersemics/em/blob/023a90b2333debfd4f0b1e9bec0fe3d101951891/src/components/Note.tsx#L49-L53
> 
> Be careful not to over-render. You want to re-render in exactly the case that's missing, but not in additional cases, which would affect performance.

`__allChildren` key in `mapStateToProps` is never actually used. There is this comment in `SubThoughts.tsx` -> `mapStateToProps` (` Re-render if children change and when children Thought entry in thoughtIndex is available.`). With this initially I thought that this was used somewhere to re-render the component but that's not the case here. I am also starting to think that this particular issue has nothing to do with re rendering but initially when components are rendered the `attribute` selector used in `Note.tsx` is unable to locate the value for `=note`. Most likely the issue lies with `getAllChildrenAsThoughts` function in `attribute.ts` selector. Meanwhile I am still investigating over these methods and see if I can trace down the problem.
@raineorshine

**Comment by raineorshine** [comment]
> `__allChildren` key in `mapStateToProps` is never actually used. There is this comment in `SubThoughts.tsx` -> `mapStateToProps` (` Re-render if children change and when children Thought entry in thoughtIndex is available.`). With this initially I thought that this was used somewhere to re-render the component but that's not the case here. 

Even though it is not used in the component, it is used to control renders. `mapStateToProps` is called whenever the state changes, and re-renders the component whenever members of its return value change. This is standard Redux functionality. 

The children are indirectly used by the component, since it looks them up itself with selectors. It would probably be a better design to use a memoized selector instead of relying on thr `mapStateToProps` effect. 

> I am also starting to think that this particular issue has nothing to do with re rendering but initially when components are rendered the `attribute` selector used in `Note.tsx` is unable to locate the value for `=note`. 

It's expected that the note's value is not yet loaded on first render, when its children are pending. In this case, it [doesn't render the note](https://github.com/cybersemics/em/blob/023a90b2333debfd4f0b1e9bec0fe3d101951891/src/components/Note.tsx#L49-L53). However, once the note's children are loaded, it should re-render with the note visible. 

I realize there are a lot of functions to trace to get to the bottom of this! It'll get easier once you are more familiar with the architecture and render pipeline.

**Comment by karunkop** [comment]
> It's expected that the note's value is not yet loaded on first render, when its children are pending. In this case, it [doesn't render the note

So if this is the case then when `hasNote` selector variable is `true`, `attribute` should return actual value of note instead of null, right? If it is then, the problem lies in the implementation of `attribute` selector. @raineorshine

**Comment by raineorshine** [comment]
When `hasNote` is true, `attribute` will return the note value. 

`attribute` is used extensively throughout the codebase. It would definitely break the unit tests if there was a problem with the implementation of `attribute`. 

If you haven't already, confirm that the `Note` component is not being re-rendered properly when the note's value loads. That will narrow your search.

**Comment by raineorshine** [comment]
Okay, that's progress.
