### ISSUE TITLE
Error deleting second empty thought

### ISSUE THREAD

**Issue by karunkop** [cybersemics/em#1543]
## Steps to reproduce

- Hit enter with an empty thought
- Hit backspace

## Current Behavior

![image](https://user-images.githubusercontent.com/40414929/160882663-6abcbb9c-29e3-4bef-bd8e-7076eaad3151.png)

## Expected Behavior

- No error should be thrown

**Comment by raineorshine** [comment]
It's a safety mechanism to prevent bugs. `expandThoughts` should never be passed a `Path` with an invalid id.

**Comment by karunkop** [comment]
> It's a safety mechanism to prevent bugs. `expandThoughts` should never be passed a `Path` with an invalid id.

So do you expect  it to run when an empty  thought  is deleted?

**Comment by raineorshine** [comment]
Yes. It will run if the correct id is passed.

**Comment by raineorshine** [comment]
If it helps, think of an error as an indication of an underlying/upstream bug. On rare occasions the error message itself is invalid, but you should generally assume that the error is correct, and it is pointing you towards invalid data upstream. In this case, an explicit throw was added to ensure that we never allow an invalid id to go unnoticed. It is better to fail early and hard than late and silent.

**Comment by karunkop** [comment]
> If it helps, think of an error as an indication of an underlying/upstream bug. On rare occasions the error message itself is invalid, but you should generally assume that the error is correct, and it is pointing you towards invalid data upstream. In this case, an explicit throw was added to ensure that we never allow an invalid id to go unnoticed. It is better to fail early and hard than late and silent.

Okay  got you!

**Comment by raineorshine** [comment]
> * No error should be thrown

I can see how this statement misleadingly suggests that the error is the problem! Really it means that that the underlying bug should be fixed *which is confirmed when no error is thrown*.
