### ISSUE TITLE
importJSON: Error importing nested list

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1547]
## Steps to Reproduce

```
<div>
	A
	<ul>
		<li>B</li>
	</ul>
	<ul>
		<li>C</li>
	</ul>
</div>
```

## Current Behavior

```
Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'trim')
importJSON: L123
```

## Expected Behavior

- a
  - b
  - c

**Comment by karunkop** [comment]
> ```
> <div>
> 	A
> 	<ul>
> 		<li>B</li>
> 	</ul>
> 	<ul>
> 		<li>C</li>
> 	</ul>
> </div>
> ```

How are we identifying/expecting that B and C must be children of A? Are we expecting this on the basis of indentation that is provided before li tags?

**Comment by raineorshine** [comment]
Whitespace is insignificant in HTML, so we don't want to base it on that.

It is the fact that `B` and `C` are inside a `<ul>`. Or it's the fact that `A` is not in a `<li>` but `B` and `C` are. Either criterion is okay with me.

Make sure the solution is general enough, i.e. `A` could be in a `<b>` tag for example and that shouldn't affect the parent-child structure.

**Comment by raineorshine** [comment]
I would start by guarding against an undefined value, since it's better to paste it in the wrong format than to fail hard in this case. At least then the user can get the data in and reformat as needed.

Then we can figure out the best way to get the desired structure.

**Comment by raineorshine** [comment]
@karunkop Oops! I closed too soon. Can you add a unit test? Thanks!
