### ISSUE TITLE
isUnbuffered: Context not found for thought

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1553]
Is this a bug, or is the warning incorrect under some conditions?

## Steps to Reproduce

```
- a
  - b
```

1. Create the above thoughts
2. Set the cursor on `b`
3. Refresh the page.

## Current Behavior

```
Warning: isUnbuffered: Context not found for thought ONR0XAr0NElUurjcdDn4X
```

## Expected Behavior

No warning.

**Comment by karunkop** [comment]
Does this still happen? I can't replicate it.

**Comment by raineorshine** [comment]
I can no longer reproduce! Thanks!
