### ISSUE TITLE
Only make font weight 600 and up bold

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1566]
## Steps to Reproduce

```
<ul>
  <li><i><b>The New Criterion</b></i><span style="font-weight: 400;"> is a </span>New York<span style="font-weight: 400;">–based monthly </span>literary magazine<span style="font-weight: 400;"> and journal of artistic and </span>cultural criticism<span style="font-weight: 400;">, 
edited by </span>Roger Kimball<span style="font-weight: 400;"> (editor and publisher) and </span>James Panero<span style="font-weight: 400;"> (executive editor). 
It has sections for criticism of poetry, theater, art, music, the media, and books. It was founded in 1982 by </span>Hilton Kramer<span style="font-weight: 400;">, former art critic for </span><i>The New York Times</i><span style="font-weight: 400;">, and Samuel Lipman, a pianist and music critic.</span>  </li>
</ul>
```

## Current Behavior

`font-weight: 400` is preserved on import. 

## Expected Behavior

`font-weight: 400` and below should be stripped on import. 

`font-weight: 500` and above should be converted to `<b>` or `font-weight: 700`.

**Comment by karunkop** [comment]
What do you mean by `font-weight: 400 is preserved on import.`?
![image](https://user-images.githubusercontent.com/40414929/169000671-b4c251b8-3ea9-4b15-8460-d5b53e5f6046.png)
Is the text `-based monthly` on font-weight 400?

**Comment by raineorshine** [comment]
Currently, `font-weight: 400` is not stripped on important. It should be removed completely on import. 

All font-weight styles provided in the HTML should be converted to either `<b>` or removed completely.
