### ISSUE TITLE
Thoughts, Contexts, and Bindings -- A Data Model 💃

### ISSUE THREAD

**Issue by rabbit** [cybersemics/em#16]
# Thoughts, Contexts, and Bindings

This is a summary of our meeting discussion around the main data model which is similar to a graph.

Thought is a textual item
Context is an unordered set of Thoughts
Binding is an unordered set of Contexts

All links are bidirectionally between a Binding and a Thought. (e.g., Thoughts and Contexts do not link to other Thoughts or Contexts. a Context belongs to a Binding which links to Thoughts, a Thought links to a Binding which links to children)

In most cases a Binding will only contain a single Context but cases where multiple Contexts should be treated the same, they are housed under the same Binding

the UX process of creating a Binding of multiple contexts is TBD but should generally follow this flow:
1. add a new thought (e.g., "Beta")
2. navigate to the context view for that thought
3. select a context to bind
4. "Beta" now shows the children from the selected context binding

decoupling the binding would generally follow the reverse flow:
1. select a thought to unbind
2. thought shows context view for that thought (which includes the context it was previously bound to)
3. switch out of context view

**Comment by raineorshine** [comment]
Yes, exactly!

> 1. add a new thought (e.g., "Beta")

Yes

> 2. navigate to the context view for that thought

Yes, technically the context view for the active context, which terminates with that thought.

> 3. select a context to bind
> 4. "Beta" now shows the children from the selected context binding

5. The children of "Beta" (the active context) are kept perfectly in sync with the bound context; adding, editing, or removing a child will effectively perform the same operation on the bound context (in O(1)).
