### ISSUE TITLE
Changes are not persisted after undo

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1631]
## Steps to Reproduce

1. Create thought `a`. 
2. Create thought `b` after `a`. 
3. Undo.
4. Create thought `c` after `a`. 
5. Refresh the page. 

## Current Behavior

`c` was not persisted. 

No changes are persisted after the undo. 

``` 
- a
``` 

## Expected Behavior

All changes should be persisted. 

```
- a
- c
```

**Comment by raineorshine** [comment]
Possibly caused by undo.

**Comment by raineorshine** [comment]
Revert 40f1a7c after this is fixed.

**Comment by RED-ROSE515** [comment]
This is why this unexpected behavior happens.
Because, current lexemeId will be removed from dockeys in **deleteThought** function(thoughtspace.ts).
And return error in checking if the dockeys contain the cxid.
Because of that `paused ` flag set as true and changes are not persisted after undo.

**Comment by raineorshine** [comment]
Thanks for investigating!

Can you clarify what is triggering `deleteThought`? Which step?

I understand that when the `taskQueue` is paused from the error, it never resumes, and that's why new edits are not persisted. I'm not sure exactly which `taskQueue` you are referring to though.

One thing that would be helpful would be for you to link to some of the relevant line numbers in the code. That will make it easier for me to connect your explanation to the specific places in the code that you are referring to.

Next, what are the incorrect assumptions that the code makes? Normally, dockeys are cached so that we can always access a thought from its parents. What is different about undo/redo?

What do you suggest as a solution?

Thank you!

**Comment by RED-ROSE515** [comment]
Currently, if you don't create a new thought before exec `undo`, it works well.
But according to these steps, it doesn't work properly.
 1. Create thought a.
 2. Create thought b after a.
 3. Undo.

Because, when exec undo, it executes deleteThought function and it will delete the thought id from dockeys.
 [https://github.com/cybersemics/em/blob/9e7f8a1e438468f3b1b8f330ffa8701f39074635/src/data-providers/yjs/thoughtspace.ts#L942](url)

**Comment by raineorshine** [comment]
Okay, thanks. One question that brings for me is, why does it break on undo, but not if you manually activate `deleteThought` on `b`? The effect should basically be the same.

That is, on the surface there doesn't appear to be anything wrong with undo triggering `deleteThought`, since the end goal is to delete `b`. There must be something more to it.

**Comment by raineorshine** [comment]
Okay, good to know. Is the prematurely deleted Lexeme `b` or the empty string?

(FYI I think you have your markdown url syntax wrong. All of them link to https://github.com/cybersemics/em/issues/url)

**Comment by RED-ROSE515** [comment]
> Okay, good to know. Is the prematurely deleted Lexeme `b` or the empty string?

I can't understand your question exactly.
Currently updateLexeme check the deleted Lexeme `b`'s id in docKeys.

**Comment by raineorshine** [comment]
I understand. So it's Lexeme `b` that is deleted, which causes `updateLexeme` to fail.

**Comment by RED-ROSE515** [comment]
Yes, that's correct!
