### ISSUE TITLE
Context View: Render parents of leaves instead of leaves themselves

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1635]
The context view is designed to present lexeme instances across the hierarchy that contain different notes in different contexts.

- Fallen Angels
  - Wong Kar Wai
    - 4/5

(e.g.. `/Film/Watched/Movies`)

Leaf instances appear differently because the thought has no children.

- Cinematography
  - Place something in between two characters in dialog 
    - Wong Kar Wai

(e.g. `Cinematography/Place something.../Wong Kar Wai`)

When combined in a single context view, these different structures don't currently look good together. The first structure is generally more desirable. Shorter category names appear in the list of contexts, and longer, prose-like notes are nested below. 

When the thought is a leaf, hide the parent from the breadcrumbs (the last segment) and render the parent instead of the leaf itself in the context view.

e.g. The note on cinematography should appear as:

`Film • Filmmaking`

- Cinematography
  - Place something in between two characters in dialog

![image](https://user-images.githubusercontent.com/750276/180348440-cabb35d6-b88d-4f6a-8619-8ff98a242009.jpeg)

**Comment by kradchenko** [comment]
Hi @raineorshine, I have a problem with starting the project on `dev` branch. I got an issue while running the command `npm start` and also while running `npm run start:expo`. Is there any stable version of the project?

**Comment by raineorshine** [comment]
We also need to think about how this feature would work when duplicate breadcrumbs are consolidated, e.g. `... • FIlm • :: • Watched • Movies`.

**Comment by raineorshine** [comment]
I'm not sure this feature makes sense. 

First, I think `Wong Kar Wai` should appear the same in the context view regardless of whether it has a subthought like `4/5`. 

Second, all of the instances in `... • Film • :: • Watched • Movies` fit the leaf criterion and should render the parents according to the rule. However, this effectively just groups `In the Mood for Love`, `Fallen Angels`, and `Days of Being Wild` under the `... • Film • :: • Watched • Movies` breadcrumbs. That is better achieved by the duplicate breadcrumb consolidation feature.

The only other rule that might capture the desired appearance of the `Cinematography` example is to render the *furthest ancestor with a single child*.
