### ISSUE TITLE
Ava test runner

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#166]
Set up Ava testing with enzyme

  - https://semaphoreci.com/community/tutorials/getting-started-with-create-react-app-and-ava

  - https://shift.infinite.red/testing-the-bejeezus-out-of-react-native-apps-with-ava-330f51f8f6c3

**Comment by mekanix** [comment]
As Ava will support ES syntax [starting with version 3](https://github.com/avajs/ava/issues/2293#event-2902827708), for now Jest is recommended test runner. For future reference, Enzyme official documentation about [Ava setup](https://github.com/airbnb/enzyme/blob/master/docs/guides/tape-ava.md#ava) is outdated. Also, adding babel presets didn't work as Ava transpiles only test files and uses CommonJS for the app.
