### ISSUE TITLE
[iOS PWA] Selection goes invisible when switching apps

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1680]
iOS PWA only

## Steps to Reproduce

1. Create a thought
2. Select some text in the thought
3. Activate "Look Up" from the context menu. 
4. Close the context popup. 

## Current Behavior

After closing the context popup, no selection is visible, but there is still an active focusNode. This prevents gestures from working.

## Expected Behavior

Either the selection should be visible, or it should be deselected. 

We should not deselect the text when the user quickly switches away and back, as they should be able to resume where they left off. Ideally we find a way to detect when there is an invisible selection (maybe the thoughts are re-rendered but the selection doesn't update?).

**Comment by ethan-james** [comment]
@raineorshine I can reproduce this on https://em-proto.web.app, but I actually can't on my dev server. Is it possible that this was fixed as part of another issue?

**Comment by raineorshine** [comment]
I'm having some trouble installing the PWA at all in order to try to reproduce. I am able to do Add to Home Screen, but then when I click on the app it opens in Safari instead of simulating a native app. Are you able to install `main` as a PWA?

**Comment by raineorshine** [comment]
It looks like VitePWA was missing the Web Manifest. Added in 02db2f0730. You should be able to install a proper PWA to the home screen now.

Also confirmed that this is no longer an issue. I think your changes in #2607 inadvertently fixed it.

**Comment by ethan-james** [comment]
I see that I can install the PWA from https://em-proto.web.app on an Android phone & an iPad, but my dev server running on http://192.168.0.101:3000 installs browser shortcuts to the home screen on both devices. My guess would be that it doesn't like something about the local address (insecure, weird port, etc.) but my second guess would be that the newer manifest isn't working for me. Is there an up-to-date deployment of `main` that I could check?

**Comment by raineorshine** [comment]
https://em-proto.web.app/ is a very old version, pre vitest. 

The latest tag from `main` is deployed to https://em-proto--staging2-cxls71a0.web.app/.

**Comment by ethan-james** [comment]
Great, yes, I see that one functioning as a PWA on iOS & Android.
