### ISSUE TITLE
Conflicting hotkeys for ToggleContextView

### ISSUE THREAD

**Issue by FritzJay** [cybersemics/em#169]
The toggleContextView shortcut (Shift + Ctrl + C) conflicts with built-in browser shortcuts in brave, chrome and Firefox.

I don’t know if this is specific to windows as I don’t have access to a Linux box at the moment, but I would suggest changing the hotkeys regardless. The conflict prevents users from opening the context view.

**Comment by raineorshine** [comment]
Thank you! It is indeed specific to Windows. I'll change it.

**Comment by raineorshine** [comment]
Did some research and wrote this answer on StackOverflow to try to get an initial rough idea of available keyboard shortcuts cross-platform: https://stackoverflow.com/a/59010351/480608
