### ISSUE TITLE
[iOS] No overscroll bounce

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1694]
## Steps to Reproduce

Try to scroll past the top or bottom of the screen.

## Current Behavior

The scroll stops at the top or bottom.

## Expected Behavior

The scroll should use bounce overscroll.

The issue is reproducible in Mobile Safari, but not when in PWA mode. Therefore, if you add em to your home screen from Safari, you can see the desired behavior.

**Comment by ankitkarna99** [comment]
This was due to me disabling the `overscroll-behavior` property in the root of the application. I have removed this and used a background color to fix the problem of white background during overscroll.

**Comment by raineorshine** [comment]
This is not working for me yet. There is no overscroll when I test on a real device.

**Comment by raineorshine** [comment]
Update:

- Requires a [plugin](https://github.com/ionic-team/capacitor/issues/2334#issuecomment-995610856) to override [bounces = false](https://github.com/ionic-team/capacitor/blob/6c2726dc0817c9e57c8b7909e4a69a9b376c425d/ios/Capacitor/Capacitor/CAPBridgeViewController.swift#L287).
- iOS 16.0 had a regression that enabled bounce. It was [fixed in iOS 16.2](https://developer.apple.com/forums/thread/711601?page=2).

References:

- https://github.com/ionic-team/capacitor/issues/1169
- https://github.com/ionic-team/capacitor/issues/2334
- https://github.com/ionic-team/capacitor/issues/5907

**Comment by raineorshine** [comment]
Fixed in 0216c4f
