### ISSUE TITLE
[iOS] Toolbar is not fixed position when keyboard is up

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1695]
## Steps to Reproduce

1. Create some thoughts
2. Enter edit mode to open the keyboard
3. Scroll down

## Current Behavior

The toolbar scrolls out out of view.

## Expected Behavior

The toolbar should always be fixed to the top of the screen.

## Notes

In Mobile Safari, position:fixed does not work when the keyboard is up, so we have a hacky solution that uses position:absolute and updates the y coordinate on scroll to simulate position:fixed. (Oddly, caniuse says that position:fixed [works fine](https://caniuse.com/css-fixed) in modern Mobile Safari)

See: https://github.com/cybersemics/em/blob/c973e935c44d42d1dc7b16d48c493f8286797032/src/components/Editable/positionFixed.ts

We only enable/disable the simulated position:fixed when the condition `isTouch && isSafari()` is true: https://github.com/cybersemics/em/blob/c973e935c44d42d1dc7b16d48c493f8286797032/src/components/Editable.tsx#L452-L454. 

Is `isSafari` returning false in the iOS capacitor app? If so, you may need to add an additional `isIOS` condition that we can check for. (It may also be possible to change `isSafari` itself to return true in the iOS capacitor app, but then you would need to confirm that it does not cause a regression in any of the other places that uses `isSafari`.)

That's the potentially quick solution. But it is far from ideal since it creates a nasty jittering effect on scroll that is impossible to get rid of when using position:absolute. Does capacitor provide a way to have position:fixed panels while the keyboard is up? This would be a much better solution for the user experience if possible. This could be addressed in a separate issue if the quick solution works.

**Comment by ankitkarna99** [comment]
I checked and the `isSafari` seems to return true inside of the capacitor app, and the `fixedPosition.start()` and `fixedPosition.stop()` were also being executed. So, I have used a different approach to fix the issue by applying the capacitor keyboard plugin to handle resizing of the webview.

**Comment by raineorshine** [comment]
It works in the Simulator but not on a real device for me. Did it work for you on a real device? I ran "yarn cap:sync:prod`, connected my device, then launched the app from XCode.

**Comment by ankitkarna99** [comment]
I tested on real device too. But not with the prod sync command.

**Comment by raineorshine** [comment]
Never mind, it seems to working now! I needed to remove the app from my phone and then launch and re-trust.

**Comment by raineorshine** [comment]
Fixed in ce8316b80f
