### ISSUE TITLE
[iOS] Command palette persists after app becomes passive

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1696]
Only relevant to iPhone X and up. 

## Steps to Reproduce

1. Grab the app switcher at the bottom of the screen and drag about 10 pixels to the right. If you do it just right it will activate the gesture hint. 
2. Without fully switching apps, let em fall back into place and become active again. 

## Current Behavior

https://user-images.githubusercontent.com/750276/213871400-7b848021-65da-4b22-88dc-3dfde89ad52d.MOV

## Expected Behavior

The gesture should be cancelled and the gesture hint dismissed when the app becomes passive. 

If that is not possible, but the passive state can still be detected, the gesture hint should be dismissed when the app becomes activated again.

**Comment by ankitkarna99** [comment]
I checked out the stackoverflow link mentioned in this file:

https://github.com/cybersemics/em/blob/dev/src/%40types/LifecycleState.ts

It mentions:

- Activate app switcher and back: no change

I tried it on my phone through PWA, but I couldn't listen to any lifecycle events in case of switcher and back.

**Comment by raineorshine** [comment]
That would have been the simplest way. Other ideas:

- Capacitor [pause or resume events](https://capacitorjs.com/docs/apis/app#addlistenerpause-)
- [window.hasFocus()](https://developer.mozilla.org/en-US/docs/Web/API/Document/hasFocus)
- window blur event
- touch events
- timer discrepancies
