### ISSUE TITLE
[mobile] Next gesture is prevented after drag in place

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1711]
## Steps to Reproduce

```
- Apple
- Banana
- Cherry
```

1. Close the keyboard.
2. Tap and hold Apple to start the drag.
3. Drag across the other thoughts and back up to Apple.
4. Release the drag, leaving Apple in place.
5. Enter one or more gestures

## Current Behavior

The first gesture after the drag is prevented and nothing happens. Subsequent gestures work as expected.

## Expected Behavior

Gestures should work after drag ends.

**Comment by Zubair286** [comment]
Unable to reproduce the issue on both android and ios, is this issue fixed?

**Comment by raineorshine** [comment]
Can confirm, seems to be fixed!
