### ISSUE TITLE
Tutorial: Add link to scroll up when tutorial instructions are hidden

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#172]
On small screens, new users can get lost when they have scrolled down to where the tutorial instructions are out of view.

To make this easier, when the tutorial buttons are hidden from view due to scrolling, display a link centered at the top of the screen with the text "Scroll up for tutorial". Clicking/tapping the link should smoothly scroll to the top. 

The link should only be displayed when the user is scrolled past the tutorial buttons. When the tutorial buttons are visible, the link should not appear.

Here's a good example of the desired behavior (including fade and translate animations):

https://github.com/user-attachments/assets/29feef79-b64a-44ed-b34a-4b5e4a25b571

And another, with just fade:

https://github.com/user-attachments/assets/835ccd5d-3618-4923-9cfc-22bc40df10bb

**Comment by trevinhofmann** [comment]
When you refer to small screens, what do you recommend for testing? I have test Android and iOS devices that I could use. Or, are you simply referring to a smaller window with a desktop browser?

**Comment by raineorshine** [comment]
I've mainly noticed the problem on older phones.

The Chrome DevTools device toolbar should allow you to simulate the issue. It doesn't show the virtual keyboard, but you could try doing a custom screen size with a shorter height (300-400px).

<img width="492" src="https://github.com/user-attachments/assets/5aa92e29-5cd5-4d31-a4e5-75203b26e7ff">

**Comment by raineorshine** [comment]
Added an example of how Discord solves it (see video above).
