### ISSUE TITLE
Disable =drop/top when drop destination is expanded

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1721]
## Steps to Reproduce

```
- a
  - =drop
    - top
  - b
  - c
  - d
```

Drag `b` after `d`. 

## Current Behavior

Nothing happens. 

## Expected Behavior

`b` should be moved after `d`. 

`=drop/top` should not apply when the parent _of the drop target_ is expanded.

**Comment by Zubair286** [comment]
If show hidden thought is enabled, then dragging b after d would place it above the =drop/top, otherwise nothing happens. In the scenario when show hidden thoughts is enabled, should the =drop/top not apply when parent is expanded?

**Comment by raineorshine** [comment]
`=drop/top` should not apply when the parent is expanded, regardless of whether `showHiddenThoughts` is enabled.

**Comment by Zubair286** [comment]
I am wondering if `=drop/top` should not be applied to an expanded parents children, then the only point I can think of it working would be at _ROOT_ level, because a thought has to be expanded to drag/drop its children. Please let me know if I am wrong.

**Comment by raineorshine** [comment]
The drop target's parent is the one that is expanded, not the drop source. 

Maybe this example is clearer:

``` 
- x
- a
  - =drop
    - top
  - b
  - c
``` 

1. Set the cursor on `a`. 
2. Drag `x` after `c`.

**Comment by Zubair286** [comment]
I see, in the above example dragging x after c puts the x above b because of the `=drop/top`, but if the parent is expanded this prevents x from being dropped after c., so =drop/top should be disabled when parent is expanded, is that right?

**Comment by raineorshine** [comment]
Yes, that’s correct. `=drop/top` should only be active when dropping into a collapsed thought.

**Comment by Zubair286** [comment]
Okay, I was just a little confused with the first example, I get it now. Thanks

**Comment by Zubair286** [comment]
Please close this issue, as it is fixed.
