### ISSUE TITLE
Fix toggleShowContexts

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#175]

**Comment by molecula451** [comment]
![context](https://user-images.githubusercontent.com/41552663/69756985-2bda8680-1132-11ea-9ab6-27a9cce74fa3.png)

Ctrl + Shift + S it might be working on Mac but not on other platforms or browser.

I am able to toggle context while adding toughts within  toughts.

![contextx](https://user-images.githubusercontent.com/41552663/69757082-66dcba00-1132-11ea-8f97-110883861fbc.png)
