### ISSUE TITLE
Table: Col1 width is different on load

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1795]
## Steps to Reproduce

```
- A
  - =view
    - Table
  - ✓
    - Boston, Massachusetts
  - ✗
    - Cincinnati, Ohio
- B
```

1. Paste the above thoughts.
2. Set the cursor to `A`.
3. Refresh the page.
4. Set the cursor to null.
5. Pause one second.
6. Set the cursor back to `A`.

## Current Behavior

The width of col1 is different between steps 3 (after refresh) and 5 (after moving the cursor away and back).

https://github.com/cybersemics/em/assets/750276/d147993e-067d-4adb-9886-e29e7d282c8c

## Expected Behavior

The width of col1 should be consistent even if the cursor has moved away and back.

**Comment by Zubair286** [comment]
Which position is the correct one this case, the one before the shift and or the initial one?

**Comment by raineorshine** [comment]
It's hard to tell, but I assume that the initial one with the wider column is the one that is wrong, because once the table is collapsed and given the chance to re-render, it corrects itself and is stable with the narrower width. 

The absolute width is not very relevant here, as that can be adjusted trivially.

My guess is that the initial width is being set and cached before the second column loads from the db.

**Comment by Zubair286** [comment]
Right, from what I have seen the the width assign to col1 is taken from `.editable` div, but initially the two values do not match, its only after the shift that they are same. So there is something that is altering the width of col1 initially.

**Comment by Zubair286** [comment]
In `setSize` function, I added an extra check on setter setSize of `width === sizeOld[key]?.width` and now if we reload with the cursor on A the width does not change but when the cursor is on any col1 thought and re reload it starts with the wrong width.

**Comment by raineorshine** [comment]
The width caching is done in `useSizeTracking`:

https://github.com/cybersemics/em/blob/88a8b205ab5321f9ec5cbafab6d6e8eac299b4a1/src/components/LayoutTree.tsx#L104

The widths are not cached in local storage.

When you identify the specific cause of the problem, please describe it here. Why is the calculated width different in the two different cases?

**Comment by Zubair286** [comment]
when putting cursor on a thought and refreshing the page, is there any state that will persist across refresh that can have an affect on the width of thoughts?
