### ISSUE TITLE
Drag and drop: Indicate when sorted drop target is out of view

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1828]
In this screenshot, `Colorado` is being dragged and hovered over the sorted `States` context, but the drop target is not visible. 

Render an upward pointing blue triangle at the top of screen to communicate to the user that the thought will be inserted above the top of the screeen. 

Render a downward pointing blue triangle at the bottom of the screen when the insertion point is below the bottom of the screen (not pictured). 

Animate the arrows with a gentle up-and-down bobbing motion. 

![image](https://github.com/cybersemics/em/assets/750276/69454f36-d58e-426e-bc1c-c4fd3560d594)

``` 

- US
  - States
    - =pin
      - true
    - =sort
      - Alphabetical
        - Asc
    - Alabama
    - Alaska
    - Arizona
    - Arkansas
    - California
    - Connecticut
    - Delaware
    - Florida
    - Georgia
    - Hawaii
    - Idaho
    - Illinois
    - Indiana
    - Iowa
    - Kansas
    - Kentucky
    - Louisiana
    - Maine
    - Maryland
    - Massachusetts
    - Michigan
    - Minnesota
    - Mississippi
    - Missouri
    - Montana
    - Nebraska
    - Nevada
    - New Hampshire
    - New Jersey
    - New Mexico
    - New York
    - North Carolina
    - North Dakota
    - Ohio
    - Oklahoma
    - Oregon
    - Pennsylvania
    - Rhode Island
    - South Carolina
    - South Dakota
    - Tennessee
    - Texas
    - Utah
    - Vermont
    - Virginia
    - Washington
    - West Virginia
    - Wisconsin
    - Wyoming
  - Colorado
```

**Comment by hereistopdev** [comment]
This is Sheldon from Upwork. I will start work right now to fix this issue

**Comment by hereistopdev** [comment]
https://www.upwork.com/freelancers/~0194d712c9f174416f

**Comment by Zubair286** [comment]
When trying to render a downward arrow for a context such as above `States`, there is an issue with `DropHover` placement. All the thoughts are not rendered until we scroll down so for a thought that will be placed at the very bottom will not have any `DropHover` rendered until we scroll down. Is there any way to detect the position of the  `DropHover` on large context when its rendering at the bottom?

**Comment by raineorshine** [comment]
This isn't so much about the position of the `DropHover` component. As you pointed out, it is not actually rendered at all in this case. Instead, we need to find where in the list it _would_ be rendered if it were within view. 

The logic for positioning within a sorted list is somewhat buried in one of the hooks, but it is ultimately just a function of the Redux state (i.e. it is a selector), so it should be easily extractable. However, determining whether that position is in view or not is trickier, as that depends on which VirtualThoughts are shimmed (i.e. virtualized). I'm not sure off the top of my head the best way to expose this to an indicator arrow like this issue requires. I would suggest identifying and formulating this before doing an implementation so that we confirm a satisfying approach, i.e. not introducing a bunch of additional state to make this happen.

**Comment by Zubair286** [comment]
I tried rendering the arrow by comparing the top value of DropHover with window.innerHeight, it works for the upward arrow but for the downward as you mention it does not render at all.

**Comment by raineorshine** [comment]
Yeah. VirtualThought is responsible for which thoughts are in the viewport, so I would look there.

**Comment by Zubair286** [comment]
Right, and I believe getSortedRank is the selector that returns the sorted rank.

**Comment by Zubair286** [comment]
One thing that comes to my mind is to get all the children of the context, assuming it only returns the children that are currently rendered, and calculate the rank using `getSortedRank`. By comparing the rank with the rank of the last thought of context we might be able to identify the need to render the arrow.

**Comment by raineorshine** [comment]
Five thoughts are rendered below the bottom of the viewport to avoid rendering gaps as thoughts are virtualized/unvirtualized during scrolling:

https://github.com/cybersemics/em/blob/e321a6537f53eb9e3bfa3108195ebc94cd622295/src/components/LayoutTree.tsx#L433-L434

The render loop in LayoutTree short circuits as soon as `viewportBottom` is exceeded:

https://github.com/cybersemics/em/blob/e321a6537f53eb9e3bfa3108195ebc94cd622295/src/components/LayoutTree.tsx#L661-L666

LayoutTree seems like the right place for this logic since it is the component that is aware of the overall layout and rendering of all the visible thoughts. The challenge is that sorted list hover logic is buried in the DropHover components which is only rendered in visible thoughts.

**Comment by Zubair286** [comment]
In the `LayoutTree` component, the arrow positioning was not remaining sticky to the top and bottom, I first tried doing it in `LayoutTree` but it didn't work probably because of the containers height. It seems to be placed fine in `Content` component but it does not have the awareness of `LayoutTree` component.

**Comment by Zubair286** [comment]
Yes, the sorted context hover logic is what I need instead of using the `DropHover` position which is not reliable.

**Comment by raineorshine** [comment]
> In the `LayoutTree` component, the arrow positioning was not remaining sticky to the top and bottom, I first tried doing it in `LayoutTree` but it didn't work probably because of the containers height. It seems to be placed fine in `Content` component but it does not have the awareness of `LayoutTree` component.

It shouldn't matter which component it goes in since it is rendered `position: fixed` (or `position: absolute` + scrollTop to make it work on iPhone [when the keyboard is up](https://github.com/cybersemics/em/blob/main/src/components/Tutorial/TutorialScrollUpButton.tsx)).

**Comment by Zubair286** [comment]
I have examined the `DropHover` and indeed it only works for the rendered thoughts, and the moveThought action actually moves the thought by setting the new rank using `getSortedRank`, but in this I do not understand how for example a thought that will go to the bottom of the entire list is placed, is there a condition that checks if it is going below the rendered items?

**Comment by raineorshine** [comment]
If `getSortedRank` is less than the rank of the first thought in the viewport, then the drop location is above the top of the viewport. 

If `getSortedRank` is more than the rank of the last thought in the viewport, then the drop location is below the bottom of the viewport.

**Comment by Zubair286** [comment]
Right, so that brings us to finding out the first and last thought in the viewport.
