### ISSUE TITLE
Table View

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#183]
Allow the user to enable Table View, which renders each level of thoughts as columns in a table.

e.g. The following thought structure:

- Paul Atreides (cursor)
  - First Name
    - Paul
  - Last Name
    - Atreides
  - Age
    - 15

would be rendered in table view as (ignore header styling):

- Paul Atreides

  | First Name | Paul     |
  |-------|----------|
  | Last Name  | Atreides |
  | Age   | 15       |

## Requirements

- Add a button to the toolbar to activate table view.
- Render thoughts within the cursor context as the first column in a table, and render their subthoughts as the second column
- Render multiple subthoughts under the same thought as bullets within the second column
- Appropriate positioning and spacing; no borders
- Smooth tweening between normal view and table view
- Dark and Light Themes
- Thoughts should still be editable in the table
- Creating a new subthought from any cursor position should work as expected, placing the new thought and cursor in the correct column for editing
- Smoothly transition x-position during navigation like existing animation
- Columns should be resizable through dragging the border
- Render more than two columns as described below
- Test and fix bugs on desktop and mobile

## Descendants

- Allow descendants within the table view to be rendered hierarchically and expanded as normal by putting the cursor on a subthought (second column)

The following thought structure:

- Paul Atreides (cursor)
  - First Name
    - Paul
  - Last Name
    - Atreides
  - Age
    - 15
      - x
        - y

would be rendered in table view as:

- Paul Atreides
  <img width="172" alt="Screen Shot 2019-12-31 at 11 17 41 AM" src="https://user-images.githubusercontent.com/750276/71630296-65822f80-2bbf-11ea-813b-cb3efd29df8e.png">

**Comment by victoray** [comment]
Can you assign this to me?

**Comment by raineorshine** [comment]
@victoray I ended up completing this later in January, but thank you for offering! There are still some bugs to be worked out if you are interested.

**Comment by victoray** [comment]
Great! I will be happy to help.

**Comment by victoray** [comment]
Great! I will be happy to help.

**Comment by raineorshine** [comment]
@victoray I created some issues for the Table View. Let me know if you can tackle any of them! https://github.com/cybersemics/em/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+table+in%3Atitle
