### ISSUE TITLE
SVG 'Home' Logo rendering after context view activated

### ISSUE THREAD

**Issue by molecula451** [cybersemics/em#187]
There is an issue we have on our app as soon as we pop up our context view the **.svg Home** it's being rendered below the contexted tought. This should be fixed. And this is happening in our actual proto live app,

![rendering](https://user-images.githubusercontent.com/41552663/69824422-13c24000-11e2-11ea-8947-3ef4b852c254.png)

**Comment by raineorshine** [comment]
This is actually by design. When a thought appears in the home context, then the home icon should appear in the context view. This indicates to the user that *home* is one of the contexts of the thought.

**Comment by molecula451** [comment]
@raineorshine  Thank you. Now I am able to end up finishing the changes for the styles documents, and element renderings on different browsers get ready!!
