### ISSUE TITLE
Bullets shift position at other font sizes

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1915]
## Steps to Reproduce

```
- A
  - B
    - C
      - D
```

1. Set the font size to 13. 
2. Move the cursor between `B` and `C`. 

## Current Behavior

Bullets shift position during the translateX animation. 

https://github.com/cybersemics/em/assets/750276/f23a9bee-a9fb-4c70-810b-ca4d50fa4157

## Expected Behavior

Bullets should not shift position.

## Notes

Occurs at any font size other than the default 18. Appears to be caused by some combination of translateX, the `Scale` component, and the bullet SVGs. 

Bullets were converted to SVG in order to solve cross-platform positioning issues (#1175). A robust proposal should be presented that takes account of the lessons learned in #1402 and #1505 and suggests a fix that does not cause a regression.

**Comment by trevinhofmann** [comment]
This appears to affect Safari (both Mac and iOS), but not Firefox or Chrome. Still looking into it.
