### ISSUE TITLE
Toolbar: Bold icon shows inactive state for bold empty thought

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1948]
## Steps to Reproduce

1. Create a new, empty thought. 
2. Activate bold in the toolbar.

## Current Behavior

The toolbar icon does not change.

(Yet we know that bold is activated because the next text you type is bold.)

## Expected Behavior

The toolbar icon should appear activated.

## Notes

The toolbar icon highlight is determined by the shortcut's `isActive`:

https://github.com/cybersemics/em/blob/5ffafd3a22beb062ff2b55b87115fe898aea7870/src/shortcuts/bold.ts#L20

**Comment by finkef** [comment]
I can reproduce for other formatting toolbar icons as well, italic, underline, strikethrough. Will fix in on go.
