### ISSUE TITLE
Cliff drop targets obscured by user's finger

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1952]
## Steps to Reproduce

```
- a
  - b
    - c
      - d
        - e
          - f
```

Drag `f` onto any of the drop targets over the cliff. 

## Current Behavior

The drag zone is too far to the left, so the user's finger obscures the drop hovers. 

https://github.com/cybersemics/em/assets/750276/942192a8-e29b-49d5-9823-b1074892395d

Note: The video does not show where the user's finger is in contact with the screen, but is included here to clarify the steps to reproduce.

## Expected Behavior

The drag zones should be shifted right so that the left edge of the drop hover is clearly visible.

**Comment by Zubair286** [comment]
Wouldn't shifting right undo the way the drop-end is flush to the thoughts right now?

**Comment by raineorshine** [comment]
The position of the (invisible) drop target should change without changing the position of the (visible) DropHover. How to achieve that of course will depend on the component hierarchy, DOM hierarchy, and CSS, and may require changes in multiple places.
