### ISSUE TITLE
Add New Subthought to toolbar

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1968]
- [x] Add `'newSubthought'` to the [TOOLBAR_DEFAULT_SHORTCUTS](https://github.com/cybersemics/em/blob/c21cdc17813b6fe06f2e112cfc56693a34ed8b4a/src/constants.ts#L166) so it shows up in the toolbar after `newThought`.
- [x] Replace the `newSubthought` shortcut [icon](https://github.com/cybersemics/em/blob/c21cdc17813b6fe06f2e112cfc56693a34ed8b4a/src/shortcuts/newThought.tsx#L10) with a new icon that is like https://thenounproject.com/icon/plus-5662424/ but with a rightward-facing arrow to the left. I recommend modifying the SVG with a vector editor like https://boxy-svg.com/.
- [x] Make sure the icon is sized, positioned, and styled like the other toolbar icons.

**Comment by trevinhofmann** [comment]
>but with a rightward-facing arrow to the left

Could you please clarify what this means? Here are some suggestions/interpretations:

![image](https://github.com/user-attachments/assets/b6811221-da2d-475c-9bb9-1aea4fa11910)

I prefer (3), but curious to know what you intended.

**Comment by raineorshine** [comment]
I was thinking (1), but I can understand why (3) might be better. 

However, now that I see it I wonder if it will generate any confusion given that the gesture is →↓→. 

![image](https://github.com/user-attachments/assets/c23df788-3659-4318-bf86-3801679d5581)

![image](https://github.com/user-attachments/assets/ce1e4961-620d-4954-b715-a21b95c47171)

Using the actual gesture would be most accurate, but that doesn't leave much horizontal space for the (+). What do you think?

**Comment by trevinhofmann** [comment]
Seeing this, I'm now partial to (3) while changing the arrow to reflect the gesture. I believe it could be scaled appropriately to appear nicely in the UI. If we try that and you aren't satisfied with the result, I'd be happy to change it to another design.

**Comment by raineorshine** [comment]
Great, let's do it :)
