### ISSUE TITLE
Add Conditional to Dark/Light Mode Advance Settings

### ISSUE THREAD

**Issue by molecula451** [cybersemics/em#198]
We have found a tiny issue on our Advance settings when turn On/Out Light mode. This happens in any platform.

**Actual Behaviour:**

![lightmode](https://user-images.githubusercontent.com/41552663/69898586-c523bb80-1331-11ea-82ec-08f249f42497.gif)

If a I click on choose 'Light mode' It will actually turn to dark mode which is Ok, but when in dark the text is still showing 'Light mode'

**Expected Behaviour:**

After click 'Light mode' and turn the app background in full light mode (white color). Change text to 'Dark mode'

**Comment by raineorshine** [comment]
Thanks!

**Comment by molecula451** [comment]
> Thanks!

Cheers.
