### ISSUE TITLE
Set cursor on first non-meta thought on paste

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#2050]
## Steps to Reproduce

1. Create a thought `a`
2. With the cursor on `a`, paste the following text:

```
- =note
  - test
- b
```

## Current Behavior

The cursor is moved to `=note` on paste.

## Expected Behavior

The cursor should be set on `b`.

The cursor should be set on the first sibling that is not a metaprogramming attribute when `state.showHiddenThoughts` is false.

## Testing

Add importText tests for showHiddenThoughts true and false.

## Notes

The logic for where the cursor is set on import is here: https://github.com/cybersemics/em/blob/5ffafd3a22beb062ff2b55b87115fe898aea7870/src/actions/importText.ts#L192

**Comment by finkef** [comment]
Note: Since we're importing a multiline block of text, `importFiles` is called instead of `importText`. The behavior of `importText` is correct for the above payload.
