### ISSUE TITLE
Thoughtspace should not scroll when Sidebar is open

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#2061]
## Steps to Reproduce

Open the Sidebar and try to scroll. 

## Current Behavior

The thoughtspace behind the Sidebar scrolls (intermittent).

https://github.com/cybersemics/em/assets/750276/26ad7b89-116a-4088-ab8d-1365dff5c328

## Expected Behavior

The thoughtspace should not scroll when the Sidebar is open. Only the Sidebar content should scroll. 

Set `overscroll-behavior: contain`?

**Comment by trevinhofmann** [comment]
This issue appears to have already been correctly fixed by 6a8068ac59e5c842be0f95ff1a3996f70b4ed0e5.

Demo (scrolling outside of the sidebar scrolls the thoughtspace, scrolling inside does not):

https://github.com/user-attachments/assets/b9a8ffe0-fe3b-4f10-b0fc-0dce95cea0a8
