### ISSUE TITLE
Footer: Breadcrumbs bottom margin is sometimes incorrect

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#2063]
## Steps to Reproduce

1. Create a thought `hello`.
2. Set the cursor to null.
3. Quickly scroll to the bottom. 
4. Scroll up and repeat. 

## Current Behavior

The safe-area below the breadcrumbs is sometimes preserved when scrolled all the way to the bottom. 

![image](https://github.com/cybersemics/em/assets/750276/54daeffd-2afd-4a0e-80df-065b42f6de1c)

## Expected Behavior

When scrolled to the top, the breadcrumbs should be rendered above the bottom safe area.

When scrolled to the bottom of the document, the bottom margin is not needed because the safe area is not obscured. If the safe area is partially obscured, the bottom margin should adjust dynamically so that there is no extra space in between the breadcrumbs and the safe area at any point during scrolling, i.e. the breadcrumbs should have a smooth transition from being stuck to the bottom of the screen above the safe area to being above the footer.

![image](https://github.com/cybersemics/em/assets/750276/bdf3dcbb-fbba-4e5e-9f45-c2e36666dd4b)

**Comment by zahidhussain998** [comment]
i fixed this #2071

**Comment by zahidhussain998** [comment]
please check my PR which i raised

**Comment by trevinhofmann** [comment]
@raineorshine -- Can you please confirm if this is still an issue, and possibly any other information on how to reproduce it? I haven't been able to get the bottom margin to appear. Here's a video of the simulated mobile device in Chrome, and I have the same results on a physical Android device:

https://github.com/user-attachments/assets/02a3062f-964e-4135-9d4f-1578890e8bd3

**Comment by raineorshine** [comment]
It looks like it now does not respect the bottom safe area at all. Tested on physical iPhone and Simulator.

I think we will need to restore the safe area margin and then see if the irregular spacing is still an issue.

I also missed a step: The cursor has to be set to null, otherwise the breadcrumb are not rendered with position: fixed.

**Comment by trevinhofmann** [comment]
Ah! I didn't realize until now that this was for the Capacitor app.

> It looks like it now does not preserve the bottom safe area at all.

This is most likely a result of: https://github.com/cybersemics/em/pull/2593/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R10

https://developer.mozilla.org/en-US/docs/Web/CSS/env

To use `env(safe-area-inset-bottom)`, we need to include `<meta name="viewport" content="viewport-fit=cover" />`.

I'll start looking for a solution to #2514 which preserves `viewport-fit=cover`.

After changing back to `viewport-fit=cover`, the safe area below the breadcrumbs seems to _always_ be preserved for me when scrolling to the bottom, so I will look into that now as well.

**Comment by trevinhofmann** [comment]
Moving the `env(safe-area-inset-bottom` to the `bottom` of this element seems to fix the issue: https://github.com/cybersemics/em/blob/d980704e25a617aacf20536a5b8719638dc046b9/src/components/NavBar.tsx#L60-L70

However, there is a comment warning about mobile Safari `z-index` issues when doing that. I haven't noticed any issues during testing. @raineorshine -- Do you have any more context about what the `z-index` issues are/were?

**Comment by raineorshine** [comment]
> Ah! I didn't realize until now that this was for the Capacitor app.

I believe it was also reproducible in Mobile Safari.

> > It looks like it now does not preserve the bottom safe area at all.
> 
> This is most likely a result of: [#2593 (files)](https://github.com/cybersemics/em/pull/2593/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R10)

Darn. And that PR was to fix the top safe area.

> However, there is a comment warning about mobile Safari `z-index` issues when doing that. I haven't noticed any issues during testing. @raineorshine -- Do you have any more context about what the `z-index` issues are/were?

I traced it back to 477fefc452257089ad57fd135865738643dfbb53 which provides a little more context:

> Unable to get it working perfectly on mobile Safari without bottom nav overlapping footer. Live with extraneous padding when scrolled to bottom in order to keep bottom nav above inset when scrolled anywhere else.

I can't recall the specific z-issues. I'm glad I left a comment, but definitely should have been more specific!
