### ISSUE TITLE
Toolbar button stuck down

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#2088]
## Steps to Reproduce

1. Create thought `a`
2. Click and drag a toolbar button down.

## Current Behavior

The toolbar button stays depressed.

https://github.com/cybersemics/em/assets/750276/68c9d536-92e9-4e56-8362-af4ebad40510

## Expected Behavior

The toolbar button should be reset after the cursor moves off the toolbar, and the command should be cancelled.

**Comment by michaelperros** [comment]
Please see #2196
