### ISSUE TITLE
Disable YJS connecting status in tests

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#2111]
When there are no thoughts, the UI is kept blank or says "Connecting..." until the YJS websockets connects or time out after 5 sec. This slows down the tests considerably. 

Disable this loading screen when in test mode and go straight to the thoughts.

Remove the [sleep](https://github.com/cybersemics/em/blob/5ffafd3a22beb062ff2b55b87115fe898aea7870/src/e2e/puppeteer/helpers/setup.ts#L68-L70) in test setup and make sure the tests pass.

**Comment by mstrofbass** [comment]
@raineorshine this request appears to require changing the logic below to hide the LoadingEllipsis component if we're in the e2e tests:

https://github.com/cybersemics/em/blob/fe3994ad5c55afbb938cb1ef44bea318e114f5e1/src/components/EmptyThoughtspace.tsx#L38-L41

Is there a mechanism to determine whether we're in the e2e tests within that component?

**Comment by raineorshine** [comment]
You can detect if the app is running in puppeteer with `navigator.webdriver`.

I'm not sure if just hiding the LoadingEllipsis will be enough, or if you'll have to mess with the https://github.com/cybersemics/em/blob/main/src/stores/offlineStatusStore.ts which has some timeouts built in.

**Comment by mstrofbass** [comment]
Okay, are you suggesting that a possible way to do this is to set the offline timeout to zero? Then this would filter down and effectively hide `LoadingEllipsis`?

I like that but I am not sufficiently familiar with the downstream impacts of setting the offline timeout to zero to fully understand the impact thereof.

That being said, I have tested both options and they seem to work fine. For both solutions I have gotten a difficult to reproduce intermittent failure with one or more of the snapshot and am continuing to debug to figure out what the cause is.

I'll note that the `sleep` in the test setup has 500ms specifically to wait for the hamburger animation to complete. I have gone ahead and removed it while debugging to see if I encounter any issues and it does not seem to cause any additional problems on my machine but I'm not sure if that would be the case in CI/CD. 

Can you clarify whether I should leave the 500ms `sleep` portion for the hamburger animation or should I go ahead and remove the entire call to `sleep`?

**Comment by mstrofbass** [comment]
FYI, it looks like the failure is in the `url.ts` test and this is the snapshot diff and error:

`Error: Expected image to match or be a close match to snapshot but was 0.13916666666666666% different from snapshot (668 differing pixels).`

![single-line-1-diff](https://github.com/user-attachments/assets/08316f8e-fb8e-4672-bfe1-4f054177a744)

**Comment by raineorshine** [comment]
> Okay, are you suggesting that a possible way to do this is to set the offline timeout to zero? Then this would filter down and effectively hide `LoadingEllipsis`?
> 
> I like that but I am not sufficiently familiar with the downstream impacts of setting the offline timeout to zero to fully understand the impact thereof.

Theoretically that would work (just like changing the animation durations to 0) and has the least impact on the code, because the start state, end state, and wait logic can stay the same.

> I'll note that the `sleep` in the test setup has 500ms specifically to wait for the hamburger animation to complete. I have gone ahead and removed it while debugging to see if I encounter any issues and it does not seem to cause any additional problems on my machine but I'm not sure if that would be the case in CI/CD.
> 
> Can you clarify whether I should leave the 500ms `sleep` portion for the hamburger animation or should I go ahead and remove the entire call to `sleep`?

Disabling the hamburger animation would fall under the scope of #2110. The goal is to remove as many sleeps as possible from the tests, switch to polling, or, as a last resort, reduce the sleep duration as much as possible.

> FYI, it looks like the failure is in the `url.ts` test and this is the snapshot diff and error:
> 
> `Error: Expected image to match or be a close match to snapshot but was 0.13916666666666666% different from snapshot (668 differing pixels).`

I reproduced the url test on my machine and took a video to get a closer look. It actually looks like there is a bug that causes a slight layout shift of the last thought. You can see it at about 4s 500ms:

https://github.com/user-attachments/assets/9cde62f0-4802-4f43-80a3-6c521229a2b5

It may be intermittent because there is a race condition between the snapshot and the layout shift.

It's a bit annoying that it interferes with our work on the tests in this milestone. Let me know if you'd like to try to fix the issue (billed as additional work at your hourly rate), or just skip the test and create an issue to come back to it.

**Comment by mstrofbass** [comment]
> Disabling the hamburger animation would fall under the scope of https://github.com/cybersemics/em/issues/2110. The goal is to remove as many sleeps as possible from the tests, switch to polling, or, as a last resort, reduce the sleep duration as much as possible.

I'll remove the websocket sleep portion under this issue and remove the hamburger animation sleep portion under #2110 

> It's a bit annoying that it interferes with our work on the tests in this milestone. Let me know if you'd like to try to fix the issue (billed as additional work at your hourly rate), or just skip the test and create an issue to come back to it.

Let's create a new issue and come back to it at the end.

**Comment by raineorshine** [comment]
> I'll remove the websocket sleep portion under this issue and remove the hamburger animation sleep portion under #2110

Sounds good!

> Let's create a new issue and come back to it at the end.

#2452
