### ISSUE TITLE
=children/=pin no longer works

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#2117]
## Steps to Reproduce

Paste the following thoughts:

```
- a
  - =children
    - =pin
  - b
    - b1
  - c
    - c2
```

## Current Behavior

`b` and `c` are not expanded.

## Expected Behavior

`b` and `c` should be expanded because `=children/=pin` exists on the parent.

You can see it working when `Pin Subthoughts` is toggled on and off on `a`.

## Testing

Add an RTL test.

**Comment by finkef** [comment]
After some digging found that for pin to work, the above should be:

```
- a
  - =children
    - =pin
      - true
  - b
    - b1
  - c
    - c2
```

Pasting this works as expected. Couldn't find any other issues importing/exporting these.
