### ISSUE TITLE
Tutorial: Fade out + in transition

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#2282]
## Steps to Reproduce

1. Start the tutorial. 
2. Click the Next Button

## Current Behavior

Tutorial content swipes in. 

https://github.com/user-attachments/assets/277fd985-3707-4bdf-a185-fe5a4d4dd97b

## Expected Behavior

Tutorial step content should fade out and new content should fade in. 

If the height of the content changes, the height should animate to adjust the available space.

**Comment by findusman** [comment]
this issue is resolved
