### ISSUE TITLE
Missed applying the job by a few hours, here was my proposal for the sync engine implementation.

### ISSUE THREAD

**Issue by bxff** [cybersemics/em#2291]
Sorry if this is the wrong place to post, but I was just unable to apply for the CRDT engineering job posting on Upwork. I already wrote a proposal that I believe is worth looking into.

Assumptions:
* It's not clear that whether the children of a tree node would be sequentially ordered like a list or unordered, I assumed that the children are to be ordered as a list. This will have implications on the approach we would take. 

### Yjs Implementation

Yjs has two major feature which are paramount, partial sync and list implementation. Yjs supports [lazy loading](https://docs.yjs.dev/api/subdocuments) documents into memory from the server or other peers, and has a correct (Fugue maximally non-interleaving) list CRDT algorithm. I would need to write a custom tree CRDT on top of the Yjs list algorithm which uses the server as the source of truth, this approach would be quite similar to how [Figma](https://www.figma.com/blog/how-figmas-multiplayer-technology-works/#syncing-trees-of-objects) has implemented its tree conflict resolution. Lastly for indexing based on props, we would need to create an adjacent data store to the Yjs document, storing only data necessary for sync (i.g. ID, parent ID, and children IDs) on the Yjs document and on our primary data store we would store the whole data set, we would partially replicate this with the Yjs document using its lazy loading feature.

There are many reasons for choosing this approach over other approaches, as outlined below:
* Assuming we need the list sync algorithm, this limits our options to CRDTs, State-machines and OTs. Most of the options listed in the requirements don't support a list sync algorithm.
* The delete logic is non-standard: Deletes always over rule inserts/moves, not the other way around, this means it's necessary to create a custom tree sync algorithm which can account for this. 
* Partial sync currently doesn't has the best support in any sync library today, and is very hard to custom implement into a solution thats doesn't have it. Luckily Yjs supports partial sync. 
* Tree sync is a hard problem, while solved, it's easy to screw up. It is paramount to have a good understanding of the tree sync problem, it's easy to underestimate. I am aware to my best extend about the implementation of the tree sync algorithms used by Syncthing, Dropbox, Notion, Figma and Loro.
* Indexing is hard as most implementation store the document internally, and not separately, as far as I am aware only Diamond Types supports the separation of document and crdt metadata.
* Efficiency: O(1) deletes (sub-tree marked delete), O(logn) getByProp and getById (as they are indexed), O(n) replicate and import. Yjs is known to support over 1 million operations and the tree sync algorithm should be quite efficient, but it's not possible to know if Yjs would be able to support this load without actually testing it.
* Auth and Full text search should be possible to implement with our dual data store approach and custom sync.

Beyond this there are a few other approaches we can use, but I don't really recommend them:
* A fully custom built solution: I would need to write a custom list and tree sync algorithm, probably based on fractional indexing and using the same tree sync approach described above. While this approach doesn't require having separate data stores for the dataset and crdt dataset and avoids the complexity of extending the partial sync for this, but requires implementing and testing the custom algorithm and would not be Fugue maximally non-interleaving if we choose fractional indexing. This approach would also take much longer to implement.
* Using the same Yjs approach, but using Liveblocks backend. This would save quite a lot of time in implementing the backend, but this would require using webhooks to replicate the dataset into the centralised server database for indexing, which would be somewhat more complex to implement, less streamlined, and this approach would need to rely on Liveblocks, and therefore added costs long term.

Some approach I considered but which don't work:
* Loro: Doesn't support branches for OT-like sync or partial sync / lazy loading, which means unless partial sync is not required then only we could use this approach. Loro is significantly faster than Yjs and has in-built tree sync algorithm, albeit using the standard delete strategy described above.

Just in case it's relevant I am an CRDT engineer working on my own CRDT implementation which would compete with the likes of Yjs and Loro and I was trying to apply for this job, and I just missed it by a few hours.

**Comment by raineorshine** [comment]
Hey! Thanks for taking the time, and sorry you missed the cutoff. I got an abundance of talented responses, probably because it's an interesting technical problem.

Actually, the app currently uses YJS. I found it very attractive, for many of the reasons you mentioned. Unfortunately, in practice it didn't work out well for this use case. Subdocument support in YJS is *basically nonexistent*. I can't emphasize that enough. There is a tiny bit of scaffolding in place that allow subdocuments to be loaded automatically, but provider support is nonexistent. There is no way of ensuring the entire graph has been synced, and you can't fit all the subdoc keys into a single doc. The hard problem of when/how to pull subdocs in and out of memory and track replication progress has to be custom built.

I ended up doing exactly that, building a managed graph of YJS documents with an append-only log to track the global replication status. Unfortunately, both the computation and memory performance on the syncing server severely broke down at about 100k nodes. Between the performance issues and nothing to guarantee tree validity (because you don't have transactions across subdocs), I decided to no longer pursue the solution.

That's not to say that it can't be done, and you definitely are deeper in the CRDT internals than me! Maybe I just need the right developer who can work around the issues I ran into. 

Thanks again for your thoughts.

**Comment by raineorshine** [comment]
> * It's not clear that whether the children of a tree node would be sequentially ordered like a list or unordered, I assumed that the children are to be ordered as a list. This will have implications on the approach we would take.

Nodes have a `rank` field used for ordering which is independent of the array order. Equal ranks should be avoided, but it's not the end of the world: they get rendered next to each other in a nondeterministic order, and the order can be finalized by the client if a duplicate ran is detected.

**Comment by bxff** [comment]
> Nodes have a rank field used for ordering which is independent of the array order. Equal ranks should be avoided, but it's not the end of the world: they get rendered next to each other in a nondeterministic order, and the order can be finalized by the client if a duplicate ran is detected.

This would have highly simplified the problem, given this all that would be needed is a custom made tree sync algorithm and some sort of partial sync and indexing mechanism that can be custom build.

> Subdocument support in YJS is basically nonexistent. I can't emphasize that enough. There is a tiny bit of scaffolding in place that allow subdocuments to be loaded automatically, but provider support is nonexistent.

Unfortunately Yjs has very poor subdocument support in providers, this is in part the reason why backend solutions like Liveblocks and Hocuspocus were created to provide better subdoc, auth, and other support which is quite painful to manually implement. Not to say it's impossible, but really hard. 

> Hey! Thanks for taking the time, and sorry you missed the cutoff. I got an abundance of talented responses, probably because it's an interesting technical problem.

If you need help in the future regrading the sync / crdt / conflict resolution, I would be more than happy to help you: dexdevlon[at]gmail[dot]com

**Comment by raineorshine** [comment]
Thanks! I will keep you in mind for future work.
