### ISSUE TITLE
Tutorial: Selector unknown returned a different result

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#2311]
## Steps to Reproduce

1. Start the tutorial.
2. Click the penultimate step.
3. Hit Enter to create a new thought.
4. Click "Learn More".

https://github.com/user-attachments/assets/fe0089d6-bbb1-4ffa-9a4a-505a882263db

## Current Behavior

<img width="755" src="https://github.com/user-attachments/assets/a55e77d1-9756-4209-8e9f-aa9277baac0a">

## Expected Behavior

No warning.

**Comment by findusman** [comment]
[issue-2311.webm](https://github.com/user-attachments/assets/b77aba4a-d5e1-4d4f-a3b0-eb7ad40890e3)

This issue seems to be fixed already. I performed deep testing and inspected the corresponding redux actions. It seems code is clean and no warning is coming around

**Comment by raineorshine** [comment]
I've updated the OP with more exact steps to reproduce.

I am also able to reproduce it by following each step of the tutorial, but skipping to the penultimate step is faster.
