### ISSUE TITLE
Able to (easily) set the font-size to tiny values, including 0

### ISSUE THREAD

**Issue by trevinhofmann** [cybersemics/em#2340]
## Steps to Reproduce

1. Click into the Settings page from the footer
2. Select the font size input so the cursor is at the end of the `18` input
3. Press backspace/delete once, changing the font size to `1`
4. Press backspace/delete again, changing the font size to `0`.

## Current Behavior

While actively updating the font size value in the input, the actual font size of the entire app is changing. This makes for a very jarring experience, as the appearance of the input drastically changes while trying to update it.

Further, it is possible to set the font size all the way to `0` by simply trying to delete the existing value before typing in the desired font size. This makes the input and all other text completely disappear.

https://github.com/user-attachments/assets/faefb941-c836-423a-b430-61b1172fdba4

## Expected Behavior

~I believe it would make more sense for the font size of the app to only update after the user completes editing of the input (i.e. `onBlur` instead of `onChange`).~

Additionally, it would likely make sense to have a minimum font size to avoid the user setting it to a value so small that they can't properly navigate the application to change it.

**Comment by raineorshine** [comment]
Yes, looks like [MIN_FONT_SIZE](https://github.com/cybersemics/em/blob/6be0e3d8fc095af31568988506c62e74fb7a4595/src/constants.ts#L139) is not being enforced in the settings. 

I'm okay with instant update as long as MIN_FONT_SIZE is enforced.
