### ISSUE TITLE
eslint: Enforce default export

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#2346]
- Add `import/prefer-default-export` to eslint rules
- Remove `import/prefer-default-export` ts override
- Convert single named exports to default exports (one commit per conversion)
- Inline functions if they are only used in one file

```ts
    // Enforce default export
    // https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/prefer-default-export.md
    'import/prefer-default-export': [
      2,
      {
        // any: Any exporting file must contain a default export.
        // single: When there is only a single export from a module, prefer using default export over named export.
        target: 'any',
      },
    ],
```

Examples:

9922909732 Remove device/router.
37af57d9b6 emojiRegex: Convert to default export.
63c7bee4e1 useSelectors: Move into Footer module.
14718399d8 Remove old migrations.
d3f83f15f6 metaSettings and hashKeys: Disable import/prefer-default-export.
0d7f2c5fb7 isUndoEnabled: Convert to default export.
8e66ec3675 serviceWorkerRegistration: Disable import/prefer-default-export.
b8db740c52 shortcuts: Disable import/prefer-default-export.
b53efdd8e8 shortcuts/index: Disable import/prefer-default-export.
299ffceaa0 Rename gestureEnum and convert to default export.
0dcfd95f68 constants: Disable import/prefer-default-export.
ba0a947ecf findAllThoughtsByText: Convert to default export.
6a59651eb5 Remove createMockStore.
154a143e3a createTestStore: Convert to default export.
8c3210b3e1 Remove unused mock-debounce-throttle.
39db7e8097 findSubthoughts: Convert to default export.
0a74b99908 getClosestByLabel: Convert to default export.
4b2b2ab397 Remove unused queryAllThoughtsByText.
d8890cd959 queryThoughtByText: Convert to default export.
649ce8259a validateRoam test: No need to export testData.
790300ec35 compareThought: disable import/prefer-default-export
ed5c5bc9f6 isMarkdown: Convert to default export.
ede06f22b5 markdownToText: Convert to default export.
2a2791c7f1 Refactor memoizeResolvers.
62399263b9 text-block-parser: disable import/prefer-default-export
6f652cefa4 react-dnd: disable import/prefer-default-export

**Comment by mstrofbass** [comment]
@raineorshine you say:

> Inline functions if they are only used in one file

Is it your expectation that I just go through your list of examples or do I need to do an audit of the project and identify all locations? If the latter, what is your recommended way to identify those functions efficiently?

**Comment by raineorshine** [comment]
Those are examples that have already been completed, you don't have to do anything with them. Apparently the commit history was rewritten, but I updated it so you can see the actual commits now.

When you turn on the `import/prefer-default-export` rule, the linter will show you exactly which files need to be changed. Then it's up to you the best way to resolve it. 

- If the module uses a single named export, that's a straightforward conversion to a default export. 
- If the module uses multiple named exports, it should probably be split into multiple files.
- Occasionally the lint rule should just be disabled, such as 6239926 and b53efdd. If you are unsure about a specific case feel free to ask.
