### ISSUE TITLE
Snapshot tests fail with missing PandaCSS styles after component changes

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#2371]
When I modify a component with the puppeteer tests running, and then hit (r) to re-run, the tests correctly pick up on the change. However, when I undo the code change and hit (r) again, I see slight differences in the snapshot, exactly where certain PandaCSS styles would apply. 

Probably the same as #2390, though it's not clear why only some font sizes fail. 

(Note that this problem existed before puppeteer was dockerized in #2365.)

## Steps to Reproduce

1. Start the dev server. 
1. `yarn test:puppeteer render -t load`
2. Add `return null` to Toolbar.tsx.
3. Hit (r) in the tests to re-run. They will fail as expected.
4. Remove `return null` from the component.
5. Hit (r) in the tests to re-run.

## Current Behavior

The snapshot tests for Font Size 18 and 22 fail. 

![font-size-18-default-initial-load-1-diff](https://github.com/user-attachments/assets/443cc6a0-e636-49f3-b2d7-744705fa1aac)

## Expected Behavior

All tests should pass.

Notice that if you quit the puppeteer tests and run `yarn test:puppeteer render -t load` from scratch *without changing any code* the tests will now pass.

**Comment by trevinhofmann** [comment]
I have not been able to reproduce this issue locally.

https://github.com/user-attachments/assets/85c98066-a2a3-4fac-a643-a6bb9e1d7b56

**Comment by raineorshine** [comment]
Fixed in #2420
