### ISSUE TITLE
[Capacitor] Position fixed components

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#2387]
Original issue for the toolbar: #1695

## Current Behavior

The [TutorialScrollUpButton](https://github.com/cybersemics/em/blob/c217ebb4b95435e24d7f6953b0953f84df1d6dcf/src/components/Tutorial/TutorialScrollUpButton.tsx) uses position absolute on mobile due to a Safari limitation. This causes the component position to be choppy during scroll.

## Expected Behavior

The ToolbarScrollUpButton should normally be position fixed, and should only switch to position absolute like [positionFixed](https://github.com/cybersemics/em/blob/c217ebb4b95435e24d7f6953b0953f84df1d6dcf/src/components/Editable/positionFixed.ts) when the following conditions are true:

1. isTouch
2. Safari
3. Not Capacitor iOS
4. Keyboard is up

The upcoming [sorted context out-of-view arrow](https://github.com/cybersemics/em/pull/2369/files#diff-d8362059d1ac04eef549d6201a2c9a1e86e1c4bcb7cf9fe2337a7f7709b51808R169) should follow this same behavior.

**Comment by msdewitt** [comment]
@raineorshine Could you add a further description on this bug or a video showing the issue?

**Comment by raineorshine** [comment]
Looks like this was fixed in ec3e432e71!
