### ISSUE TITLE
strip slows down expandThoughts

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#2398]
> I found that a significant part of scripting and HTML parsing is done at the start of the interactions due to the `expandThoughtsRecursive` function using the `strip` function to perform sanitization on the values. In my tests, this accounts for at least 15-20% of the interaction time, with 1000 thoughts processed. This could be fixed by moving the sanitization to another stage that's not after every interaction. It is to be noted that if window-like virtualization is implemented, the impact of optimizing this would be reduced as the number of thoughts processed per interaction would be greatly reduced. WDYT?
> 
> ![Brave Browser 2024-09-15 19 23 20](https://github.com/user-attachments/assets/95174b44-fa06-4f81-a84a-e5b0d0202bce)

It looks like `strip` was added to handle bold/italic/strikethrough. Thoughts that end in `:` should be pinned open, including `<b>:</b>`. See #1073. Solved in #1090 but note the unit tests appear to be false positives now.

We can remove `strip` and replace it with a much faster alternative that just strips closing tags.

**Comment by raineorshine** [comment]
Maybe this regex?

```
s.match(/:(<\/[^>]>)*$/g)
```

Matches `a`, `<b>a:</b>`, `<i><b>a:</b></i>`, etc.

**Comment by carloslfu** [comment]
Yes, that regex looks right. Thanks! I'll test it, measure and submit a PR.

**Comment by carloslfu** [comment]
Closing via #2419.

**Comment by carloslfu** [comment]
@raineorshine, I think this one is safe to close.
