### ISSUE TITLE
Correct description of table view subthoughts as rows

### ISSUE THREAD

**Issue by trevinhofmann** [cybersemics/em#2439]
I've been experimenting with tables, and it appears that only 2 columns are possible. The subthoughts of the current thought are each treated as a row in Column 1 rather than each being a column, and the subthoughts of those are rendered in Column 2.

Assuming this is the intended behavior, I believe the text description of the table view shortcut should be updated to reflect that subthoughts are separate rows in the table (rather than separate columns).

## Steps to Reproduce

Navigate to `Settings` -> Click on `Customize Toolbar` -> Scroll to `Table View` in the `Special Views` section.

## Current Behavior

![Screenshot 2024-10-01 at 6 46 21 AM](https://github.com/user-attachments/assets/1cd84f93-4b9e-4ee9-8cb5-eed3d269a006)

## Expected Behavior

![Screenshot 2024-10-01 at 6 49 58 AM](https://github.com/user-attachments/assets/9f113773-d8ad-46fb-b7e9-43ccbe7347d9)

**Comment by raineorshine** [comment]
Yes, good catch. 

FYI Multicolumn support is scheduled for #334.
