### ISSUE TITLE
Initial Tests

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#244]
Create the following tests:

- [x] 1. New Thought
  - When the user hits Enter, a new thought is created:
  - `getThought('')` should return a thought object in the root context.
  - `getThoughtsRanked([ROOT_TOKEN])` should contain only `''`
  - An empty thought should be rendered in the DOM
  - localForage should be updated with the new thought
- [x] 2. Edit Thought
  - When the user creates a new thought and types `'A'`, the empty thought should be modified:
  - `''` should not exist
  - `getThought('A')` should return a thought object in the root context.
  - `getThoughtsRanked([ROOT_TOKEN])` should contain only `'A'`
  - A thought with text "A" should be rendered in the DOM
  - localForage should be updated with the new thought
- [x] 3. New Subthought
  - When the user creates a new thought, types `'A'`, and hits Cmd + Enter a new subthought should be created:
  - `getThought('A')` should return a thought object in the root context.
  - `getThought('')` should return a thought object in the 'A' context.
  - `getThoughtsRanked([ROOT_TOKEN])` should contain only `'A'`
  - `getThoughtsRanked(['A'])` should contain only `''`
  - An empty subthought should be rendered under "A" in the DOM
  - localForage should be updated with the new thought
- [ ] 4. newThoughtAbove
  - Test `getThought`, `getThoughtsRanked`, DOM, and `localForage` as above.
- [x] 5. newThoughtTop
  - Test `getThought`, `getThoughtsRanked`, DOM, and `localForage` as above.
- [ ] 6. newUncle
  - Test `getThought`, `getThoughtsRanked`, DOM, and `localForage` as above.
- [ ] 7. setCursor
  - When the user clicks a thought, the cursor is moved to that thought.
- [ ] 8. expandThoughts
  - When the user clicks on a collapsed thought, the thought should be expanded to reveal its subthoughts.
- [x] 9. deleteThought

**Comment by mekanix** [comment]
Problems during testing:
 1. `import * as uuid` vs `import uuid` https://github.com/mekanix/em/commit/86b5d90e31c5afc7c7ea0ba0496b8814467c3b1e#diff-b056c1ad802eb5041886154caaf3a3d4R3
 2. window and document objects in testing are not complete, so `document.getSelection()` in https://github.com/mekanix/em/blob/feature/jest/src/components/ModalComponent.js#L61 doesn't work

For 1. what was observed that "uuid" is function in browser but object in testing. It took me way too much time to suspect that "import" is not working. There might be other errors like this, but I'm stuck on 2. For 2. there are 2 ways we can take: mock missing functions or store selection in store. If we decide to mock, these are the references:
  - https://www.reddit.com/r/reactjs/comments/ajwjym/things_you_cannot_unit_test_what_to_do/
  - https://stackoverflow.com/questions/43677034/enzyme-jest-window-getselection-does-not-work

**Comment by raineorshine** [comment]
@mekanix Thanks! Great work. 

2. What's the easiest way to simply ignore the browser selection in tests? Dummy mock? Some day we may want to test selection position, but at this point it is a low priority.

**Comment by mekanix** [comment]
It's case by case. Sometimes we can just return dummy value, sometimes we must return something more meaningful, depending on what the rest of the code does.

**Comment by raineorshine** [comment]
Okay, thanks. I don't have a strong opinion in this case, so take the simplest approach when possible and use your judgment.

**Comment by raineorshine** [comment]
Most tests implemented in #706.
