### ISSUE TITLE
Do not strip bold, italic, underline

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#247]
- Change the [`strip`](https://github.com/cybersemics/em/blob/dev/src/util/strip.js) function to take an optional `stripFormatting` argument that controls whether `<b>`, `<i>`, and `<u>` (and their closing tags) are removed. It should default to `true`. Modify the regex to achieve this functionality. 
- Do not remove formatting when rendering thoughts (no change needed)
- Remove formatting in the [`Breadcrumbs`](https://github.com/cybersemics/em/blob/dev/src/components/Breadcrumbs.js) component.

**Comment by sparklingW** [comment]
So, if stripFormatting = true, function will return a formatted string, but if false, return unformatted string?

**Comment by sparklingW** [comment]
Hello, I want to ask how stripFormatting will affect the functionality of the strip function? Because I can't understand it from the description.

**Comment by raineorshine** [comment]
Hi! 

- If `stripFormatting` is `true`, `strip` should behave as it currently does, stripping all HTML from the string.
- If `stripFormatting` is `false`, `strip` should not strip `<b>`, `<i>`, and `<u>`.
- `stripformatting` should default to `true`

Does that make sense?

**Comment by sparklingW** [comment]
Thank you, sorry for the misunderstanding.

**Comment by raineorshine** [comment]
No problem! Thanks for asking.

**Comment by sparklingW** [comment]
Hello, I want to ask what is wrong with the pull request? Did I forget to do something?
