### ISSUE TITLE
Intermittent test failure rendering dimmed sibling

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#2496]
## Steps to Reproduce

```
- a
  - m
- b
  - m
```

Set the cursor on `a`.

https://github.com/cybersemics/em/blob/e35751c2cfb68c144efd1c54ef9ddeecab42f6f3/src/e2e/puppeteer/__tests__/render-thoughts.ts#L119C8-L131

## Current Behavior

Intermittent test failure. `b` is 5 pixels off (the failure threshold is 4 pixels). I don't really want to increase the failure threshold, as we do want the snapshot tests to catch regressions at that scale.

https://github.com/cybersemics/em/actions/runs/11515138928/job/32055198992

![font-size-13-superscript-1-diff](https://github.com/user-attachments/assets/b8c1a4c9-d442-4aab-a317-e0df079f29eb)

## Expected Behavior

No test failure.

**Comment by raineorshine** [comment]
My best guess is that the snapshot is catching `b` before its opacity has animated into place. `b` dims when the cursor is on `a`. Normally this is done with a slow transition, but in the e2e tests the transition duration is set to 0 so it should instantly render the end state. Maybe the snapshot is in a race condition with the next rendered frame with the correct opacity?

https://github.com/cybersemics/em/blob/e35751c2cfb68c144efd1c54ef9ddeecab42f6f3/src/components/Subthought.tsx#L130-L132

**Comment by mstrofbass** [comment]
> b is 5 pixels off (the failure threshold is 4 pixels). I don't really want to increase the failure threshold, as we do want the snapshot tests to catch regressions at that scale.

I'm somewhat worried that browsers will still render elements in over multiple frames and so race conditions between the tests and the browser will exist regardless of the duration. We may want to consider looking into whether we can set up the tests to fail fast if the difference is over a certain threshold but retry a set number of times if the difference is under a certain threshold. Where that threshold would be set is obviously debatable but I would tend to base it on how scale results in a noticeable visual difference.

I would not recommend considering this quite yet, however, as I ran into some weird situations where it seemed like once an intermittent failure appeared, it _kept_ appearing. This may have just been an artifact of what I was doing at the time so I don't know if this is something that is actually a problem, I'm just noting it as a reason to not assume that some form of test retry will actually work.

**Comment by raineorshine** [comment]
> We may want to consider looking into whether we can set up the tests to fail fast if the difference is over a certain threshold but retry a set number of times if the difference is under a certain threshold. Where that threshold would be set is obviously debatable but I would tend to base it on how scale results in a noticeable visual difference.

Yes, that could work. Also vitest has a `{ retry: number }` option that is very easy to use, if we're willing to forgo the fast fail threshold.

> I would not recommend considering this quite yet, however, as I ran into some weird situations where it seemed like once an intermittent failure appeared, it _kept_ appearing. This may have just been an artifact of what I was doing at the time so I don't know if this is something that is actually a problem, I'm just noting it as a reason to not assume that some form of test retry will actually work.

Okay, keep me posted!

**Comment by raineorshine** [comment]
Another failure, so definitely something going on with this test: https://github.com/cybersemics/em/actions/runs/11534504432/attempts/1?pr=2369

It might be a good idea to use `puppeteer-screen-recorder` to confirm that the opacity transition is actually disabled.

It could possibly be a variation on #2452, but it looks to me more like an opacity animation.

**Comment by mstrofbass** [comment]
The image below is a side-by-side comparison of the difference. IMO this simply is not worth failing a test over and to the extent that this is caused by the `pixel-match` threshold (`0.18`) I think the threshold is too low. We should consider setting the threshold higher and not fight with it at this point.

Once we get the tests more stable and mature, we can start lowering the threshold and start optimizing the threshold.

![image](https://github.com/user-attachments/assets/a9c34940-6e4a-44ca-a32a-5dbd701c41f2)

**Comment by raineorshine** [comment]
Sure, we can try in increasing it slightly. If we increase it too much we're going to start getting false positives, e.g. tests not differentiating light gray from dark gray, or dark gray from black.

**Comment by raineorshine** [comment]
Has not been triggered by the CI in a while. I think it was likely fixed by another change.
