### ISSUE TITLE
Handle caps keyboard shortcut 

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#250]
On some platforms, `e.key` returns ‘S’ instead of ‘s’. Make sure this is handled the same as `s + e.shift` in [shortcuts.js](https://github.com/cybersemics/em/blob/111cf111c01299ad0e07fc2e4db841d6a7499cc5/src/shortcuts.js#L150).

**Comment by y471n** [comment]
@raineorshine  Need more clarity on this issue.

**Comment by raineorshine** [comment]
@y471n This is assigned to @enukeabhi.
