### ISSUE TITLE
Editable width is different between children and grandchildren

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#251]
The width of a thought that is a child of the cursor is longer than the width of a thought that is a grandchild of the cursor. They should be the same (equal to the shorter). 

This should be a CSS only change. You will need to compensate for the additional margin appropriately. 

Grandchild:
![71EC0902-4B4A-44CC-9289-5C43FD0EE906](https://user-images.githubusercontent.com/750276/71624560-6eafd400-2ba0-11ea-997f-b1feb8891d8f.jpeg)

Child:
![7BCF8754-7247-4CBD-91BF-C37E528E55DE](https://user-images.githubusercontent.com/750276/71624561-6eafd400-2ba0-11ea-9896-61bfddd4952e.jpeg)

**Comment by y471n** [comment]
@raineorshine 

I don't think this is an issue. When you click the child in 2nd screenshot, all of the thoughts/contexts move a little to left hence more space for child (which is focussed). But in first one if you can see alignment all are a bit to right. This would be to accommodate the parent of "Integral Theory" too in the screen (which isn't visible in screenshot above)
PS: I also debugged it locally.
Hence, not a bug.

**Comment by raineorshine** [comment]
@y471n Thanks for your input. It does functionally make sense, since this is more room for the children without the grandparent thought visible. That said, it is distracting for the user to see the text reflow during navigation. For that reason, I still consider it an issue to be corrected.
