### ISSUE TITLE
Superscript should be rendered a few pixels to the right

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#252]
As you can see, the `Superscript` component is too far left and overlaps the thought component. It should be shifted a few pixels to the right. 

- Tested on iOS Safari. Please confirm that this issue also exists on your platform if different. 
- This is a CSS only change to `App.css`. 

![4A3A60AC-3202-49BC-96FE-7312BAEC33B7](https://user-images.githubusercontent.com/750276/71624756-6efc9f00-2ba1-11ea-9826-4b7202c617ac.jpeg)

**Comment by y471n** [comment]
Hi @raineorshine  Can you please assign this issue to me.
