### ISSUE TITLE
Space before superscript at font size 16

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#2520]
Note that reproducing this correctly depends on the window width, font size, and the specific thoughts below.

## Steps to Reproduce

```
- a1
  - a2
    - a3
      - b1
        - b2
          - Dehejia, Vidya. "India's Visual Narratives: The Dominance of Space over Time," in Paradigms of Indian Architecture: Space and Time in Representation and Design, Collected Papers on South Asia no. 13, ed. Giles Tillotson (Richmond, Surrey: Curzon, 1998), 80-106.
- c
  - Dehejia, Vidya. "India's Visual Narratives: The Dominance of Space over Time," in Paradigms of Indian Architecture: Space and Time in Representation and Design, Collected Papers on South Asia no. 13, ed. Giles Tillotson (Richmond, Surrey: Curzon, 1998), 80-106.
```

1. Set window width to 1470 pixels.
2. Set font size to 16.
3. Set the cursor on `b1`

## Current Behavior

There is a space in between the thought and the superscript:

<img width="1469" alt="Screenshot 2024-11-01 at 11 54 58 AM" src="https://github.com/user-attachments/assets/5d652a86-71e0-444c-ae80-e5cd3cbb87a9">

## Expected Behavior

Superscript should be rendered immediately after the thought:

<img width="1469" alt="Screenshot 2024-11-01 at 11 55 43 AM" src="https://github.com/user-attachments/assets/e4d1f5ae-c9e8-4c4e-8ac1-5dcfa509d547">

**Comment by snqb** [comment]
![{902CB8BE-32BA-4FA6-A7EF-4CD1622E4D08}](https://github.com/user-attachments/assets/85aeaf31-218a-412c-b33c-42651f243913)

could not reproduce on vivaldi browser(chromium) in dev mode with given instructions

**Comment by raineorshine** [comment]
Yes, it's very hard to reproduce! Note that it only happens for me at width >= 1470, but at exactly 1470.

I wanted to document it, but given how rare it is, it's hardly worth trying to fix at this point.
