### ISSUE TITLE
[Safari] Empty thought height changes when first character is typed

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#2567]
Regression: 5b8914fc341dd18499b50a6cb46106d2df441304

## Steps to Reproduce

```
- [empty thought]
- b
```

Set the cursor on the empty thought and type a character.

## Current Behavior

The height of the first thought changes:

https://github.com/user-attachments/assets/1a2ddb19-8d45-4775-a31b-532b0ffbb534

## Expected Behavior

The height should not change.

**Comment by arashveysi3** [comment]
Working on it.
