### ISSUE TITLE
Export Modal

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#257]
When the export button is clicked, render a `Modal` that allows the user to choose the export format. 

- Reuse `Modal` component (See `ModalWelcome.js` or `ModalHelp.js`)
- Modal should contain:
  - Text should be `Export "{ellipsize(headValue(cursor))}" and {descendants.length} subthoughts as..."`
  - Dropdown menu that has a two options: "plain text" and "html (unformatted)"
  - "Export" button
  - "Cancel" link
- Should export `RANKED_ROOT` there is no `cursor`. In that case the text should say `"Export all {allDescendants.length} thoughts."`

**Comment by afaayerhan** [comment]
@raineorshine can I take this issue?
