### ISSUE TITLE
Scrolling works in gesture zone on Chromium/Android.

### ISSUE THREAD

**Issue by snqb** [cybersemics/em#2618]
While investigating [wrong gesture detection](https://github.com/cybersemics/em/issues/2605) on the scroll zone, I've also encountered a Chromium issue that allows for scrolling on the Gesture Zone.

## Steps to Reproduce
Scroll by dragging in the Gesture Zone on Chromium either on Android or Windows(if you have a touch screen like I do)
 
## Current Behavior
It allows scroll on the Gesture Zone on Android & Chrome.
https://github.com/user-attachments/assets/8b5c3ebf-dbfc-4d33-a53b-d278d920ca3b

## Expected Behavior
It plainly shouldn't allow for scroll there.

**Comment by snqb** [comment]
Reuploading the video, as it attached improperly above.

https://github.com/user-attachments/assets/94ed9b34-acec-4318-a1c8-3fec09f33864

**Comment by raineorshine** [comment]
Thanks for the update. I don't see any comments explaining why `e.cancelable` is checked, so removing it worth a try!
