### ISSUE TITLE
[Mobile] The Stars background is crudely attached.

### ISSUE THREAD

**Issue by snqb** [cybersemics/em#2619]
Is this the correct look for the stars on the background?
It looks cut off: on Android, on iOS and even on desktop browser when in smaller size mode.

## Steps to reproduce
Just add like 50-100 thoughts and look at the Gesture Zone.
![{6571B0F2-80CE-47D1-A842-225676D6EDFD}](https://github.com/user-attachments/assets/499de666-1870-4100-86a2-2a94c57fc073)

## Desired behavior
Feels like this should be a long and continous starry canvas, without being cut off like this.

**Comment by raineorshine** [comment]
Thanks, you're right. It needs to be tiled.

**Comment by snqb** [comment]
![image](https://github.com/user-attachments/assets/9d39d908-3394-4cba-85bc-63919cf0a2fe)
does this look alright?

**Comment by raineorshine** [comment]
Looks good from here. I'll need to use the live version and scroll a bit to know for sure.

**Comment by snqb** [comment]
https://github.com/cybersemics/em/pull/2621 if you can try it here
