### ISSUE TITLE
formatSelection: IndexSizeError on set whole thought color after selection color

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#2629]
I found a regression with `formatSelection` when changing the text color of the entire thought after setting the text color of a selection.

## Steps to Reproduce

1. Create thought `Hello world`.
2. Select the text `world`.
3. Open the ColorPicker and click the blue swatch.
5. Click the blue swatch again.

## Current Behavior

`Uncaught IndexSizeError: Failed to execute 'collapse' on 'Selection': There is no child at offset 2.`

<img width="735" alt="image" src="https://github.com/user-attachments/assets/63f4f88a-9d81-4ffb-91d7-feffb91e84c1">

## Expected Behavior

There should be no error, and the whole thought should be blue.

## Note

I have not verified, but this looks to me like `window.getSelection().focusOffset` is not handled correctly when `window.getSelection().focusNode.nodeType` is an ELEMENT_NODE.

> Offset: If the focus node is a TEXT_NODE, then offset refers to the character offset of the caret. If the focus node is an ELEMENT_NODE, then offset is the index of the element before the caret. For example, offset: 1 on an ELEMENT_NODE means the caret is after the focus node. Thus, do not mistakenly assume the offset is always a character offset.

**Comment by RED-ROSE515** [comment]
@raineorshine , I can't find the regression here.
It works well on my side.

**Comment by RED-ROSE515** [comment]
I will check about that.

**Comment by raineorshine** [comment]
Added: #2684
