### ISSUE TITLE
[RegExp] Fix isURL

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#263]
The regular expression in [`isURL`](https://github.com/cybersemics/em/blob/a7e11bf3afdb617081ae8d2e466d77afe0aeb4a4/src/util/isURL.js) is not working for all cases.

False negatives (incorrectly returns `false`):
- https://link.springer.com/article/10.1057/s41303-017-0039-0
- https://www.academia.edu/12962582/Embodiment_Semiosis._Violi_P

False positives (incorrectly returns `true`:
- 3.5/5

Create a unit test that returns `true` for the following urls:

- http://nonssl.com
- https://ssl.com
- localhost:3000/
- nohttp.com
- withslash.com/
- sub.domain.com
- withpath.com/a/b

And returns `false` for the following:

- e.g.
- 3.5/5

**Comment by mul53** [comment]
Hey @raineorshine i can work this, will make the isURL function work as intended with tests.

**Comment by raineorshine** [comment]
@mul53 Okay, thanks!
