### ISSUE TITLE
Edited thought not sorted correctly in descending list

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#2725]
## Steps to Reproduce

```
- x
  - c
  - b
  - =sort
    - Alphabetical
      - Desc
```

1. Set the cursor on `x`. 
2. Activate New Subthought Above (Meta + Shift + Enter). 
3. Type `a`.

## Current Behavior

`a` is not re-sorted:

```
- x
  - a
  - c
  - b
  - =sort
    - Alphabetical
      - Desc
```

## Expected Behavior

`a` should be sorted in correct descending order:

```
- x
  - c
  - b
  - a
  - =sort
    - Alphabetical
      - Desc
```

## Testing

Add an RTL test.

**Comment by RED-ROSE515** [comment]
https://github.com/user-attachments/assets/dc2211c3-62d6-4389-b203-b783492d45fa

As you can see in this video, #2737 Pr will resolve this issue too.

**Comment by raineorshine** [comment]
Beautiful!
