### ISSUE TITLE
Cursor disappears after moving parent

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#276]
`existingThoughtMove` causes the cursor to disappear in some circumstances.

## Steps to Reproduce

Given the following structure and cursor position:

- A
  - C
    - y
  - B
    - x (cursor)

Drag "B" above "C".

## Current Behavior

The thought cursor disappears.

## Expected Behavior

The thought cursor should stay on the same element even after it is re-ordered or moved.

- A
  - B
    - x (cursor)
  - C
    - y

## Notes

This appears to be caused by the new rank of "B" not being updated in the `cursor` state variable.

## Requirements

The cursor should similarly be preserved when dragging to a parent or uncle.

**Comment by sparklingW** [comment]
I figured out that problem occurs not only because of the cursor(state variable) doesn't update, also it may occur because newPath contain elements except last one, so if we moved our element above and our cursor was on a child element of C(took from your example above), newPath will contain only 'C' element.

**Comment by incora-dev** [comment]
@raineorshine  Estimate: 2.5h

**Comment by incora-dev** [comment]
@raineorshine 
Spent a lot of time I have found a possible solution. The possible problem is the wrong calculation for `isEditing` variable in Thought.js(line 94). When I try to calculate this variable without rank (just using value), it works partially, but I don't like this solution. I don't have any idea about other solutions for now.

My temporary solution(without good code style):
```
  // const isEditing = equalPath(cursorBeforeEdit, thoughtsResolved)
  const isEditing = thoughtsResolved && cursorBeforeEdit.every((e, i) => {
    return e.value === (thoughtsResolved[i] && thoughtsResolved[i].value)
  })
```

**Comment by raineorshine** [comment]
Great! Thanks for identifying the cause of the problem.

If you ignore `rank` then `isEditing` will incorrectly return `true` when editing a duplicate thought in the same context.

Why is `cursorBeforeEdit` still referring to the old cursor? I would think that by the time the thoughts are re-rendered, the `existingThoughtMove` will have already updated it.

I think the problem is here:
https://github.com/cybersemics/em/blob/dev/src/reducers/existingThoughtMove.js#L186-L187

It updates the cursor when the editing thought itself is moved, but not when its ancestor is moved. We may need to check [`isEditingPath`](https://github.com/cybersemics/em/blob/dev/src/components/Subthoughts.js#L90) like the Subthoughts component.
