### ISSUE TITLE
ArrowUp moves selection to beginning of previous sibling

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#333]
## Current Behavior

Hitting `ArrowUp` moves the selection to the beginning of the previous thought.

## Expected Behavior
Hitting ArrowUp should move the selection to the last line of the previous thought, directly up. This mimics the default browser behavior when hitting `ArrowUp` within a multi-line thought (although this is currently broken. See: #550).

e.g.

```
- This is a thought that
  is now wrapping.
- Test|
```

Hitting `ArrowUp` should result in:

```
- This is a thought that
  is n|ow wrapping.
- Test
```

**Comment by raineorshine** [comment]
When a shortcut keycode or gesture is detected, the cursor and application state may or may not allow for that shortcut to be executed (for example trying to indent a thought that is already indented all the way). If `canExecute` returns `true`, then `e.preventDefault()` will be called on the native event and the `exec` function of the shortcut will be called.

This statement returns `false` so that in prose view the default browser behavior for the up arrow is executed. This allows the browser selection to move up one line (browser default) instead of moving the cursor up to the previous paragraph (the cursorUp action-creator). It has the intended effect describe above. We need to change the behavior when moving the cursor between thoughts while preserving the correct up arrow behavior when moving the browser selection within a thought.

**Comment by Athuln** [comment]
Presently an unexpected behaviour i came across was in a multi line thought ,when cursor is presently at second line, and up arrow is pressed cursor should go to the first line ,but the cursor jumps to the thought present above. 
Same is the case for down arrow,when down arrow is pressed cursor goes to start of next thought,but cursor should go to the line below.Are they intended behaviours.

**Comment by raineorshine** [comment]
Good catch! No, that is not intended. I think we need the requested behavior implemented not just in prose view, but for any multi-line thought.

**Comment by raineorshine** [comment]
I added that as a separate issue: #550.
