### ISSUE TITLE
Table View: Column 1 should use triangle overlay bullet.

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#339]
## Current Behavior

In Normal View, the cursor is indicated by a dark gray overlay bullet that surrounds the normal bullet. In Table View, when the cursor is on a thought in column 1, the overlay bullet is hidden completely.

<img width="230" alt="Screen Shot 2020-02-16 at 12 42 52 PM" src="https://user-images.githubusercontent.com/750276/74612828-4cc5ce80-50c6-11ea-9974-efd7e036fa86.png">

Instead, a gray, right-pointing triangle should be shown to the left of the thought.

## Expected Behavior

<img width="230" alt="Screen Shot 2020-02-16 at 12 42 52 PM" src="https://user-images.githubusercontent.com/750276/74612876-c3fb6280-50c6-11ea-9f0d-0dc67a658c41.png">

**Comment by victoray** [comment]
I can start with this.

**Comment by raineorshine** [comment]
Great! Please let me know if you have any questions. Make sure you read the contributing guidelines and follow existing coding style.

**Comment by victoray** [comment]
Are there any extra requirements for running the project locally?

**Comment by raineorshine** [comment]
Just `npm install` and `npm start`. It's an old `create-react-app`.

**Comment by victoray** [comment]
will this fix be applied to just column one or all nested columns.

**Comment by raineorshine** [comment]
Just column 1. As you can see in the screenshots, the bullets in column 2 are already visible.

**Comment by victoray** [comment]
Yes, I understand, if i activate table view for `x` , it's children should also have the overlay.

**Comment by raineorshine** [comment]
I'm going to use the same example as above for clarity, but yes, if you activate table view for `a`, its child should show a triangle overlay when it has the cursor.

The new overlay arrow will represent the cursor in column 1. The existing triangles are the bullets that represent thoughts, not the cursor.

**Comment by victoray** [comment]
okay, I will finish up tests and submit a PR

**Comment by victoray** [comment]
I had to remove the `text-align: right` property to be able to position the arrow properly, I am open to discussing any further changes you have in mind.
