### ISSUE TITLE
Import Performance

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#340]
When importing more than 10* thoughts at a time, dispatch an `alert` with text "Importing 1/20 thoughts..." that is updated for each thought imported. This should be followed by an inline "Cancel Import" link that cancels the import.

Updates should be throttled to 100* milliseconds.

When successfully completed, it should dispatch an `alert` with text "Imported 20 thoughts" which disappears after 10 seconds*.

**Constants should go in `constants.js`.*

**Comment by ArtMyWeb** [comment]
@raineorshine 
I started project, open it through ngrok in browser, go through 2 tutorials, research code a bit, but I can not find Import feature to check it's behaviour right now and check the code of this feature.

**Comment by raineorshine** [comment]
No problem! Glad you asked. 

Generally all keyboard commands and gestures (swiping on mobile) in the app are located in `/src/shortcuts`. These are the entry points to most of the functionality of the app. `import` is a little different since it is launched from the [Editable paste handler](https://github.com/cybersemics/em/blob/dev/src/components/Editable.js#L302-L305). The actual [`importText`](https://github.com/cybersemics/em/blob/dev/src/util/importText.js) function is in `/util`.

(Side note: you shouldn't have to use ngrok unless you are testing on mobile specifically. The app works on a normal browser accessing `localhost:3000`.)

**Comment by ArtMyWeb** [comment]
@raineorshine 
Thank you! But I can not find how to start import in app in browser.
I did not find button or description on Help page or in Tutorials.

**Comment by raineorshine** [comment]
`import` is a little different since it is launched from the [Editable paste handler](https://github.com/cybersemics/em/blob/dev/src/components/Editable.js#L302-L305). The actual [`importText`](https://github.com/cybersemics/em/blob/dev/src/util/importText.js) function is in `/util`.

If you copy and paste any text into **em**, it will call `importText`.

**Comment by raineorshine** [comment]
@ArtMyWeb Given that this feature is intended to provide user feedback during larger imports, it is worth it to make some initial measurements to confirm where the bottleneck is. I was surprised to find the bottleneck was not in the parser, but in some naive code that I wrote that seems to be causing a huge performance hit.

When pasting [this sample data](https://docs.google.com/document/d/18HdtsGCtmn6xs7R4LLwhMRucZJ8uHUHjJcAisyEPK8o/edit?usp=sharing) (~8.5kb), I get the following import times:

replace ([L41-48](https://github.com/cybersemics/em/blob/dev/src/util/importText.js#L41-L48)): 21.617 sec
parse ([L50-212](https://github.com/cybersemics/em/blob/dev/src/util/importText.js#L50-L212)): 0.053 sec
sync ([L214-227](https://github.com/cybersemics/em/blob/dev/src/util/importText.js#L214-L227)): 0.264 sec

Obviously that first section is a big problem and will solve the major performance issue.

Once that is solved, it raises a couple questions:

1. How many thoughts can be imported before a significant performance bottleneck is hit?
2. How can `htmlparser2` be throttled?

My brief investigation into `htmlparser2` does indicate that it has [streaming capabilities](https://github.com/fb55/htmlparser2/wiki/Parser-options#streaming) as well as undocumented [`pause` and `resume` methods](https://github.com/fb55/htmlparser2/commit/c65a46154c7c019ee8aaea2e896d7be0e8fed12c) which may be helpful.

Looking forward to hearing your thoughts.

**Comment by marucat** [comment]
I will try and get back to you

**Comment by ArtMyWeb** [comment]
I will try and get back to you

**Comment by raineorshine** [comment]
Performance dramatically improved in e6e2935ef76fe6b44ce0335cd9db0eb50d978d1c.
