### ISSUE TITLE
Divider: Should set cursor after creation

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#342]
When the user types `---` (three dashes), the thought is converted into a horizontal [`Divider`](https://github.com/cybersemics/em/blob/dev/src/components/Divider.js). Doing a [search for "isDivider"](https://github.com/cybersemics/em/search?q=isDivider&unscoped_q=isDivider) provides a good survey of all of the divider business logic.

## Steps to Reproduce
1. Hit Enter and type "A" to create a new thought
2. Hit Enter to create a new empty thought
3. Type `---` to create a divider

## Current Behavior

Divider is not highlighted (cursor).

## Expected Behavior

The cursor should be on the divider thought and the divider should be highlighted.

**Comment by parthpnp** [comment]
Can not reproduce the issue. Can you please verify.

**Comment by raineorshine** [comment]
@parthpnp Thanks! Turns out it is only an issue when the divider is not the first child. I updated the steps to reproduce accordingly.

**Comment by raineorshine** [comment]
This was supposed to be fixed as described in https://github.com/cybersemics/em/pull/522#discussion_r404212502, but it is happening again.
