### ISSUE TITLE
Allow cursor on context home thought

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#343]
When in the Context View, if the thought is in the root context, it will display a home icon.

<img width="216" alt="Screen Shot 2020-02-16 at 6 46 16 PM" src="https://user-images.githubusercontent.com/750276/74617975-18b1d400-50ed-11ea-82af-b70d06676ed8.png">

## Current Behavior

The cursor cannot be set on the home thought. Using the up and down arrows skips the home thought.

## Expected Behavior

Instead of navigating to the home context, clicking the home icon should place the cursor on the thought. The home thought should not be editable, but may be deleted.

Using the up and down arrows should move the cursor to the home thought just like any other thought. This may require refactoring one or more of `cursorUp`, `cursorDown`, `cursorNext`, `cursorPrev`, `nextSibling`, `prevSibling`, `selectNextEditable`, `selectPrevEditable`, `nextThoughtElement`, and `prevThoughtElement` in order to have an elegant general solution instead of adding more special cases.

Also see: `setCursor`.

**Comment by raineorshine** [comment]
@shresthabijay Anmol confirms this has been fixed in `dev`. Could you test when you get the chance? Thanks!

**Comment by shresthabijay** [comment]
@raineorshine  I tested this on the latest `dev`.

- Using the up and down arrows moves the cursor to the home thought just like any other thought. But when home icon thought is selected, the cursor selection still remains at the previous node. So on trying to edit will actually cause edit on previous node.

![Screen Capture_select-area_20200630103115](https://user-images.githubusercontent.com/25879100/86085100-0b0a5300-babe-11ea-84fd-48ee9d57aa4b.png)

- Clicking the home icon doesn't place the cursor on the thought and still navigates to the home context.
- Delete inside context view doesn't work at all for me for any thoughts.

**Comment by raineorshine** [comment]
> when home icon thought is selected, the cursor selection still remains at the previous node

To remove the caret, consider the simple approach in 7cacad65b2ffa90cfc12b0c83e4cc0851a244782. (Open to suggestions about how to cleanly move the side effect out of the reducer though.)

**Comment by raineorshine** [comment]
Here is an example of testing the browser caret: https://github.com/cybersemics/em/blob/dev/src/reducers/__tests__/deleteEmptyThought.js#L219-L252

**Comment by raineorshine** [comment]
Since JSDOM does not have full caret emulation, we should use Puppeteer for caret testing.

**Comment by raineorshine** [comment]
Hold until #495 since thought structure is changing
