### ISSUE TITLE
Browser selection not preserved on page reload

### ISSUE THREAD

**Issue by snqb** [cybersemics/em#359]
## Current Behavior
When the page is reloaded, the cursor is restored to the correct thought, but the placement in it is always in the beginning.
E.g. the thought was `hey jude` and the cursor was in the end of it: `hey jude|` (| for cursor)
when the page reloads, it becomes `|hey jude`

## Expected Behavior
the cursor location should be preserved: `hey jude|`

**Comment by raineorshine** [comment]
To clarify `cursor` on this project generally refers to a specific state variable that represents the focused thought. The browser cursor is different, and is usually referred to as the "browser selection". I would like to rename `cursor` to `focus` to eliminate this confusion.
