### ISSUE TITLE
Settings page

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#36]
Create a Settings page (full-screen modal, like the shortcuts modal) and move the settings currently in the footer to the Settings page.

- dark mode
- swap swipe right/left
- auto sort
- refresh

**Comment by robertbegna** [comment]
hey, I could create the settings page if you'd like

**Comment by raineorshine** [comment]
That would be great! Let me know if you have any questions about running the app and finding the right places to make changes.

**Comment by raineorshine** [comment]
@robertbegna Any update?
