### ISSUE TITLE
Re-architect store/local/remote storage

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#378]
The redux store should serve as a single source of truth for the app. Currently `localStorage`, `localForage`, and `firebase` are used in too ad hoc a fashion. Consider how best to re-architect this aspect of the app to consolidate state persistence.

- Is there an existing library that syncs the redux store to other data stores?
- Could this be accomplished with custom middleware?

**Comment by raineorshine** [comment]
- `sync` is my early attempt to consolidate storage logic
- Redux supports `persist`, which may be able to plug in to `localForage` and `firebase`
- Updates are done slightly differently between `localForage` (key-value store) and `firebase` (nested object)
- We can use the deep key path that is passed to `firebase` (e.g. `thoughtIndex/f3b88c`) as the key in `localForage`.
- Must support merging individual thoughts from different states based on timestamps (different devices).
- `migrate` must be run on `localForage` and `firebase` data due to offline mode and multiple devices.

**Comment by raineorshine** [comment]
Some thoughts:

There are plenty of persistor libraries like [react-persist](https://github.com/rt2zz/redux-persist/), but it’s not clear how much effort it would take to configure the specific combination of `localStorage`, `indexedDB`, and `Firebase`. 

The Redux middleware only has access to the dispatched action, but the root reducer has access to the before and after states. If we have to write our own storage engines, it might be better to simply wrap one or more reducers.

Consider wrapping the `thoughtIndex` reducer since it is the last place we still have access to `thoughtIndexUpdates` before they become `thoughtIndex`. Other reducers will have to be wrapped for other persisted values (cursor, lastUpdated, tutorial, etc). Luckily they don’t require access to intermediate values. 

We should keep the persistence layer as decoupled as possible. Instead of calling `db` and `sync` functions directly, they should be called automatically on the appropriate state slice.

**Comment by raineorshine** [comment]
Settled for isolating `sync` calls to `updateThought` reducer in order to avoid fat action-creators or extra diffing on state to determine updates.

**Comment by raineorshine** [comment]
**Another idea:** 

1. Add updates to state. Merge with previous updates. 
1. Subscribe to the store 
1. If `updateQueue` is not empty, call `flushQueue` action-creator
1. `flushQueue` syncs to local db and remote, and clears the queue

Thus the reducers remain pure.

**Comment by raineorshine** [comment]
![em -  sync flow](https://user-images.githubusercontent.com/750276/80919829-58ba4780-8d29-11ea-890d-296e16abfc43.png)

**Comment by anmolarora1** [comment]
The architecture looks good. There’s a good separation of concerns.
SyncQueue looks like a parallel sub-state of the app, which might come with additional managing overheads. A few thoughts/questions -
1. As JS is single-threaded, the `syncQueue` would still impact the performance and perhaps the interaction with the app, when syncing is in process. 
2. There can be multiple async calls to `Firebase` and `localDB` and hence, race conditions (unless we ensure that the sync function is only called after the last call has completed). How do we ensure that if there are such race conditions, only the latest updates thrive? Or do we wait for the previous call to complete before making the new call?

**Comment by raineorshine** [comment]
> The architecture looks good. There’s a good separation of concerns.

Okay, that's good.

> SyncQueue looks like a parallel sub-state of the app, which might come with additional managing overheads.

Yes, `syncQueue` would be duplicating information contained in `thoughtIndex` and `contextIndex`. However, `thoughtIndex` and `contextIndex` will *only* be updated through the `syncQueue` itself via a special `updateThoughts` reducer, which should prevent any inconsistencies in the state.

> 1. As JS is single-threaded, the `syncQueue` would still impact the performance and perhaps the interaction with the app, when syncing is in process.

I don't really see this, but let me know if I'm missing something. `syncQueue` is just a static slice of the state. `sync` is an asynchronous function. Like all asynchronous functions in Javascript it won't block while it's waiting for the network response.

> 2. There can be multiple async calls to `Firebase` and `localDB` and hence, race conditions (unless we ensure that the sync function is only called after the last call has completed). How do we ensure that if there are such race conditions, only the latest updates thrive? Or do we wait for the previous call to complete before making the new call?

If there are multiple updates, they will be merged into `state.syncQueue` atomically in the reducer. `store.subscribe(sync)` will call `sync` once at the end of all state updates. Plus we can always debounce it if there are multiple actions dispatched asynchronously. `syncQueue` will include all updates queued up at that point.

I think the part to be careful about is to ensure a tight loop between `sync` and `clearQueue`. We can't allow updates that haven't been synced to be cleared. Likewise, we don't want any updates that have been sync'd to be left in the queue. This is why `clearQueue` is called synchronously, not after receiving a success from the write/network operation. This is the most speculative part of my proposal so let me know if you believe this to be a problem.

**Comment by shresthabijay** [comment]
@raineorshine This architecture makes sense. 

> Consider wrapping the `thoughtIndex` reducer since it is the last place we still have access to `thoughtIndexUpdates` before they become `thoughtIndex`. Other reducers will have to be wrapped for other persisted values (cursor, lastUpdated, tutorial, etc). Luckily they don’t require access to intermediate values.

I totally agree with this. Our current architecture has multiple reducers responsible for `thoughtIndex `and `contextIndex` updates and at some places these reducers are composed too. So root reducer is the only place we will be able to access `thoughtIndexUpdates` and `contextIndexUpdates`. We can copy easily copy the duplicate these and calculate `synceQueue`.

However we really need a good plan to handle error while syncing. We cannot afford infinite dispatch loop to retry the failed sync.  If we find a proper way to do it then it will be a tight architecture.

**Comment by raineorshine** [comment]
> @raineorshine This architecture makes sense.

Good, wanted to make sure I was on the right track.

> 
> > Consider wrapping the `thoughtIndex` reducer since it is the last place we still have access to `thoughtIndexUpdates` before they become `thoughtIndex`. Other reducers will have to be wrapped for other persisted values (cursor, lastUpdated, tutorial, etc). Luckily they don’t require access to intermediate values.
> 
> I totally agree with this. Our current architecture has multiple reducers responsible for `thoughtIndex `and `contextIndex` updates and at some places these reducers are composed too. So root reducer is the only place we will be able to access `thoughtIndexUpdates` and `contextIndexUpdates`. We can copy easily these to create `synceQueue`.

Yup, and I have already consolidated the merging of `contextIndexUpdates/thoughtIndexUpdates` into `contextIndex/thoughtIndex` in a shared reducer [updateThoughts](https://github.com/cybersemics/em/blob/dev/src/reducers/updateThoughts.js). The only change to that reducer will be to copy the updates to the `syncQueue` and move `sync` out and into `store.subscribe.`

> 
> However we really need a good plan to handle error while syncing. We cannot afford infinite dispatch loop to retry the failed sync. If we find a proper way to do it then it will be a tight architecture.

`Firebase` has an internal queue and does automatic retries, so I'm hoping we can simply clear the queue regardless of the async response.

**Comment by raineorshine** [comment]
@anmolarora1 @shresthabijay Trying to clear the queue within a `store.subscribe` handler got sketchy, so I tried two similar approaches. Both successfully remove the side effect from the reducer, but do so in different ways: 

- #666 - middleware, action-creator, reducer
- #667 - store enhancer

I mention the overall approach and potential downside in the opening description. Please review and let me know which approach you think is best!

**Comment by anmolarora1** [comment]
> @anmolarora1 @shresthabijay Trying to clear the queue within a `store.subscribe` handler got sketchy, so I tried two similar approaches. Both successfully remove the side effect from the reducer, but do so in different ways:
> 
> * #666 - middleware, action-creator, reducer
> * #667 - store enhancer
> 
> I mention the overall approach and potential downside in the opening description. Please review and let me know which approach you think is best!

@raineorshine I checked out both the solutions and they look equally brilliant with some trivial differences. Though not strongly opinionated, I'd opt for #666 because of its simplicity. 
I've left my comments on the issues.

**Comment by raineorshine** [comment]
#666 merged
