### ISSUE TITLE
Fix url icon positioning

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#413]
Fix the positioning of the link icon that appears after urls. There is a hidden ThoughtAnnotation component of the same size as the Thought, which is supposed to place the icon in the correct place while remaining independent from the Thought itself (which needs to span the full width for ease of selecting). Something seems to be causing the ThoughtAnnotation and Thought to be breaking differently. 

![59C671FC-6982-47E0-A586-207E83C06504](https://user-images.githubusercontent.com/750276/76165468-e9571b80-611c-11ea-9472-c823974b957e.jpeg)

**Comment by incora-dev** [comment]
Estimate: 1h

**Comment by incora-dev** [comment]
@raineorshine 
![image](https://user-images.githubusercontent.com/36540892/78248945-33ea6e80-74f6-11ea-9af2-4664666dae84.png)
I need write permission

**Comment by raineorshine** [comment]
@incora-dev All contributions are made through public pull requests. You can fork the repo, push to your branch, and open a pull request against `dev` to submit your work for review.
