### ISSUE TITLE
Reference.update fails on split

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#430]
## Steps to Reproduce
1. Log in
2. Add a thought
  - a
3. Go back and edit it from the beginning, so the browser selection is in between the first and second parts
  - b|a
4. Hit enter to split the thought

## Current Behavior

```
Reference.update failed: First argument 
contains undefined in property 
'users.m9S244ovF7fVrwpAoqoWxcz08s5
2.recentlyEdited.💡 Ideas.Resen: 
Resilient Citation Engine.Discussion.Cross 
site origin.Cache and notarize.path.3.rank'
``` 

## Expected Behavior
No error

- a
- b

**Comment by raineorshine** [comment]
@shresthabijay Are you able to reproduce this? Thanks!

**Comment by shresthabijay** [comment]
> @shresthabijay Are you able to reproduce this? Thanks!

@raineorshine I tried this with the latest dev.  I was not able to reproduce it.
