### ISSUE TITLE
Blank thoughts on refresh

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#444]
Sometimes thoughts and their subthoughts are replaced with blank thoughts when the page is refreshed. It seems like edits are sometimes not being committed to local and/or Firebase (not sure which one). This was happening in the normal course of editing multiple items over a period of 10-20 minutes. At some point the app crashes, and then the thoughts are blank on reload. There is no error message on screen, although I didn’t see what was in the console. 

**Observation 1:** When the blank thought is edited back to its previous value, its children suddenly appear. This shows that the subthoughts are being created and edited correctly. It might suggest that the thought’s context is being overwritten afterwards, removing the newly added thought and leaving the subthoughts floating. 

**Observation 2:** The missing thoughts are searchable. This shows that they are correctly added to the `thoughtIndex`. It is unclear whether they have the correct context always. I encountered a situation where a thought added to `/apple` was shown as having context `/a` in the `thoughtIndex`. 

- Dexie and/or Firebase?
- Mobile and/or Desktop?
- Only occurs with > 10k thoughts?
- existingThoughtChange failing?
- ordering issue?

![005BA36C-FCC9-4896-B041-9D93CF1DF573](https://user-images.githubusercontent.com/750276/77333720-77203280-6ce9-11ea-915c-a5dfe8a3505c.jpeg)

**Comment by shresthabijay** [comment]
@raineorshine This issue needs proper attention and lot of testing.

**I have following questions for you.**

1. Was this issue introduced after recent changes ? If so can you point me to the commit that you think might have introduced it ? 

2. Have you seen this issue with lower number of thoughts( < 1k )?

3. Have you noticed any inconsistency that might be a result of hash collisions of thoughts or context ?

I will start investigating right away. I will keep you updated.

**Comment by raineorshine** [comment]
> @raineorshine This issue needs proper attention and lot of testing.

Yes, I agree. Unfortunately there are a lot of unknowns still.

> 1. Are you able to consistently reproduce this issue ?

I don't have exact steps to reproduce, as it appears to involve some kind of timing issue and I don't see the issue until I refresh the page. It happens frequently though when I am engaged in personal writing.

> 2. Was this issue introduced after recent changes ? If so can you point me to the commit that you think might have introduced it ?

This has been an issue since the first throttled editing was merged. No idea which commit in there may have caused this. May be caused not by a specific commit, but by a timing issue with throttling that we didn't take into account. Hard to tell.

> 3. Have you seen this issue with lower number of thoughts( < 1k )?

No, but I don't spend as much time with fewer thoughts outside of targeted development. My personal thoughtspace has about 10,000 thoughts.

> 4. Have you noticed any inconsistency that might be a result of hash collisions of thoughts or context ?

There is some inconsistency due to different expressions with the same hash, e.g. plurals like "test" and "tests" that intentionally generate the same hash, however the `value` in the `thoughtIndex` is not necessarily an exact match to any of them, so wherever that is used there are potentially problems. This is related to #426.

> 
> I will start investigating right away. I will keep you updated.

**Comment by raineorshine** [comment]
One more variable to consider. (As if there aren't enough!) I generally have **em** open on two devices: my phone and my laptop. It is possible that when I make updates on my phone, and then go and open my laptop, the outdated data from the laptop is overriding the new data. This would explain why thoughts are not in their contexts, but still in the `thoughtIndex`. The thoughts are being sync'd properly to Firebase and down to the other device, but then the laptop is potentially overriding the new context with the old context. Not sure why thoughts are blank though, or why exactly this would happen, but we have to consider it as another possibility.

I will close **em** on my laptop and only use my phone, and see if it's still an issue. Then I will open it on my laptop again to see if it comes back. Might take a day or two before I notice a pattern.

**Comment by raineorshine** [comment]
Syncing issues were first explored in #304. I suspect that #230 may be a part of the problem. Entries in `thoughtIndex` have a `lastUpdated` property that can be compared during a sync. `contextIndex` does not have one, thus no way to know if the incoming contexts are newer or older. The root issue could be this, with the blank thoughts just being a new manifestation due to the throttled edits.

**Comment by raineorshine** [comment]
**Observation 3**: I’ve been using **em** for two days on my phone only with all other devices signed out, and this issue *has not occurred*.
