### ISSUE TITLE
Split line does not work after speech-to-text entry

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#457]
iOS Safari

## Steps to Reproduce
1. Create a new thought. 
1. Use dictation to enter two or more words.
1. Close the keyboard 
1. Tap between two words
1. Hit Enter

## Current Behavior
An empty thought is created before the dictated thought

## Expected Behavior
The dictated thought should be split into two thoughts at the browser selection

**Comment by pushkov-fedor** [comment]
Actually on Safari IPhone 6s split line doesn't work at all. I have the same experience on Android. Enter, while cursor is on any position within a Thought, causes creation of an empty thought.

I've checked `splitThought` reducer. `valueLeft` is empty  there  and `valueRight` is a whole Thought's value. It seems to me that there's something wrong with offset. What about 1-1.5hours for this one?

**Comment by raineorshine** [comment]
Yes, that would be great. Please create a separate issue for `splitThought` not working on those devices.

**Comment by pushkov-fedor** [comment]
I think it was solved here: https://github.com/cybersemics/em/pull/720

On 6s i have expected behavior

**Comment by raineorshine** [comment]
Indeed!
