### ISSUE TITLE
Multi line superscript positioning 

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#468]
The superscript should appear inline at the end of a thought. This should be on the last line right at the end of the text on multi line thoughts, just like single line thoughts. 

Care must be made to not introduce any regressions related to Thought Annotation rendering. 

![3656E80A-5C93-46FC-B684-A704D946DC53](https://user-images.githubusercontent.com/750276/77717170-5b48b500-6fa5-11ea-92a0-d2f3192d5669.jpeg)

**Comment by incora-dev** [comment]
Estimate: 1h
