### ISSUE TITLE
Duplicate rank after merge empty thought

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#478]
Appears to be a regression from #406. 

## Steps to Reproduce
- a 
  - b
- *empty thought* [cursor]
  - c

## Current Behavior

The rank of 'c' does not change when it is merged, causing duplicate rank and duplicate render key.

```js
Warning: Encountered two children with the same key, `0`. Keys should be unique so that 
components maintain their identity across updates. 
```

## Expected Behavior

'c' (and any other children of the empty thought) should get new ranks that sequentially follow the rank of the last child in 'a'.

**Comment by shresthabijay** [comment]
fixed by #505
