### ISSUE TITLE
Url false negative

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#485]
The regex used to display a link next to urls has some invalid matches. 

False negatives:
(invalidated by the `.` character)
- http://www.cs.cornell.edu/report.pdf
- http://test.com/?foo=1.0

False positives:
- a.b.c (top level domain minimum 2 characters)

Consider https://github.com/kevva/url-regex

**Comment by incora-dev** [comment]
@raineorshine Estimate: 1h
