### ISSUE TITLE
Ancestor url changes along with descendant on edit

### ISSUE THREAD

**Issue by shresthabijay** [cybersemics/em#498]
Create a `thought`  and edit it's value to become same as one of its direct `ancestor`. Then as you keep editing that descendant thought the parts of url representing both edited thought as well as that specific ancestor keeps on changing the same. Using **New Thought** shortcut immediately won't work and using **New Subthought** will cause **cursor to loose focus**.

![captured](https://user-images.githubusercontent.com/25879100/78269636-94df6a00-7529-11ea-875f-18fed7ad3cdd.gif)

In above case url becomes **"/helloasdasd/helloasdasd/"**

**Comment by raineorshine** [comment]
Related: #23

**Comment by raineorshine** [comment]
Fixed with unique ids
