### ISSUE TITLE
Table style fixes

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#501]
- [x] Bottom spacing is smaller than top spacing 
- [x] Cursor overlap bullet is positioned incorrectly on non-first column 2 thoughts. 4d6b86b6
- [x] Column 1 with no subthoughts should have round bullet
- [x] Add more space in between rows (e.g. see What’s Important Today?)

**Comment by molecula451** [comment]
Which platform you're referring to ?

**Comment by raineorshine** [comment]
All platforms
