### ISSUE TITLE
Imported type incorrectly triggers no-unused-variables rule

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#506]
When a type is imported, it incorrectly triggers the `no-unused-variables` rule. See https://github.com/cybersemics/em/commit/a6599c80ef5a97e7f401bd084ff2dd6726725259#diff-a5aa9a98b54f7cb720be1a808707508fR10.

I tried the recommendation here, but it didn't work:
https://github.com/typescript-eslint/typescript-eslint/issues/46#issuecomment-470486034

How can we prevent this linter warning so that `eslint-disable-next-line` does not have to be used?

**Comment by anmolarora1** [comment]
It works fine for me without `eslint-disable-next-line`

**Comment by raineorshine** [comment]
@anmolarora1 Interesting. So you don’t get an error on either `npm run lint` or `npm start`?

**Comment by anmolarora1** [comment]
> @anmolarora1 Interesting. So you don’t get an error on either `npm run lint` or `npm start`?

No errors on either `npm run lint`, `npm run lintts` or `npm start`?

**Comment by raineorshine** [comment]
Of COURSE it's not erroring now 😂

I don't know if it's what caused it, but I did accidentally have `attribute.js` and `attribute.ts` in the same folder for a little while there. That was causing all sorts of import/compile issues.

Thanks for checking!
