### ISSUE TITLE
Table: Tap to create column 2 thought

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#509]
In a table, allow the user to tap in an empty column 2 to create a new subthought. 

e.g. 

- a *[table]*
  - b      *[tap here]*

Tapping to the right of `b` should result in:

- a *[table]*
  - b      *[empty thought]*

Which in list view would be:

- a
  - b
    - *[empty thought]*

**Comment by shresthabijay** [comment]
@raineorshine Should subthought be created when user clicks or taps inside the table column 1 content editable ? Or should it be created when it is focused ?

**Comment by raineorshine** [comment]
No, I think it would be confusing to create a subthought when clicking in column 1. The user is expecting to edit column 1, not create a new thought in column 2 in that case. Clicking in column 2 is intuitive since the user is clicking right where the new subthought will appear.

**Comment by raineorshine** [comment]
We’ve hit the budget on this task. Please discontinue all work on it.

**Comment by raineorshine** [comment]
Better to stay consistent with existing methods of creating a new subthought.
