### ISSUE TITLE
Prevent line break at superscript 

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#518]
![2A67D5C2-DA8A-4CDF-94EB-A0CC2D323C40](https://user-images.githubusercontent.com/750276/78498743-5dc7af00-7709-11ea-8e95-a7fd374899c9.jpeg)

## Steps to Reproduce

- a word 
- b [cursor]
  - a word

Convert “b” into a table (click the table icon in the toolbar)

## Current Behavior

The “2” superscript is on a separate line from “word”. 

## Expected Behavior

The “2” superscript should be positioned immediately to the right of “word” on the same line.

**Comment by incora-dev** [comment]
Spent: 1h
