### ISSUE TITLE
Table view and pinned context toggle stops working

### ISSUE THREAD

**Issue by shresthabijay** [cybersemics/em#521]
**Steps to reproduce:** 
1. Take a node and set it to table view from the toolbar.
2. Now select context view and then click table view in the toolbar again.

Now the table view shortcut stops working and it doesn't toggle back off. 
If we follow the same process with pinned context, it stops working too.

**Comment by shresthabijay** [comment]
@raineorshine  I found the cause of this issue. It is caused due inconsistency between `thoughtIndex` and `contextIndex`. To properly understand the cause we need to reproduce it step by step.

Steps:

1. Create a `thought` `A` and then create it's `subthought` `B`. 
   - A
     - B

2. Toggle on Table view , toggle on Context View and then toggle off Table view again.

Now Table view won't toggle off stops working.

So when A is set to Table view
- A
  - =view
     - Table

Here table has rank -1.

So if Table view is toggled off, `thoughtRanked` is calculated inside `toggleAttribute` using `rankThoughtsFirstMatch`. It has -1 as rank of `Table` which is correct. So when `existingThoughtDelete` is called both `thoughtIndex` and `contextIndex` remain consistent. 

But if we trigger toggle off Table view  when context view is turned on, `thoughtRanked` returned by `rankThoughtsFirstMatch` gives 0 as rank of `Table` instead of 1. So when `existingThoughtDelete` is called the`Table` node is being deleted from `thoughtIndex` but not from `contextIndex`. So it is causing inconsistency. So when we try to toggle off Table view, it won't work because `Table` node is not available in `thoughtIndex` anymore. But thought `A` will still be rendered in Table because view returned by function `attribute(thoughtsRankedLive, '=view')` still returns `Table` as value. It is because node `Table` is still available in `contextIndex`. 

So the cause of this issue is `rankThoughtsFirstMatch` returning different rank for node `Table` when context view is turned on which leads to inconsistency between `thoughtIndex` and `contextIndex`

One possible solution is that we don't allow Table view and context view to be turned on at the same time. I couldn't understand logic behind `rankThoughtsFirstMatch` when context is turned on.  Please let me know what you think about this.

**Comment by raineorshine** [comment]
Great work! Thanks for documenting this.

Ultimately we would like to be able to activate Table View within the Context View. However this isn't possible right now since `=view` is implemented as a meta thought. There's no way to add meta thoughts currently to the Context View. Adding a `=contextView` meta thought that can contain its own `=view` would be a good solution eventually.

For now, I think disabling Table View within the Context View is a good choice since this is lower priority.

**Comment by shresthabijay** [comment]
> For now, I think disabling Table View within the Context View is a good choice since this is lower priority.

Sure. I will work on that.

**Comment by shresthabijay** [comment]
> But if we trigger toggle off Table view when context view is turned on, `thoughtRanked` returned by `rankThoughtsFirstMatch` gives 0 as rank of `Table` instead of 1. So when `existingThoughtDelete` is called the`Table` node is being deleted from `thoughtIndex` but not from `contextIndex`. So it is causing inconsistency.

@raineorshine The root cause of this issue as I explained above shows that at certain cases existingThoughtDelete` can cause inconsistency between `thoughtIndex` and `contextIndex`.  

In this case `rankedThoughtsFirstMatch` gave different rank of meta thought `=view` when context view is toggled on. That rank didn't match with both `contextIndex` and `thoughtIndex` data. But interestingly `existingThoughtDelete` managed to delete it only from `thoughtIndex` causing this issue. I strongly believe that reducers like `exisitingThoughtDelete` should never behave this way even if they are provided bad input.

So I tested this issue further and I noticed this issue doesn't occur at all if we have more than one node with table view on in the tree. This really blew me away. 

1. After recreating the issue as mentioned above https://github.com/cybersemics/em/issues/521?#issuecomment-610935239 , clear the application data.

2. Now create following structure.

- A
  - B
- C (table view on)
  - D

3. Now try recreating the issue . Select thought **A** , Toggle on Table view , toggle on Context View and then toggle off Table view again.

Previously table view toggle stopped working. But with another table view on in the tree , this issue doesn't occur at all.

After looking into logic of `exisitingThoughtDelete` I found the potential cause.

https://github.com/cybersemics/em/blob/a72f439f055cddea27ae2c9234f3ce2292c3d1f0/src/reducers/existingThoughtDelete.js#L47-L57

As you can here rank check of the thought is being completely ignored when `thought.contexts.length` is less than 1. And that specific thought is straight away deleted from the `thoughtIndex` without making sure if that specific thought was valid in the `contextIndex`. So provided thoughts with bad rank, `exisitingThoughtDelete` causes inconsistency. 

Removing that specific condition of `thought.contexts.length > 1` solves this issue. But I don't know if that logic was implemented for specific cause. Please let me know what you think about this!

**Comment by raineorshine** [comment]
One step closer to eliminating `thoughtIndex`/`contextIndex` issues! Nice work.

> In this case `rankedThoughtsFirstMatch` gave different rank of meta thought `=view` when context view is toggled on. That rank didn't match with both `contextIndex` and `thoughtIndex` data. But interestingly `existingThoughtDelete` managed to delete it only from `thoughtIndex` causing this issue. I strongly believe that reducers like `exisitingThoughtDelete` should never behave this way even if they are provided bad input.

Yes, I wholeheartedly agree! Do you think you could investigate why `rankedThoughtsFirstMatch` returns the incorrect rank?

> So I tested this issue further and I noticed this issue doesn't occur at all if we have more than one node with table view on in the tree. This really blew me away.

Yes, how odd.

> As you can see here rank check of the thought is being completely ignored when `thought.contexts.length` is less than 1. And that specific thought is straight away deleted from the `thoughtIndex` without making sure if that specific thought was valid in the `contextIndex`. 

Actually, it deletes the thought directly when `thought.contexts.length <= 1`. This is correct: If a thought exists in multiple contexts (> 1), it should be removed from the current context. If a thought exists in a single context (<= 1), it should be removed from the `thoughtIndex` completely.

> So provided thoughts with bad rank, `exisitingThoughtDelete` causes inconsistency.

Yes, exactly. It's the bad rank that's the problem.

> Removing that specific condition of `thought.contexts.length > 1` solves this issue. But I don't know if that logic was implemented for specific cause. Please let me know what you think about this!

That condition is needed, as described above, but it wouldn't hurt to have a check in place that ensures the rank is valid.

**Comment by shresthabijay** [comment]
> Do you think you could investigate why `rankedThoughtsFirstMatch` returns the incorrect rank?

Sure! I will do that.

**Comment by shresthabijay** [comment]
> That condition is needed, as described above, but it wouldn't hurt to have a check in place that ensures the rank is valid.

For now I will keep the rank check in place and continue investigating `rankedThoughtsFirstMatch`.
