### ISSUE TITLE
Copy/Paste Issue on a thought

### ISSUE THREAD

**Issue by wwwdevpro** [cybersemics/em#529]
**Step to reproduce**
- Create a thought
- try to copy/paste some info within the thought

**Current behaviour**
when try to copy/paste an emoticon or any letter or any word, it creates new thought in the same column instead pasting in the place.

**Expected behaviour**
the info you're going to paste should be inserted at the current position of cursor.

**Comment by raineorshine** [comment]
Does this only occur in the table view? Or only for certain text?

I am able to paste single lines of text correctly.
