### ISSUE TITLE
Scaled text gets cut off at bottom

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#536]
When font size is increased (`scaleSize > 1`) and there are many (50-100) thoughts in the root, then they get cut off at the bottom of the window. The `<Scale>` element gets scaled but `<body>` doesn’t scale to fit. If we know the `scaleSize`, can we add the requisite padding-bottom without having to read the element height from the DOM?

@edsonayllon Could you take a look at this? I didn’t catch this bug in the original PR. 

See: https://stackoverflow.com/questions/34474826/how-to-fit-html-parent-elements-bounding-box-to-a-css-transformed-child

Related: #223

**Comment by edsonayllon** [comment]
I'll take a look at it.
