### ISSUE TITLE
Correctly position sorted drop hover

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#538]
When a thought is dragged over any of the subthoughts of a sorted context, the drop hover (blue line) should be shown at the sorted drop location. 

Currently the drop hover position is misleading. It should instead be positioned at the point where the dragged thought will be sorted to.

**Comment by incora-dev** [comment]
@raineorshine Estimate: 2.5h

**Comment by raineorshine** [comment]
@incora-dev This is a challenging one. If you want to take this on, I ask for a written description of your proposed solution before you begin implementing it. 2-3 hours for the proposal and 4-6 hours total.

**Comment by incora-dev** [comment]
@raineorshine I've investigated a bit current functionality and looks like we need adjust current condition `globals.simulateDropHover || isHovering` based on sort is enabled or not.

**Comment by raineorshine** [comment]
Thanks! I will need a bit more of a plan before proceeding to implementation.

- The current `isHovering` boolean is set to `monitor.isOver({ shallow: true }) && monitor.canDrop()`. How will the new condition be determined? i.e. How will you determine when to show the `drop-hover`, and how will you determine which `drop-hover` to show?
- There are three different `drop-hover` elements. Which ones will be used? Will they have the same conditions?

**Comment by incora-dev** [comment]
- If sorting is disabled current `isHovering` variable will be used. Else `isHovering` should check if mouse is over parent (or root) thought and then check if draggable thought is alphabetically next after current thought.
- All three will be used. I think they should have the same conditions (at least very similar).

**Comment by raineorshine** [comment]
Great, what is your time estimate?

> * If sorting is disabled current `isHovering` variable will be used. Else `isHovering` should check if mouse is over parent (or root) thought and then check if draggable thought is alphabetically next after current thought.

That sounds good. It will need to specifically exclude (return `false`) older ancestors, as they will technically be under the mouse cursor.

> * All three will be used. I think they should have the same conditions (at least very similar).

Okay, makes sense.

**Comment by incora-dev** [comment]
@raineorshine I think it will take 3-4 hours.
