### ISSUE TITLE
Sort empty thought to top 

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#539]
Empty thought should always be sorted to top in sorted context. Currently it is sorted after thoughts that start with certain punctuation e.g. `*`

e.g. 

- My Sorted Context
  - `*`
  - [New Thought]
  - A
  - B

**Comment by incora-dev** [comment]
@raineorshine Estimate: 1.5h

**Comment by raineorshine** [comment]
@incora-dev This is already assigned to another developer.
