### ISSUE TITLE
Preserve formatting

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#542]
`<b>`, `<i>`, and `<u>` should be preserved when a thought is edited. It is being stripped as soon as the thought is re-rendered. 

I recommend searching for all calls to `strip` and find the one that is not passing `preserveFormatting` that should be. Note that there are some components like `Breadcrumbs` that are supposed to strip formatting.

**Comment by incora-dev** [comment]
Estimate: 3.5h

**Comment by raineorshine** [comment]
@incora-dev I will start by budgeting 1 hour for this. It may be as simple as just adding `preserveFormatting` to a single call. If you spend an hour and are not able to fix it because the solution is more involved, then you can explain what you have found, what the proposed solution is, and how long it will take, and I will consider adding more hours.
