### ISSUE TITLE
Mobile Safari: Toolbar disappears when keyboard is up

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#545]
Toolbar should be position: fixed and always visible.

**Comment by pushkov-fedor** [comment]
I tried it on Android with Chome and toolbar was visible. Maybe it's only Safari problem?

**Comment by raineorshine** [comment]
Appears so. Thanks for testing on Android.

**Comment by pushkov-fedor** [comment]
I found this article https://medium.com/@im_rahul/safari-and-position-fixed-978122be5f29. It describes the same problem that we have. 
This issue shouldn't be difficult, 1-1.5hrs

**Comment by raineorshine** [comment]
Sure, thanks. The hardcoded height seems really fragile. Make sure to do some research in case there is another solution or a way to make it more robust.
