### ISSUE TITLE
Fix ArrowUp/ArrowDown in multi-line thought

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#550]
## Current Behavior
When the browser selection is on the second or greater line of a multi-line thought, hitting `ArrowUp` moves the selection to the previous thought.

## Expected Behavior
Hitting `ArrowUp` should move the selection up one line (default browser behavior).

e.g.

```
- This is a thought that
  is no|w wrapping.
```

Hitting `ArrowUp` should result in:

```
- This |is a thought that
  is now wrapping.
```

The inverse behavior should occur for `ArrowDown`.

**Comment by incora-dev** [comment]
@raineorshine 2h
