### ISSUE TITLE
Split and combine shortcuts

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#56]
- Split each shortcut in `shortcuts.js` into a separate file.
- Use the following code to avoid a separate import for each file.
- Combine all shortcuts to restore the original functionality.

```js
const req = require.context('./', true, /.js$/);
const modules = req.keys().map(req);
```
(https://stackoverflow.com/a/57009738/480608)

**Comment by gutofoletto** [comment]
Hey! Can I tackle this one as well?

**Comment by gutofoletto** [comment]
Just started it and got a bit confused...
Do you want to 
 - split all the functions inside `shortcuts.js` into different files 
or 
- split the objects (that represent shortcuts) inside `globalShortcuts` into different files
?

**Comment by raineorshine** [comment]
> split the objects (that represent shortcuts) inside globalShortcuts into different files

That one! Move each of these into their own dedicated file in a `shortcuts` folder:

```js
  {
    id: 'newSubthought',
    name: 'New Subhought',
    description: 'Create a new subthought in the current thought. Add it to the bottom of any existing subthoughts.',
    gesture: 'rdr',
    exec: () => newItem({ insertNewChild: true })
  }
```
