### ISSUE TITLE
Cursor is set to unmounted thought (Context View) 

### ISSUE THREAD

**Issue by shresthabijay** [cybersemics/em#568]
## Steps to Reproduce

**Note**: Be sure that duplication error #551 has been been fixed. Otherwise you will run into that issue first. Also they are both independent issues. 

- a
  - m
    - x
- b
  - m

1. Create the above thought structure
2. Select `a.m` and activate Context View.
3. Select `a.m~.a`
4. Hit `ArrowDown` (Focus still remains at `a` and it collapses unmouting `x`)
6. Hit `Add Subthought` shortcut.

## Current Behavior
It throws Uncaught TypeError: Cannot read property 'context' of undefined. It is because when arrow down is used focus still remains in thought `a` but cursor is set at thought `x` which is already unmounted. 

![chrome-capture (9)](https://user-images.githubusercontent.com/25879100/79633960-68615a00-8187-11ea-9b4c-2ac3fd9ef9ab.gif)

## Expected Behavior
On hitting arrow down it should go to thought `x` and cursor should sync properly.

**Comment by pushkov-fedor** [comment]
I've tested it on Chrome, it works as expected.

**Comment by raineorshine** [comment]
Great, thanks for confirming!
