### ISSUE TITLE
Split and combine reducers

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#57]
- Split each reducer in `store.js` into a separate file.
- Use the following code to avoid a separate import for each file.
- Combine all reducers to restore the original functionality of the main app reducer.

```js
const req = require.context('./', true, /.js$/);
const modules = req.keys().map(req);
```
(https://stackoverflow.com/a/57009738/480608)

**Comment by miladkdz** [comment]
Can I take this issue?

**Comment by raineorshine** [comment]
@miladkdz Any update? Thanks!
