### ISSUE TITLE
Cursor Duplication in context view

### ISSUE THREAD

**Issue by anmolarora1** [cybersemics/em#590]
For thoughts with a similar tree structure, the `setCursor` action in the context view doesn't seem to work for the contexts of children at second or subsequent levels of the tree. Clicking on one context focuses on all the contexts with a similar structure. 
Here's an example -

![cursor-duplication_contextView](https://user-images.githubusercontent.com/7765764/80104997-3df11180-8578-11ea-8728-f725afdf11e8.gif)

**Comment by raineorshine** [comment]
Minimal test case:

```
  - a
    - x
      - y
  - b
    - x
      - y
```

Activate context view on `y` and select child.

**Comment by pushkov-fedor** [comment]
I think we just need to add some check in `setCursor`. I've worked with Context VIew recently and would like to pick this one. What about 3-4 hours?

**Comment by raineorshine** [comment]
Yes, thanks!

However my guess is that it's not `setCursor` that is the problem. The `cursor` is probably correct. It's probably the logic in the component that determines if the bullet overlay is rendered.
