### ISSUE TITLE
Fade out toolbar and breadcrumbs

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#605]
On desktop when the user starts typing, fade out the toolbar and breadcrumbs (800ms, ease-in-out).

When the user moves their mouse, fade them back in.

This mimics the behavior in Notion.

**Comment by pushkov-fedor** [comment]
Tried it on Notion, this behavior looks really cool. I would like to take this issue. I think it's 1-1.5 hour with development and testing.

**Comment by raineorshine** [comment]
@anmolarora1 claimed this just before you, I just hadn't updated the issue yet! Thank you, though.

I agree it's a slick feature.
