### ISSUE TITLE
Toolbar does not expand fully on desktop

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#608]
<img width="767" alt="Screen Shot 2020-04-29 at 7 32 33 AM" src="https://user-images.githubusercontent.com/750276/80602221-140e7380-89ec-11ea-994e-7ff813b17efe.png">

## Steps to Reproduce

Open **em** in a window about 700px wide or more.

## Expected Behavior

Toolbar should expand to its full width and not have any scroll bars.

## Current Behavior

Toolbar container width is smaller than content, causing scrollbars to appear.

## Notes

Important to test that the fix does not introduce regressions at any device size.

**Comment by pushkov-fedor** [comment]
This task could be a bit tricky and needs time to understand current scroll/resize logic inside Toolbar and test expected behavior on any screen size.  What about 2-2.5 hours for development and 1 extra hour for tests and fixes?

**Comment by raineorshine** [comment]
This was the other issue that @anmolarora1 claimed, but he's going to be working on the Typescript conversion, so maybe he can hand this off to you.
