### ISSUE TITLE
External link not clickable

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#620]
When you enter a url as a thought, the url icon should open the url in a new tab. 

I think this is a z-index issue. Make sure that metaprogramming attributes (eg `=test`) still have their background color.

**Comment by pushkov-fedor** [comment]
I think it takes 0.5-1 hour. But i don't understand what you mean by metaprogramming attributes and their background. Can you clarify this please?

**Comment by raineorshine** [comment]
Absolutely! Not an obvious connection 😄

Metaprogramming attributes are thoughts that start with `=`. The [background color is assigned](https://github.com/cybersemics/em/blob/dev/src/App.css#L2602) via the ThoughtAnnotation component. ThoughtAnnotation has to have a lower z-index than Editable, but the link icon, which is inside ThoughtAnnotation, has to have a higher z-index than Editable in order to clickable.

Looking for line numbers in the code to show you I accidentally ended up fixing the issue 😊.
