### ISSUE TITLE
Note button should move selection from note to cursor

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#633]
When the browser selection is on a note, clicking the "Note" button in the toolbar should move the browser selection to the end of the `cursor` thought. Currently it moves to the end of the note.

It works correctly when the keyboard shortcut for "Note" is used, just not clicking the button.

**Comment by raineorshine** [comment]
Created this as a separate issue from #600 since it was already broken on `dev`.

**Comment by pushkov-fedor** [comment]
When Note is in focus, click on the "Note" button should set focus on the end of Thought, am i right?

**Comment by raineorshine** [comment]
Yes, that's right.
