### ISSUE TITLE
Home link not working

### ISSUE THREAD

**Issue by shresthabijay** [cybersemics/em#648]
`TypeError: getState is not a function`

https://github.com/cybersemics/em/blob/a72f439f055cddea27ae2c9234f3ce2292c3d1f0/src/components/HomeLink.js#L24-L35

@raineorshine  The second argument of `mapDispatchToProps` is `ownProps` not `getState` function. `getState` is accessible as second argument of action creator.

Either create action creator like this or just use `store.getState()`.

```javascript
const goHomeActionCreator = () =>
  (dispatch, getState) => {
    if (getState().search != null) {
      dispatch({ type: 'search', value: null })
      restoreCursorBeforeSearch()
    }
    else {
      home()
    }
  }

const mapDispatchToProps = dispatch => ({
  goHome: e => {
    e.preventDefault()
    dispatch(goHomeActionCreator())
  }
})

```

**Comment by raineorshine** [comment]
Got it, thanks!
