### ISSUE TITLE
Mobile: Selecting text activates gesture

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#676]
While dragging the ends of the selected text on mobile, gestures should not be activated. 

This was working correctly before, so start by identifying the commit that caused the regression.

**Comment by shresthabijay** [comment]
@raineorshine Do you mean dragging text selection inside input ? Or is it dragging over current thought ? It would be helpful if you could provide a small clip or gif of this issue.

**Comment by raineorshine** [comment]
Sure! https://youtu.be/rKQaS8snt1k

This shows the issue a few different times, incorrectly triggering `cursorBack` and `cursorForward`.

**Comment by shresthabijay** [comment]
https://drive.google.com/file/d/1PkhNH68UlBQTkuvIQLUqSG1sT3kSQuKa/view?usp=drivesdk

@raineorshine It's not happening in my device. I think its browser specific.

**Comment by raineorshine** [comment]
In your video, it looks like you moved back and forth several times, generating a →←→←→←→  which is not a valid gesture. Does it also not occur when you make only the gesture →← while dragging the selection on a subthought?

**Comment by shresthabijay** [comment]
> Does it also not occur when you make only the gesture →← while dragging the selection on a subthought?

I have tried it. It doesn't occur at all.

**Comment by raineorshine** [comment]
Okay, thanks for trying!

**Comment by raineorshine** [comment]
Tried to find the regression all the way back to [v80.0.0](eccce1632c83b10429d0ec898f9b583a76eca940), but even that is not working. There's no way it has been broken since then. I just noticed it last week. I wonder if it was a Mobile Safari update...?
