### ISSUE TITLE
Replace formatNumber with toLocaleString

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#682]
https://github.com/cybersemics/em/pull/656#pullrequestreview-416858140

**Comment by anmolarora1** [comment]
The current function doesn't seem to have a handler for non-numbers. 
`formatNumber('abcdef')` returns `abc,def`

Now that we're refactoring it, we might want to fix that. How should the function handle such (non-number) inputs?

**Comment by raineorshine** [comment]
> Now that we're refactoring it, we might want to fix that. How should the function handle such (non-number) inputs?

What do you recommend? I always like to hear your idea first, unless you're truly stumped.

**Comment by anmolarora1** [comment]
> > Now that we're refactoring it, we might want to fix that. How should the function handle such (non-number) inputs?
> 
> What do you recommend? I always like to hear your idea first, unless you're truly stumped.


Based on it's [ existing usage](https://github.com/cybersemics/em/blob/ce23b78d26f9c8e9f10c020c53de863b8027ef45/src/components/SearchSubthoughts.js#L89), I'd suggest we should ignore `invalid/NAN` inputs and return `0` in such cases.

**Comment by raineorshine** [comment]
Okay, that's an option. I'm a little concerned that that might allow some invalid usage to slip through. Wouldn't it be better to return `null` or throw an error?

**Comment by anmolarora1** [comment]
Initially, I thought of the same options. Throwing an error or returning
null would require explicit handling by the caller.
Unless it deviates from the business requirements, a more appropriate way
would be to ensure that the input to this function is only number(can be
done using TS) as it's responsibility is to format the number.
If we need the function to work for strings, we can add some logic for that
too using TS.

**Comment by raineorshine** [comment]
Makes sense that it should only accept `number`.
