### ISSUE TITLE
Insert space when pasting into non-empty thought

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#72]
Because whitespace is trimmed from the beginning and end of all thoughts, pasting (non-multi-line) text to the end of an item being edited unintentionally collapses the space.

When text *with no leading whitespace* is pasted into a *non-empty* thought, add an intervening space.

See: `importText` in `util.js`

**Comment by miladkdz** [comment]
I’ll take this one too.

**Comment by raineorshine** [comment]
In progress: #91

**Comment by raineorshine** [comment]
@esandez93 There is a small bug still. When pasting at the beginning of a line, it inserts the space at the beginning when it should insert it after `newText`. Would you like to fix this?

**Comment by esandez93** [comment]
@raineorshine Yes, for sure! This week I won't be a le able, though. Maybe in the weekend or the next week, is that OK?

**Comment by raineorshine** [comment]
@esandez93 Yes, no problem! Thanks!
