### ISSUE TITLE
Ancestor drop target incorrectly highlighted

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#727]
## Steps to Reproduce

- a
  - b
    - c

1. Sort `a`
2. Drag `b` over `c`

## Current Behavior

Drop target above `b` is incorrectly highlighted.

## Expected Behavior

No drop target should be highlighted since `b` cannot be dragged to its descendants. It should be the same behavior as an unsorted context.

**Comment by incora-dev** [comment]
@raineorshine Here I've found an issue when we drag some item to descendants of sorted thought. Then some child of sorted thought is highlighted. Looks like I've found solution already but still working on it.

**Comment by shresthabijay** [comment]
> 2\. Drag `b` over `c`

@raineorshine I think it should Drag `a` over `b` since `a` is the sorted thought.

**Comment by raineorshine** [comment]
> > 2. Drag `b` over `c`
> 
> @raineorshine I think it should be Drag `a` over `b`.

No, the steps listed are correct. That may be a separate issue.
