### ISSUE TITLE
Quick Add

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#749]
This task adds a "Quick Add" feature to quickly add a thought to **em**. It renders and adds new thoughts to a unique `[ABSOLUTE]` context which represents no context.

- Add a plus icon with `position: fixed` in the bottom right corner. Find a suitable svg icon from nounproject.com.
- Define `const ABSOLUTE = '__ABSOLUTE__'` in [constants.ts](https://github.com/cybersemics/em/blob/dev/src/constants.ts). This represents a context whose children do not appear in any other context. (We need to represent an absolute "no context" as an actual context in order to allow O(1) lookup of children.)
- Add `state.startingContext: [ROOT_TOKEN]` to track the starting context of the Content component. Replace the [hardcoded `[ROOT_TOKEN]` value in the Content component](https://github.com/cybersemics/em/blob/dev/src/components/Content.tsx#L40) with `state.startingContext`. 
- **When the icon is clicked, show thoughts that have no context and were created after the icon is clicked**. Click the icon to set `startingContext` to `[ABSOLUTE]`. Add a condition to the calculation of `rootThoughts` in the Content component: if `startingContext` is `[ABSOLUTE]`, then filter the `rootChildren` by `child.created > t` where `t` is the time when the icon is clicked. Thus it will initially be empty until the user creates a new thought.
- Editing any child at the top level should save it to the `[ABSOLUTE]` context.
- Editing and navigating below the top level should function as normal.
- Add a `quickAdd` shortcut that has the same effect as clicking the icon. Its keyboard shortcut should be `Alt + n`.

- **Faster way back than Recently Edited:** When Quick Add is activated, save the `cursor` in `cursorBeforeQuickAdd` which functions just like `cursorBeforeSearch`. i.e. When `startingContext` is `[ABSOLUTE]`, there is no `cursor`, and the user activates `cursorBack`, reset `startingContext` to `[ROOT]` and restore `cursor` to `cursorBeforeQuickAdd`  This should go in the same place as the `cursorBeforeSearchLogic`. 
- **Faster new thought:** Render an empty thought and set the browser selection when Quick Add is activated. Do not save it to state until the user starts typing.

**Comment by shresthabijay** [comment]
@raineorshine absolute rendering uses same `Subthought` component but with filter on and starting from ABSOLUTE context instead of ROOT_TOKEN. Is that right ?

**Comment by raineorshine** [comment]
> * absolute rendering uses same `Subthought` component but with filter on and starting from ABSOLUTE context instead of ROOT_TOKEN. Is that right ?

Yes, exactly. I didn't realize that `Subthoughts` did not use `rootThoughts`. Maybe a `filter` attribute should be added to the component? What do you think?

> * > * When the icon is clicked, show thoughts that have no context and were created after the icon is clicked
>   So how do we view thoughts with no context that were created before ?

They will be accessible from the Recently Edited. However we should probably have a way to view them all. Maybe a button in the toolbar? Or an option in the Search View?

**Comment by shresthabijay** [comment]
> Maybe a `filter` attribute should be added to the component? What do you think?

Yes. We should pass a `filter` attribute to `Subthought` component. Then we can just filter based on time icon is clicked. Everything else will just the same.

**Comment by shresthabijay** [comment]
> They will be accessible from the Recently Edited. However we should probably have a way to view them all. Maybe a button in the toolbar? Or an option in the Search View?

Can you explain the necessity of this feature briefly ? I would be able to give proper feedback if I understand use of this feature.

**Comment by shresthabijay** [comment]
![Screen Capture_select-area_20200715174311](https://user-images.githubusercontent.com/25879100/87542512-c5a37380-c6c2-11ea-8ca4-86b1a1a9a4bb.gif)

@raineorshine  I tried something like this. The plus icon will toggle the `startingContext`  between `ABSOLUTE` and `ROOT_TOKEN`. If `ABSOLUTE` context is active then plus icon will rotate to become a cross icon which on click will toggle `startingContext` back to `ROOT_TOKEN`. We need ability to toggle filter on absolute context on and off. So another view icon will show up when `startingContext` is set as `ABSOLUTE` and disappear on toggle. What do you think ?

**Comment by raineorshine** [comment]
> > They will be accessible from the Recently Edited. However we should probably have a way to view them all. Maybe a button in the toolbar? Or an option in the Search View?
> 
> Can you explain the necessity of this feature briefly ? I would be able to give proper feedback if I understand use of this feature.

Sure, I would be happy to. To clarify, are you asking about the necessity of the Quick Add feature, or the necessity of the View All Thoughts Without A Context feature?

> @raineorshine I tried something like this. The plus icon will toggle the `startingContext` between `ABSOLUTE` and `ROOT_TOKEN`. If `ABSOLUTE` context is active then plus icon will rotate to become a cross icon which on click will toggle `startingContext` back to `ROOT_TOKEN`. We need ability to toggle filter on absolute context on and off. So another view icon will show up when `startingContext` is set as `ABSOLUTE` and disappear on toggle. What do you think ?

Thank you, this is interesting! Let me think about this some more. I think I am getting closer to being able to articulate the desired relationship between creation and filtering.

**Comment by raineorshine** [comment]
I’ve considered several different options but I’m not landing on a final design. I need to use Quick Add for a bit to get a feel for how it works. 

In the mean time, please implement it as originally described, with no way to turn off the filter. The only difference is the following:

- **Faster way back than Recently Edited:** When Quick Add is activated, save the `cursor` in `cursorBeforeQuickAdd` which functions just like `cursorBeforeSearch`. i.e. When `startingContext` is `[ABSOLUTE]`, there is no `cursor`, and the user activates `cursorBack`, reset `startingContext` to `[ROOT]` and restore `cursor` to `cursorBeforeQuickAdd`  This should go in the same place as the `cursorBeforeSearchLogic`. 
- **Faster new thought:** Render an empty thought and set the browser selection when Quick Add is activated. Do not save it to state until the user starts typing.

**Comment by shresthabijay** [comment]
@raineorshine  Since the root can either be `__ABSOLUTE__`  or `__ROOT__`, we may need to generate `RANKED_ROOT` based on the which `startingContext` is active. For example in `expandThoughts` we need to expand path [{ value: '__ABSOLUTE__', rank: 0 }]  instead of [{ value: '__ROOT__', rank: 0 }] when `startingContext` has absolute token.

**Comment by raineorshine** [comment]
> @raineorshine Since the root can either be `__ABSOLUTE__` or `__ROOT__`, we may need to generate `RANKED_ROOT` based on the which `startingContext` is active. 

Yes, we may need to do this since we cannot always assume that the rendered root is `ROOT_TOKEN`. There may be places in the code that make this assumption.

> For example in `expandThoughts` we need to expand path `[{ value: '__ABSOLUTE__', rank: 0 }]` instead of `[{ value: '__ROOT__', rank: 0 }]` when `startingContext` has absolute token.

`expandThoughts` only uses `RANKED_ROOT` when the `path` is `null` or `[]`, so as long as the `path` begins with `[{ value: '__ABSOLUTE__', rank: 0 }]` I don't see `expandThoughts` changing, unless I am missing something.

**Comment by shresthabijay** [comment]
> `expandThoughts` only uses `RANKED_ROOT` when the `path` is `null` or `[]`, so as long as the `path` begins with `[{ value: '__ABSOLUTE__', rank: 0 }]` I don't see `expandThoughts` changing, unless I am missing something.

When cursor back is triggered cursor gets set to null at last. So we need to provide proper `RANKED_ROOT` when `path` is `null` based on the starting context else the `ABSOLUTE` context won't expand.

**Comment by raineorshine** [comment]
I see, that's right. When `cursor` is `null`, we have to expand from the `startingContext` because the `cursor` does not have the information any more.

**Comment by shresthabijay** [comment]
@raineorshine I have started implementing the feature. I want your input on few things. First of all we have lot of utils that depends on `ROOT_TOKEN` and `RANKED_ROOT`. Since now absolute is a root too and all the functionalities are same as normal, so how should we change the implementation of `isRoot`. In my opinion `isRoot` should return true for both `ROOT_TOKEN` and `ABSOLUTE_ROOT`.  Also in many places we default to `RANKED_ROOT` if `state.cursor` is null. For example in `newThought` reducer, we should do this.

```javascript
const path = at || state.cursor || getRoot(state)
```

Since `ABSOLUTE_RANKED_ROOT` and `RANKED_ROOT` are both legit ranked roots, so `getRoot` selector should return proper ranked root depending on `state.startingContext`.

What do you think ?

**Comment by raineorshine** [comment]
> I have started implementing the feature. I want your input on few things. First of all we have lot of utils that depends on `ROOT_TOKEN` and `RANKED_ROOT`. Since now absolute is a root too and all the functionalities are same as normal, so how should we change the implementation of `isRoot`.

Yeah, this is a bit of a scary change :). The `ROOT` context is ubiquitous. That said, it's not a bad idea for us to decouple the concept of the ROOT context from the start context. `RANKED_ROOT` is often used as a default for a `path`, which in some cases will still be correct (e.g. `ExportModal`). However anything that needs to refer to the start context of the current "view mode" rather than the ROOT context specifically will need to handle ROOT and ABSOLUTE.

> In my opinion `isRoot` should return true for both `ROOT_TOKEN` and `ABSOLUTE_ROOT`.

I agree.

We could rename `isRoot` to `isStartContext` and ROOT will continue to refer specifically to the `[ROOT_TOKEN]` context. Or we could rename ROOT to HOME and use the word ROOT to refer to the root context of the current view mode. What do you think?

> Also in many places we default to `RANKED_ROOT` if `state.cursor` is null.

Yes, but be cautious as some places (like export) should always default to `RANKED_ROOT`.

> Since `ABSOLUTE_RANKED_ROOT` and `RANKED_ROOT` are both legit ranked roots, so `getRoot` selector should return proper ranked root depending on `state.startingContext`.

Yes, I agree.

In this case it sounds like you are using ROOT to refer to the starting context, regardless of whether it is ABSOLUTE or the currently named `RANKED_ROOT`. As mentioned above, we should nail down our desired semantics for consistency.

**Comment by raineorshine** [comment]
On a related note, I believe it was a mistake to use, for example, `['a']` as shorthand for `[ROOT_TOKEN, 'a']`. Fixing this would be an extensive change however, and should probably be relegated to a separate issue.

**Comment by shresthabijay** [comment]
@raineorshine What would be the appropriate naming for `rootedParentOf` selector that returns either ranked root or absolute ranked root based on `startingContext` ? Also for `unroot` ?

**Comment by raineorshine** [comment]
> @raineorshine What would be the appropriate naming for `rootedParentOf` selector that returns either ranked root or absolute ranked root based on `startingContext` ? Also for `unroot` ?

I see two overall approaches, which I summed up above:

> We could rename isRoot to isStartContext and ROOT will continue to refer specifically to the [ROOT_TOKEN] context. Or we could rename ROOT to HOME and use the word ROOT to refer to the root context of the current view mode. 

Given the way both of us having been using the word "root", it seems like we should define "root" to mean the earliest context of the current view mode, rather than to a specific home context. Thus, I would suggest the following:

- `ROOT_TOKEN` → `HOME_TOKEN`
- `RANKED_ROOT` → `HOME_PATH`
- `startingContext` → `rootContext`
- `rootedParentOf` → support both HOME and ABSOLUTE
- `isRoot` → return true for both HOME and ABSOLUTE
- `isHome` → return true for HOME
- `removeRoot` → `removeHome` (I think this should only be needed for HOME)
- `unroot` → support both HOME and ABSOLUTE

Does that align with your intuitions? Consistent semantics is an important skill for large-scale architecture and API design, so I'm glad we're discussing this.

**Comment by shresthabijay** [comment]
> Does that align with your intuitions? Consistent semantics is an important skill for large-scale architecture and API design, so I'm glad we're discussing this.

Yes. That's much cleaner and understandable.

**Comment by raineorshine** [comment]
Great! I look forward to the next time when you break it down for me 😉😁
