### ISSUE TITLE
Search gets trimmed during editing

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#751]
Seems to be caused by the search editable being re-rendered during editing.

**Comment by shresthabijay** [comment]
@raineorshine Can you provide a screenshot for this ?

**Comment by raineorshine** [comment]
Sure! I'll give exact steps to reproduce, as visually it's hard to see what the issue is.

## Steps to Reproduce

1. Activate Search
2. Quickly type "a " (`a` followed by space)

## Current Behavior

The trailing space gets removed. This is normal behavior for thoughts when they are blurred, but should not be done for the search editable.

## Expected Behavior

- Leading space should be trimmed
- Trailing space should never be trimmed from the editable. The editable should not be re-rendered at all during editing.
- Trailing space should be trimmed internally before the search is performed
