### ISSUE TITLE
Disallow duplicate thoughts in context 

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#764]
## Background

After using **em** for a while now, I find ~no~ little practical necessity to allow a duplicate thought in the same context. Disallowing duplicates confers the following benefits:

1. Thoughts can be indexed by the hash of their value, making lookups simpler and more efficient (`O(1)`). 
2. No duplicates better fits the conceptual model. Thoughts have no identity above and beyond their value. Two thoughts with the same value are the same thought (lexeme). 

## Exceptions
Dynamic contexts (search results, queries) may have duplicates. 

## Approach

We can make this change in two phases:

(1) Disallow duplicate thought on edit. 

~(2) Refactor Path logic. Ranks will no longer be needed to uniquely identify a thought, so `Path` can change to `Context` in most places.~ Paths may include dynamic contexts with duplicate thoughts. 

(1) is the simplest. (2) is extensive, but can be done iteratively over time. This issue is for (1). 

## Editing Behavior
1. When a change event would create a duplicate thought (i.e. when `e` is typed at the end of `Appl` when there is already a thought `Apple`):
    - `Appl` should change to `Apple` as normal, but should not be saved to state. 
    - `Apple` should be grayed out. 
    - After two seconds, an alert should should be shown that says “Duplicate thoughts are not allowed within the same context.”
2. When the duplicate is changed to a unique value, all of the above should be reversed and reset to normal.

**Comment by pushkov-fedor** [comment]
Hey, Raine! This issue looks interesting, Can i take it? 
I would like to clarify one moment. What happens after dispatching an alert? Can user edit other thoughts or we "lock" all thoughts until user edits or removes duplicate thought?  
I'm not sure about time estimation right now, but i would like to start with 3-4hrs, do as much as possible in this period and then report you about my progress. What do you think? Is is okay?

**Comment by raineorshine** [comment]
> Hey, Raine! This issue looks interesting, Can i take it?

Sure!

> I would like to clarify one moment. What happens after dispatching an alert? Can user edit other thoughts or we "lock" all thoughts until user edits or removes duplicate thought?

Great question. The user can edit as normal. The duplicate is **never actually saved**. This is the same behavior as the current `readonly` logic: https://github.com/cybersemics/em/blob/dev/src/components/Editable.tsx#L271-L278.

Try adding a `=readonly` child and edit the parent. Notice that editing is not affected at all, it just shows an error message. If the user navigates away from the thought while it is a duplicate, it will naturally convert back to the last non-duplicate value due to the re-render. This issue is very similar to that, except for two things:

1. The alert has a longer delay to avoid flashing the alert when a user "types over" an existing word during normal editing, e.g. typing "12" when "1" exists as a sibling.
2. The value should be grayed out when it is a duplicate.

> I'm not sure about time estimation right now, but i would like to start with 3-4hrs, do as much as possible in this period and then report you about my progress. What do you think? Is is okay?

I am going to cap it at 4 hours maximum. This is a relatively small change to a single file, with existing code that shows you mostly what to do. Most of the time will probably be spent understanding relevant parts in Editable.tsx.
