### ISSUE TITLE
Hit delete at beginning of only child to outdent 

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#772]
- [ ] Unit Test

When the caret is located at `offset: 0` of a thought which is the only child of a context, then hitting delete should outdent the thought. 

This provides a way to “undo” indent via space in at least some circumstances, without interfering with other commands.

**Comment by shresthabijay** [comment]
@raineorshine Do you think we should create shortcut for this ?

**Comment by raineorshine** [comment]
What do you think? I always like to hear your thinking first, along with alternative proposals and confidence levels if appropriate.

**Comment by shresthabijay** [comment]
> What do you think? I always like to hear your thinking first, along with alternative proposals and confidence levels if appropriate.

Since we are now using generic shortcuts like `enter`, we can create a shortcut for this as well. But I see there would be problem naming generic shortcuts if they have multiple keys including meta and ctrl.

**Comment by raineorshine** [comment]
> Since we are now using generic shortcuts like `enter`, we can create a shortcut for this as well. But I see there would be problem naming generic shortcuts if they have multiple keys including meta and ctrl.

We should use generic shortcuts sparingly. It's much better when a shortcut is semantically meaningful. We should only generalize for the few shortcuts that really do have widely varying split behaviors based on a condition. In fact, `enter` might be better named `newThoughtOrOutdent` so that it is not so general. I'm not eager to have shortcuts that are named simply after the input itself. Decoupling the name from the input is more flexible since it allows changing the input in the future without changing the name.

What about renaming `shortcuts/deleteEmptyThought` to `shortcuts/deleteEmptyOrOutdent`?

**Comment by shresthabijay** [comment]
> What about renaming `shortcuts/deleteEmptyThought` to `shortcuts/deleteEmptyOrOutdent`?

That would be a much better approach. However it will get messy if a shortcut has more than two actions. How likely is it that we will have such shortcuts ? Also there can be cases like `indent` can be triggered by delete pressed at beginning of the thought. So we may need to name it something like `indentOnDelete`

**Comment by raineorshine** [comment]
> > What about renaming `shortcuts/deleteEmptyThought` to `shortcuts/deleteEmptyOrOutdent`?
> 
> That would be a much better approach. However it will get messy if a shortcut has more than two actions. How likely is it that we will have such shortcuts ? 

There is a natural limit on this since highly polymorphic shortcuts would be confusing to users. In general there will be one shortcut per action. These conveniences we are creating are exceptions rather than the rule.

> Also there can be cases like `indent` can be triggered by delete pressed at beginning of the thought. So we may need to name it something like `indentOnDelete`

Not sure I follow... delete pressed at the beginning of a thought would outdent, not indent.

**Comment by raineorshine** [comment]
Just realized this should **not** be applied when the thought is empty, as that would override the expected behavior of `deleteEmptyThought`.

**Comment by shresthabijay** [comment]
> Just realized this should **not** be applied when the thought is empty, as that would override the expected behavior of `deleteEmptyThought`.

`deleteEmptyThought` gets triggered on 'Backspace'. Are we using `delete` or `Backspace` to `outdent`

**Comment by raineorshine** [comment]
`Backspace`. Sorry for the ambiguity. I'm on a Mac so my `Backspace` says `delete` and I don't have a key that deletes forward.
