### ISSUE TITLE
Replace NOOP and ID with equivalent lodash functions

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#776]

**Comment by pushkov-fedor** [comment]
What do you mean? Do you want to replace all NOOP and ID uses in all files with lodash equivalents or you want to bind lodash equivalents to current definition of NOOP and ID in order not to change current codebase?

**Comment by raineorshine** [comment]
I'm going to close this actually. The type definitions were not as clean on the lodash functions so it was causing type errors that would have required unnecessary typing refactors.
