### ISSUE TITLE
Flat Render: Move thought up/down animation

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#789]
PR: #503 
Commit: d4664475

Adjacent thoughts swap places abruptly without any animation. Their translation should be animated, like when a new thought is added or removed from a context.

![Untitled mov](https://user-images.githubusercontent.com/750276/87254793-7b13c400-c442-11ea-93cc-7fbdbc3f8aa3.gif)

```
- a
  - b
  - c
```

**Comment by shresthabijay** [comment]
@raineorshine I think to achieve this we would need relative positioning.
