### ISSUE TITLE
Remove the setCursor action on new thought creation

### ISSUE THREAD

**Issue by anmolarora1** [cybersemics/em#814]
## Current Behavior

When a new thought is created by pressing the enter key, the actions `newThought` and `setCursor` are being dispatched. The `setCursor` is a gratuitous action that updates the `dataNonce`, which is already being updated by the former action.

## Expected Behavior

The `setCursor` action shouldn't be dispatched on the creation of a new thought.

**Comment by raineorshine** [comment]
I think we still need to call `setCursor`, otherwise the `cursor` will not be set properly, but we need to call it directly within the reducer flow rather than dispatching a separate action for it.

**Comment by raineorshine** [comment]
@anmolarora1 Have you started work on this or should I leave it open for anyone to grab?

**Comment by anmolarora1** [comment]
> @anmolarora1 Have you started work on this or should I leave it open for anyone to grab?

I've started working on this

**Comment by anmolarora1** [comment]
> I think we still need to call `setCursor`, otherwise the `cursor` will not be set properly, but we need to call it directly within the reducer flow rather than dispatching a separate action for it.

The only thing that's being changed in this case is the `datanonce`. And that seems like an overhead because it's being changed by the preceding action - `newThought` as well

**Comment by raineorshine** [comment]
Could you test if #828 solves the issue? Thanks!

**Comment by anmolarora1** [comment]
> Could you test if #828 solves the issue? Thanks!

@raineorshine This code prevents the extra `setCursor` action and we can safely remove [this code](https://github.com/cybersemics/em/commit/e81e66994cf9f0e7be742cbe89a592b1abbbe580#diff-e60c5e4ff2b203d85c2fbac345b56bdd73231a29ab28ac0426e0a7bccd37b680R506-R511) that was added to prevent extraneous patches (something that the `setCursor` that followed every `newThought`, was adding).

We won't be able to replicate the issue even if we remove both these sections of codes because of [this function](https://github.com/cybersemics/em/pull/811/files#diff-5960ad3f7ae66b2cf4fe0c26124db0f09db7a416862b1a7ac3fb2fe25067300eR18-R20) which was added to the `undoRedoReducerEnhancer` to combine such extraneous patches that just updated the `/dataNonce` 

That said, though, I still believe that we shouldn't have any futile actions so let's keep #828 if you think that's a better way of handling it.

**Comment by raineorshine** [comment]
Great! Thanks so much for confirming.
