### ISSUE TITLE
Edit after merge siblings broken

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#816]
## Steps to Reproduce

- a
  - b
  - |c

1. Hit Backspace to merge `b` and `c`
2. Type `d` to edit
3. Hit Escape or Up

## Current Behavior

`a/bdc` is never saved and reverts to `a/bc` as soon as the cursor moves.

## Expected Behavior

`a/bdc` should be saved and editing should work as normal after merging siblings.

## Note

`editingValue` is dispatched but not `existingThoughtChange`.

**Comment by pushkov-fedor** [comment]
I think, we just need to investigate `onChangeHandler` and `thoughtChangeHandler` in Editable components. 3hrs

**Comment by raineorshine** [comment]
@shresthabijay Could you take a look at this when you get a chance? @pushkov-fedor is working on other issues right now. This is fairly high priority since it has a big impact on (my personal) editing experience. Thanks!
