### ISSUE TITLE
Child with same value as parent breaks cursor

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#824]
## Steps to Reproduce

1. Create thought `a`
2. Create subthought `ab` (by typing `a` then `b`)

## Current Behavior

`cursor` becomes `[{ value: 'ab', rank: 0 }, { value: 'ab', rank: 0 }]`

## Expected Behavior

`cursor` should be `[{ value: 'a', rank: 0 }, { value: 'ab', rank: 0 }]`

## Notes

When the ranks differ, the problem does not occur:

- a
  - x
  - a

1. Create thought `a`
2. Create subthought of `a`: `x`
3. Create subthought of `a`: `a`
4. Edit `/a/a` to `/a/ab`

This will correctly result in `cursor: [{ value: 'a', rank: 0 }, { value: 'ab', rank: 1 }]`

**Comment by raineorshine** [comment]
Test to add to `/src/reducers/__tests__/existingThoughtChange.js`:

```js
it('edit a child with the same value as its parent', () => {

  const steps = [
    newThought({ value: 'a' }),
    newThought({ value: 'a', insertNewSubthought: true }),
    existingThoughtChange({
      newValue: 'ab',
      oldValue: 'a',
      context: ['a'],
      thoughtsRanked: [{ value: 'a', rank: 0 }, { value: 'a', rank: 0 }]
    })
  ]

  // run steps through reducer flow and export as plaintext for readable test
  const stateNew = reducerFlow(steps)(initialState())
  const exported = exportContext(stateNew, [ROOT_TOKEN], 'text/plaintext')

  expect(exported).toBe(`- ${ROOT_TOKEN}
  - a
    - ab`)

  // ab should exist in context a
  expect(getContexts(stateNew, 'ab'))
    .toMatchObject([{
      context: ['a'],
      rank: 0,
    }])
  expect(getThoughts(stateNew, ['a']))
    .toMatchObject([{ value: 'ab', rank: 0 }])

  // cursor should be /a/ab
  expect(stateNew.cursor)
    .toMatchObject([{ value: 'a', rank: 0 }, { value: 'ab', rank: 0 }])

})
```

**Comment by pushkov-fedor** [comment]
The problem is somewhere in `existingThoughtChange` reducer. I can fix it. 4hrs
