### ISSUE TITLE
Remove side effect from setCursor

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#829]
https://github.com/cybersemics/em/blob/dev/src/reducers/setCursor.ts#L44-L48

It might have to go in every cursor action creator that ends up calling `setCursor`, but if you can think of a solution with less surface area we should do that.

**Comment by anmolarora1** [comment]
> It might have to go in every cursor action creator that ends up calling `setCursor`, but if you can think of a solution with less surface area we should do that.

@raineorshine I'd suggest we should handle this with a middleware that would run the same logic for every `setCursor` action. That'd be a clean approach with a minimal surface area.

On a side note, I noticed that the `clearSelection` isn't activated when navigating the thoughts using a `cursorUp/cursorDown`. Let me know if this is a known issue, or we should create one for this.

![dividercursor_issue](https://user-images.githubusercontent.com/7765764/101241911-4b7e9480-3720-11eb-820e-aa2b1098d651.gif)

**Comment by raineorshine** [comment]
> @raineorshine I'd suggest we should handle this with a middleware that would run the same logic for every `setCursor` action. That'd be a clean approach with a minimal surface area.

Sounds good.

> On a side note, I noticed that the `clearSelection` isn't activated when navigating the thoughts using a `cursorUp/cursorDown`. Let me know if this is a known issue, or we should create one for this.

Good catch. Won't it be fixed with the middleware? It should call `clearSelection` after `setCursor` has been dispatched.

**Comment by anmolarora1** [comment]
> > @raineorshine I'd suggest we should handle this with a middleware that would run the same logic for every `setCursor` action. That'd be a clean approach with a minimal surface area.
> 
> Sounds good.
> 
> > On a side note, I noticed that the `clearSelection` isn't activated when navigating the thoughts using a `cursorUp/cursorDown`. Let me know if this is a known issue, or we should create one for this.
> 
> Good catch. Won't it be fixed with the middleware? Calling `clearSelection` after `setCursor` has been dispatched should solve that since `setCursor` is called by `cursorDown`.

No. It won't be because the `setCursor` itself isn't being dispatched for those actions.

**Comment by raineorshine** [comment]
The `updateUrlHistory` middleware detects cursor changes. That could be generalized to `cursorChanged` and then the `clearSelection` logic could be called whenever the cursor changes and not be tied to a specific action.

**Comment by anmolarora1** [comment]
> The `updateUrlHistory` middleware detects cursor changes. That could be generalized to `cursorChanged` and then the `clearSelection` logic could be called whenever the cursor changes and not be tied to a specific action.

@raineorshine I'm not sure what you mean by `cursorChanged` here. Let me know if I understand this correctly - I think that you're perhaps referring to detecting any changes in the state cursor, which isn't something that middleware is supposed to do because it cannot access the reducers. That's only possible with a `store-enhancer`.

**Comment by raineorshine** [comment]
`cursorChanged` would be the new middleware that both `updateUrlHistory` and the logic for clearing the selection would use.

I guess I'm not so familiar with the difference between middleware and `store-enhancer`. Currently `updateUrlHistory` is written to detect when `state.cursor` has changed.

I'm open to other proposals, that's just the most obvious one to me.
