### ISSUE TITLE
Default browser drag cursor flashes when drag starts

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#833]
When starting a drag operation with the mouse on desktop, the css cursor gets changed to `cursor: copy` for a split second.

Here is what it looks like on Mac:

<img width="51" alt="Screen Shot 2020-08-17 at 3 42 53 PM" src="https://user-images.githubusercontent.com/750276/90447386-6b6e4780-e0a0-11ea-8548-3dbc8d054ce4.png">

The cursor should instead remain the default.

![em - dnd default browser cursor](https://user-images.githubusercontent.com/750276/90447446-9193e780-e0a0-11ea-9725-2ac6da6b374e.gif)

**Comment by Zubair286** [comment]
I am not able to reproduce this issue anymore on mac, on which it seems to be occurring. Previously, it did flash but not anymore.

**Comment by raineorshine** [comment]
Also no longer able to reproduce!

Maybe it was a bug that was fixed in one of the newer versions of react-dnd ☺️
