### ISSUE TITLE
Command: join

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#851]
- [ ] Unit Test
 
Create a pure, functional reducer called `join` that joins all siblings into a single thought. Joined thoughts should be separated by a single space. Children should be merged.

Create a shortcut that dispatches `{ type: 'join' }`

Keyboard: <kbd>Meta</kbd> + <kbd>Option</kbd> + <kbd>j</kbd>

# Case 1

## Before

- a
  - b [cursor]
  - c
  - d

## After

- a
  - b c d [cursor]

# Case 2 (children)

## Before

- a
  - b [cursor]
    - c
  - d
    - e

## After

- a
  - b d [cursor]
    - c
    - e

**Comment by pushkov-fedor** [comment]
I liked to work on splitSentences, i would like to pick this too! 7-9hrs

**Comment by raineorshine** [comment]
I'm afraid I can't budget that much time for this. Given how similar it is to `splitSentences`, it should be very straightforward. 3-4 hours at most.

**Comment by pushkov-fedor** [comment]
Okay, i still want to take it and try to implement it in your estimation. But if you want to assign it to someone, who is more confident in his estimation, it's okay :)

**Comment by raineorshine** [comment]
I'd be happy to give it to you if you log no more than 4 hours, even if it takes you a bit more. I'll leave that up to you. I understand if you want to work strictly hourly.

**Comment by anmolarora1** [comment]
@raineorshine Can we close this one?
