### ISSUE TITLE
Command: splitSentences

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#853]
- Add a reducer `splitSentences` that splits multiple sentences within a thought into separate thoughts. 
- Add a corresponding shortcut and toolbar button. 
- Reducer unit tests

### Before

- One. Two. Three.

### After

- One.
- Two.
- Three.

### Before

- a
- One. Two. Three.
- b

### After

- a
- One.
- Two.
- Three.
- b

**Comment by pushkov-fedor** [comment]
Looks interesting! I can take it, 6-8hrs

**Comment by raineorshine** [comment]
Looks like we're going to come in right under the estimate. Nice work.
