### ISSUE TITLE
Thoughts hidden on nested context view

### ISSUE THREAD

**Issue by shresthabijay** [cybersemics/em#881]
# Steps to reproduce

1. Create this structure

``` 
- a
    - c
- f
    - c
        - e
- r
    - e 
        - i
``` 

2. Then open a nested context view as follows:

``` 
- a
    - c~
        - a
        - f
            - e~
                - f.c
                - r
                    - i (cursor)
``` 

# Current behavior

As we click on thought `i` all thoughts will get hidden.

# Expected behavior

Navigate to `i` without hiding thought or losing focus.

**Comment by raineorshine** [comment]
Confirmed fixed
