### ISSUE TITLE
Back/Forward after deleting results in invalid cursor

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#884]
History back/forward should never result in an invalid cursor. History states with invalid `Paths` should be skipped. Thus if there are three invalid history states in a row (e.g. due to a thought being archived and `showHiddenThoughts` being `false`), then they should all be skipped and the next valid `Path` in the cursor history should be restored.

Start with a failing unit test.

## Steps to Reproduce

- a
- b
- c [cursor]

1. Create `a`, `b`, `c`, in order as shown above.
2. Select `a`.
2. Archive `a`.
3. Hit Back in the browser

## Current Behavior

Cursor disappears and url changes to `/a` even though `a` has been archived.

## Expected Behavior

Cursor should move to `c`.

**Comment by anmolarora1** [comment]
@raineorshine I wasn't able to replicate the issue. Can you please confirm if it still exists?

**Comment by raineorshine** [comment]
The current behavior has changed, but the expected behavior is still not happening.

**Comment by anmolarora1** [comment]
After some further digging, I think the best place to handle this would be [the updateUrlHistory middleware](https://github.com/cybersemics/em/blob/dev/src/redux-middleware/updateUrlHistory.ts). 
IMO, we should simply skip the archived thoughts' states from the window's history object, and the browser's back button would work as we're expecting.
Albeit unused, the logic to handle this scenario (or something similar) is in place already. [This is](https://github.com/cybersemics/em/blob/5baf45d1bc0e188dd2dd744dd806f3c885ef3100/src/redux-middleware/updateUrlHistory.ts#L55) where we're deciding whether to replace the push to the state or replace it.

Also, [the throttled function](https://github.com/cybersemics/em/blob/5baf45d1bc0e188dd2dd744dd806f3c885ef3100/src/redux-middleware/updateUrlHistory.ts#L68) doesn't work correctly for varying arguments.
[Here's the issue](https://github.com/lodash/lodash/issues/2403) which captures this problem. So we might have to combine the `throttle` function with `memoize`.
@raineorshine What are your thoughts?

**Comment by raineorshine** [comment]
> Albeit unused, the logic to handle this scenario (or something similar) is in place already. [This is](https://github.com/cybersemics/em/blob/5baf45d1bc0e188dd2dd744dd806f3c885ef3100/src/redux-middleware/updateUrlHistory.ts#L55) where we're deciding whether to replace the push to the state or replace it.

Let me know if I'm misunderstanding you here, but I don't think we can change the way the history is updated. It has to be pushed no matter what; it doesn't become invalid until the `Path` is invalid in the future. Using the example in the OP, when `a` is created, `updateUrlHistory` calls `window.history.pushState` with `/~/a`. That is a completely valid history state. It's only when `a` is archived in the future that the history state becomes invalid. Therefore it has to be handled in `onPopstate`.

> Also, [the throttled function](https://github.com/cybersemics/em/blob/5baf45d1bc0e188dd2dd744dd806f3c885ef3100/src/redux-middleware/updateUrlHistory.ts#L68) doesn't work correctly for varying arguments.
> [Here's the issue](https://github.com/lodash/lodash/issues/2403) which captures this problem. So we might have to combine the `throttle` function with `memoize`.

`updateUrlHistoryDebounced` passes a fresh `state` to `updateUrlHistory` whenever it is called, so I don't think that's a problem here, like it would be if we were trying to pass varying arguments.

**Comment by anmolarora1** [comment]
> > Albeit unused, the logic to handle this scenario (or something similar) is in place already. [This is](https://github.com/cybersemics/em/blob/5baf45d1bc0e188dd2dd744dd806f3c885ef3100/src/redux-middleware/updateUrlHistory.ts#L55) where we're deciding whether to replace the push to the state or replace it.
> 
> Let me know if I'm misunderstanding you here, but I don't think we can change the way the history is updated. It has to be pushed no matter what; it doesn't become invalid until the `Path` is invalid in the future. Using the example in the OP, when `a` is created, `updateUrlHistory` calls `window.history.pushState` with `/~/a`. That is a completely valid history state. It's only when `a` is archived in the future that the history state becomes invalid. Therefore it has to be handled in `onPopstate`.

Yes, there's a bit of a misunderstanding here. I agree with your point of the state being valid when `a` is created. And we'd only invalidate the state when it's archived.
Here's the series of steps with reference to the example that you shared -
```
1. select c - window.history.pushState('c')
2. select a - window.history.pushState('a')
3. archive c - window.history.replaceState('b')
4. Hit back button - cursor moves to 'c' on popState
```
Notice the **third step** - Instead of adding a new state, I'm replacing the state `a` with `b`. So we're invalidating the state on the archive.

**Comment by raineorshine** [comment]
> Notice the **third step** - Instead of adding a new state, I'm replacing the state `a` with `b`. So we're invalidating the state on the archive.

That only works for contiguous states. It doesn't invalidate past states. There could be any number of intervening actions between 1 and 3.

**Comment by anmolarora1** [comment]
> > Notice the **third step** - Instead of adding a new state, I'm replacing the state `a` with `b`. So we're invalidating the state on the archive.
> 
> That only works for contiguous states. It doesn't invalidate past states. There could be any number of intervening actions between 1 and 3.

Okay, that makes sense.

**Comment by anmolarora1** [comment]
@raineorshine Do you think we can conclude the state as invalid if the [path decoded from the URL](https://github.com/cybersemics/em/blob/5baf45d1bc0e188dd2dd744dd806f3c885ef3100/src/util/initEvents.ts#L21) equals null? If yes, we can simply trigger a `window.history.back` action for such scenarios.
If not, we can add an additional check to validate the `window.history.state` object for invalid paths but that function would have a considerable overlap with `decodeThoughtsURL`.

The second challenge for us would be to ensure that the `forward button` acts in accordance with the `back button`, that is, it skips over the invalid paths. So triggering an [additional back](https://github.com/cybersemics/em/issues/884#issuecomment-731626085) would only solve a part of this problem unless we want to handle the corresponding `forward action` in a different issue.
Nevertheless, I believe that we'd need to keep track of the window's state history in our local state to handle both these actions. Let me know what you think.

**Comment by raineorshine** [comment]
> Do you think we can conclude the state as invalid if the [path decoded from the URL](https://github.com/cybersemics/em/blob/5baf45d1bc0e188dd2dd744dd806f3c885ef3100/src/util/initEvents.ts#L21) equals null?

No, because `null` represents the root.

You can use `pathExists` to see if a `Path` is valid:

https://github.com/cybersemics/em/blob/547b2c9049c2cc049897e5bc2e07155f56866f40/src/selectors/decodeThoughtsUrl.ts#L11-L13

> The second challenge for us would be to ensure that the `forward button` acts in accordance with the `back button`, that is, it skips over the invalid paths. So triggering an [additional back](https://github.com/cybersemics/em/issues/884#issuecomment-731626085) would only solve a part of this problem unless we want to handle the corresponding `forward action` in a different issue.

Yes, we will need to handle forward as well.

> Nevertheless, I believe that we'd need to keep track of the window's state history in our local state to handle both these actions. Let me know what you think.

I'm not seeing this. Wouldn't be more efficient to check when they hit Back or Forward?

**Comment by anmolarora1** [comment]
> > Do you think we can conclude the state as invalid if the [path decoded from the URL](https://github.com/cybersemics/em/blob/5baf45d1bc0e188dd2dd744dd806f3c885ef3100/src/util/initEvents.ts#L21) equals null?
> 
> ~I _think_ so, but you have to be careful since `null` is a valid `cursor` as it is used to represent the root context.~ It seems that `decodeThoughtsUrl` is a little inconsistent; when `exists: true` is given it returns `null` for a valid root context. This might be a bug.
It's likely to be one. I'll look further once I'm done with this issue, and confirm whether it is a bug or not.

> 
> You can also use `pathExists` to see if a `Path` is valid:
> 
> https://github.com/cybersemics/em/blob/547b2c9049c2cc049897e5bc2e07155f56866f40/src/selectors/decodeThoughtsUrl.ts#L11-L13

Thanks for sharing this.

> 
> > The second challenge for us would be to ensure that the `forward button` acts in accordance with the `back button`, that is, it skips over the invalid paths. So triggering an [additional back](https://github.com/cybersemics/em/issues/884#issuecomment-731626085) would only solve a part of this problem unless we want to handle the corresponding `forward action` in a different issue.
> 
> Yes, we will need to handle forward as well.
Okay. I think we should update the issue to specify that.

> 
> > Nevertheless, I believe that we'd need to keep track of the window's state history in our local state to handle both these actions. Let me know what you think.
> 
> It might not necessary to track the browser history in the state, as you can simply repeat `history.back()` or `history.forward()` to skip the invalid URL. Though I'm not sure how to distinguish back and forward since that information is not provided in `onPopstate`. Here's what I was thinking: #920.

I didn't find a direct way to distinguish between the `forward` and `back` buttons because both trigger a `popState`. 
So I'm currently trying to find some possible workarounds to achieve that.

> 
> Maybe we should do a comparison of the advantages/disadvantages of the two approaches.
What are the two approaches that you're referring to?

**Comment by raineorshine** [comment]
> What are the two approaches that you're referring to?

With or without additional state. If it's not possible to distinguish `forward` and `back`, then we'll need to use state.

**Comment by anmolarora1** [comment]
> > What are the two approaches that you're referring to?
> 
> With or without additional state. If it's not possible to distinguish `forward` and `back`, then we'll need to use state.

That's correct. We'll need to have a counter of some sort, but it might be still possible to not add it to the state. 
I'm trying for a solution similar to [this](https://stackoverflow.com/a/8980832), and already tried a rough implementation, which seems to be working.
I noticed that we're storing the context in the history state
https://github.com/cybersemics/em/blob/52b13755160f68b6c3c9a7d024177fb617c9af94/src/redux-middleware/updateUrlHistory.ts#L55-L58 
But I don't see it being consumed anywhere. Do you think we can replace it with another variable?

**Comment by raineorshine** [comment]
> I'm trying for a solution similar to [this](https://stackoverflow.com/a/8980832), and already tried a rough implementation, which seems to be working.

Is this comment, which describes a flaw in that solution, relevant? https://stackoverflow.com/questions/8980255/how-do-i-retrieve-if-the-popstate-event-comes-from-back-or-forward-actions-with/8980832#comment29288957_8980832

> I noticed that we're storing the context in the history state
> https://github.com/cybersemics/em/blob/52b13755160f68b6c3c9a7d024177fb617c9af94/src/redux-middleware/updateUrlHistory.ts#L55-L58
> 
> 
> but the `history.state` isn't being directly consumed anywhere. Do you think we can replace it with another variable?

Yes, it's not currently used.

**Comment by anmolarora1** [comment]
> Is this comment, which describes a flaw in that solution, relevant? https://stackoverflow.com/questions/8980255/how-do-i-retrieve-if-the-popstate-event-comes-from-back-or-forward-actions-with/8980832#comment29288957_8980832

I don't think that's relevant in our case, even though our navigation is completely dynamic. As long as we're considering any intervening navigation actions between two or more thoughts to be unique. For instance, the following sequence for thoughts
```
a
b
c
d
```

```
1. select a
2. select b
3. select c
4. select a
5. select d
6. select c
7. select a
8. archive a
9. back -> c
10. back -> d
11. back -> c
12. forward -> d
13. forward -> c 
14. forward -> root
```
Let me know if that's inline with what we're expecting.

**Comment by raineorshine** [comment]
Yup, that's right!
