### ISSUE TITLE
newThought: Invalid split error

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#887]
"Duplicate thoughts are not allowed in the same context" gets alerted incorrectly when activating `newThought` after editing a descendant. 

Perhaps `editingValue` is not updated when the cursor moves?

https://github.com/cybersemics/em/blob/dev/src/action-creators/newThought.ts

**Comment by anmolarora1** [comment]
@raineorshine I couldn't replicate this one. You can refer to[ this video](https://www.awesomescreenshot.com/video/1727116) to confirm if I followed the correct steps.
Else, you can provide the exact steps to reproduce.

**Comment by raineorshine** [comment]
I can't reproduce it either! Maybe it was fixed in another commit.
