### ISSUE TITLE
Navigation into context view fails

### ISSUE THREAD

**Issue by shresthabijay** [cybersemics/em#892]
### Steps to reproduce

1. Create following structure.
  ```
   - a
     - b
       - c
   - k
     - l
       - c
         - i
          - m
  ```
2. Activate context view on `a.b.c` and set cursor to `a.b.c.l.i`
  ```
   - a
     - b
       - c ~
         - a.b.c
         - k.l.c
           - i (cursor)
   - k
     - l
       - c
         - i
          - m
  ```

### Current behavior

App crashes with following error.

![image](https://user-images.githubusercontent.com/25879100/97796590-da892000-1c3b-11eb-9016-6b8d4e6351a3.png)

### Expected behavior

Navigate without crashing.

**Comment by anmolarora1** [comment]
@shresthabijay I wasn't able to replicate this on `dev`. Can you please verify if the issue still exists?

**Comment by shresthabijay** [comment]
@anmolarora1 I can confirm it's been resolved. I forgot to link this issue with the respective PR that resolved this issue.
