### ISSUE TITLE
Unhandled error for logged-in users after undo 

### ISSUE THREAD

**Issue by anmolarora1** [cybersemics/em#903]
The user must be logged into the app to replicate this

Steps to replicate - 
1. Create a thought
2. Click the `undo` shortcut from the toolbar
3. Hit enter to create a new thought

Expected - The user should be able to create a new thought

Current - Unhandled rejection (screenshot attached)
![Screenshot 2020-11-10 at 11 46 22 AM](https://user-images.githubusercontent.com/7765764/98707646-468b2700-23a6-11eb-8fec-1df6e32a83a3.png)

**Comment by anmolarora1** [comment]
@raineorshine This one was quite tricky to debug 😃 . Here's what I found -

The [deepClone](https://github.com/cybersemics/em/blob/7ef14b256d1c8b432cba81d2b325e0acf4293a47/src/redux-enhancers/undoRedoReducerEnhancer.ts#L59) doesn't work as expected for the `userRef`. Not sure of the exact reason but the reference is holding some functions. 

But since [we're omitting](https://github.com/cybersemics/em/blob/7ef14b256d1c8b432cba81d2b325e0acf4293a47/src/redux-enhancers/undoRedoReducerEnhancer.ts#L8) the `userRef` from the patches, we can easily ignore any updates that might be falsely made to those omitted sections.
Instead of doing this 
```
if (undoOrRedoState) return undoOrRedoState

```
We can safely do this 
```
if (undoOrRedoState) {
  const omitted = _.pick(state, stateSectionsToOmit)
  return { ...undoOrRedoState, ...omitted }
}
```

And that just adds an extra safety net to ensure that omitted items don't get updated.
What are your thoughts?


On a side note, storing functions in the redux store isn't a good idea because they're not serializable - [The Redux docs](https://redux.js.org/faq/organizing-state#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state) suggest the same.

**Comment by raineorshine** [comment]
> We can do this
> 
> ```
> if (undoOrRedoState) {
>   const omitted = _.pick(state, stateSectionsToOmit)
>   return { ...undoOrRedoState, ...omitted }
> }
> ```
> 
> And that just adds an extra safety net to ensure that omitted items don't get updated.
> What are your thoughts?

I think that's a great idea.

> On a side note, storing functions in the redux store isn't a good idea because they're not serializable - [The Redux docs](https://redux.js.org/faq/organizing-state#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state) suggest the same.

I completely agree. We already store the user's `uid` in `state.user.uid`. Can we just use that to reconstruct the `userRef` as needed?

```js
firebase.database().ref('users/' + state.user.uid)
```
