### ISSUE TITLE
Uncaught error when creating new 'Note'

### ISSUE THREAD

**Issue by anmolarora1** [cybersemics/em#923]
Steps to replicate
1. Create a thought.
2. Select the new note shortcut from the toolbar
3. Press the `arrow up` key

An error is thrown.
![Screenshot 2020-12-02 at 6 36 00 PM](https://user-images.githubusercontent.com/7765764/100877318-986b2c80-34ce-11eb-9e57-6e73a41b3222.png)

**Comment by anmolarora1** [comment]
@raineorshine It turns out this issue is because of the way the code is compiled. 

The reason for the error is pretty clear if we look at the compiled version of our code. This is how it looks like -
![Screenshot 2020-12-03 at 12 46 32 PM](https://user-images.githubusercontent.com/7765764/101053241-8d3afe00-35ad-11eb-85ca-9a0bcb07db0b.png)


If we add an explicit return statement or replace this loc 
`(noteEl.parentNode?.previousSibling as HTMLElement)?.querySelector('.editable') as (HTMLElement | null)
`
with 
`(noteEl.parentNode?.previousSibling as HTMLElement).querySelector('.editable') as (HTMLElement | null)`

It changes into 
![Screenshot 2020-12-03 at 12 47 32 PM](https://user-images.githubusercontent.com/7765764/101053233-8a400d80-35ad-11eb-9094-6302c8f218ba.png)

I checked the code on ts playground, and couldn't find any noticeable differences. I understand the reason for adding optional chaining, so we can probably use an explicit return statement here. What are your thoughts?

**Comment by raineorshine** [comment]
Wow! How strange. I've never run into that before. Yeah, it compiles fine in TS Playground.

Maybe something like this:

```js
const editableOfNote = (noteEl: HTMLElement) => {
  const thoughtContainer = noteEl.parentNode?.previousSibling as HTMLElement | undefined
  return thoughtContainer?.querySelector('.editable') as HTMLElement | null
}
```

Make sure to include a descriptive comment that warns about the compilation bug.
