### ISSUE TITLE
Server-Side Search

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#931]
With the introduction of the `pullQueue`, not all thoughts are loaded into `state`. This breaks the current implementation of search. We need to change it to search Firebase, if logged in, or IndexedDB otherwise.

- The behavior should be close to the previous state search, although we may need to add a `LoadingEllipsis`.
- Firebase search should be done server-side. You might need to create your own `Firebase` database to test this.
- Need to search IndexedDB without loading the entire `thoughtIndex` into memory somehow.

**Comment by shresthabijay** [comment]
@raineorshine Since firestore and realtime database do not provide full text search, we should use services like Algolia or Elastic Search with Cloud functions to achieve it. https://firebase.google.com/docs/firestore/solutions/search. We can use cloud functions to add, delete and update the indexes using  firebase realtime database triggers.

**Comment by raineorshine** [comment]
Ah, more work than I expected. That seems right though. Are you up for it?

**Comment by shresthabijay** [comment]
@raineorshine I am up for it. This is the only way to have full text search.

**Comment by shresthabijay** [comment]
@raineorshine  I have setup a basic search functionality using cloud functions and [Algolia!](https://algolia.com). It can do following things:

- On addition of new `Lexeme` search index is added.
- On deletion of a `Lexeme` related search index is deleted.
- An api endpoint to generate a secured search api key based on firebase `user.uid`. It returns api key that can be used in frontend. It only returns results specific to the user.

Currently it stores `value`, `thoughtHash` as search index fields.

Link to cloud function repo: https://github.com/shresthabijay/em-search-function

I have created a very basic ui to test how well the remote full text search setup works: https://github.com/shresthabijay/em/tree/em-search-remote

Please test this branch. I have used separate firebase database and cloud function for this. So you will need to add data. I would like you test the latency on frequent changes to the thoughts. 

![Screen Capture_select-area_20201215171721](https://user-images.githubusercontent.com/25879100/102209868-87bcac80-3ef9-11eb-9a07-960d9b22a5ec.gif)

Still need to workout the archived feature and  pulling required data from remote after search to render `contextView`. I would like you to review the progress first.

**Comment by raineorshine** [comment]
> I have setup a basic search functionality using cloud functions and [Algolia!](https://algolia.com)

Great!

> * An api endpoint to generate a secured search api key based on firebase `user.uid`. It returns api key that can be used in frontend. It only returns results specific to the user.

Excellent

> I have created a very basic ui to test how well the remote full text search setup works: [https://github.com/shresthabijay/em/tree/em-search-remote](https://github.com/shresthabijay/em/tree/em-search-remote?rgh-link-date=2020-12-15T11%3A36%3A44Z)

Please open a PR so it's tracked in this repo. Also I would rather than download the whole project and have a duplicate `node_modules` which is very large.

> I would like you test the latency on frequent changes to the thoughts.

Looks pretty fast from the screenshot!

> Still need to workout the archived feature

I believe that could be done client-side after the server-side search is done? The search will include archived thoughts by default (any thought with `=archive` as an ancestor) and they can be filtered client-side. It might be simpler than trying to do that server-side, and we can optimize it later. Up to you.

> pulling required data from remote after search to render `contextView`

[pull](https://github.com/cybersemics/em/blob/61fed90ab10b930aa3fe6c30a31b643221b4d759/src/action-creators/pull.ts#L29) takes a `Index<Context>`. Unfortunately it doesn't take a list of `Lexemes`, nor is there a way for it to pull only from `thoughtIndex` and not `contextIndex`.

[getThoughtsByIds](https://github.com/cybersemics/em/blob/61fed90ab10b930aa3fe6c30a31b643221b4d759/src/data-providers/firebase.ts#L24-L31) is the most direct way to pull the `Lexemes` from only the `thoughtIndex`, but it's not connected to `reconcile` or the `pullQueue`, so it won't trivially populate the search results.

Either way, this part will take some thought as to the best approach.

**Comment by shresthabijay** [comment]
> I believe that could be done client-side after the server-side search is done? The search will include archived thoughts by default (any thought with `=archive` as an ancestor) and they can be filtered client-side. It might be simpler than trying to do that server-side, and we can optimize it later. Up to you.

Yeah its better done on client side.
