### ISSUE TITLE
Mobile incorrectly enters edit mode when tapping between parent and child

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#946]
Tested on iOS.

## Steps to Reproduce

- a
  - b

1. Set cursor on `a`. 
1. Tap on the bottom edge of `b`

## Current Behavior

If you tap in just the right place, the cursor moves and `b` and enters edit mode. 

## Expected Behavior

The cursor should move to `b` without entering edit mode. 

Note: the same behavior can be observed when the cursor is on `b` and the bottom edge of `a` is tapped.

**Comment by raineorshine** [comment]
We need a fix that doesn't break #1029.

**Comment by raineorshine** [comment]
@shresthabijay The only fix I knew for #1054 involved breaking this again (9633aee). While annoying, at least the app is usable. #1054 was breaking both scrolling and gestures.

**Comment by shresthabijay** [comment]
@raineorshine I tried reproducing the issue on both ios and android. I was not able to reproduce it. I may be missing something. Can you please screen grab the issue ?

**Comment by raineorshine** [comment]
Huh, that’s strange. A screen grab isn’t going to show you anything else unfortunately. You can’t see where the taps occur. The text description is accurate. 

I’d you can’t reproduce it, I can take another stab at it and try not to break everything else!

**Comment by shresthabijay** [comment]
May be I am not accurately following the steps. Tapping anywhere in the bottom edge of the `b` should move the cursor right? Also the issue title suggests that it  occurs when tapped in space between parent and child. 

> Huh, that’s strange. A screen grab isn’t going to show you anything else unfortunately. You can’t see where the taps occur. The text description is accurate.

**Comment by raineorshine** [comment]
> May be I am not accurately following the steps. Tapping anywhere in the bottom edge of the `b` should move the cursor right? Also the issue title suggests that it occurs when tapped in space between parent and child.
> 
> > Huh, that’s strange. A screen grab isn’t going to show you anything else unfortunately. You can’t see where the taps occur. The text description is accurate.

Yes, tapping close to the bottom edge of `b` causes it to incorrectly enter edit mode instead of moving the cursor. `b` does not have to have a child, it would just be in between the parent and child if the child existed. This is clearer in the case where the cursor is on `b` and then you tap the bottom edge of `a`, i.e. in between `a` and `b`.

One question that needs to be answered is, which element are you actually tapping when tapping on the "edge"? My guess is that there is a tiny bit of margin that is causing a different element to get the click event.

**Comment by raineorshine** [comment]
Testing checklist:

**Desktop:**

- [x] Set selection on click from null cursor
- [x] Set selection on cursorDown from null cursor
- [x] Set selection clicking on empty space

**Mobile:**

- [x] Enter edit mode
- [x] Preserve editing: false
- [x] Preserve editing: true
- [x] cursorBack on hidden element (#1029)
- [x] Preserve editing clicking on child edge (#946)
- [x] Preserve editing on switch app (#940)
- [x] No uncle loop (#908)
