### ISSUE TITLE
splitSentence should work on `;?!`

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#949]
Currently the `splitSentences` shortcut just splits on period. It should split on `/[.;?!]/`. 

See #853 and #859 for how the `splitSentences` shortcut works.

**Comment by linghong** [comment]
It seems that the splitSentences also works for /[.;?!]/, but it always replace those symbols  with "."  Do you mean you want to replace "."  with the original symbol?

Currently in some special cases, for example 333.12345, it will splits into 333. and 12345. Do you want to keep it like that way, or  if it is a decimal  number, just don't split them.  

There are also other special cases, like the below:
sentense A?! sentense B
"sentense A." sentenseB.
(sentense A!) sentenseB.

Do you prefer our code to address those issues, or just split them whenever any of the /[.;?!]/ symbols occurs  and let the users themselves to adjust the result?

**Comment by raineorshine** [comment]
> It seems that the splitSentences also works for /[.;?!]/, but it always replace those symbols with "." Do you mean you want to replace "." with the original symbol?

Yes, I didn't realize that! We want to preserve the original symbol.

> Currently in some special cases, for example 333.12345, it will splits into 333. and 12345. Do you want to keep it like that way, or if it is a decimal number, just don't split them.

It is not expected that the user would activate `splitSentences` on such thoughts, so I think we can leave it as-is. Thanks for noticing though.

> There are also other special cases, like the below:
> sentense A?! sentense B
> "sentense A." sentenseB.
> (sentense A!) sentenseB.

- `sentense A?! sentense B` → `sentense A?!` and `sentense B`
- `"sentense A." sentenseB.` → `"sentense A."` and `sentenseB.`
- `(sentense A!) sentenseB.` → `(sentense A!)` and `sentenseB.`

Good catch on those. It is more logic than I originally expected when I designed the feature, but they are all cases that I would like to cover.

> Do you prefer our code to address those issues, or just split them whenever any of the /[.;?!]/ symbols occurs and let the users themselves to adjust the result?

Thanks for your thoroughness, I really appreciate that. I'd love for you to address all the cases you raised.
