### ISSUE TITLE
Cursor not exported

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#953]
## Steps to reproduce

- a
  - b
    - c

1. Set the cursor on `a`
1. Export `a`

## Current Behavior

`b` and `c` are exported correctly but the cursor thought itself is excluded. 

- b
  - c

## Expected Behavior

Cursor thought should be exported. 

- a
  - b
    - c

**Comment by shresthabijay** [comment]
@raineorshine This behavior is introduced by this logic.

https://github.com/cybersemics/em/blob/edec0655310835a1fbcbcb375fd90c5e6b33d278/src/components/ModalExport.tsx#L73
Here `removeRoot` removes first thought from the `exported` if `titleChild` is not available. Shouldn't it check if the thought'a value is `__ROOT__` before removing ?

**Comment by raineorshine** [comment]
Indeed! Let's add that condition in `removeRoot` itself, and if the first line is not the ROOT then return `exported` as-is. Thanks!
