### ISSUE TITLE
Recently Edited: formatting and filtering

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#959]
There are some small improvements we can make before the next major upgrade:

- Exclude EM_TOKEN and metaprogrammimg attributes
- Format breadcrumbs like context view

**Comment by shresthabijay** [comment]
> * Exclude EM_TOKEN and metaprogrammimg attributes

@raineorshine Should we omit tracking them into recently edited tree entirely if the path has EM_TOKEN or metaprogramming attributes ?

**Comment by shresthabijay** [comment]
> * Format breadcrumbs like context view

@raineorshine  Just like this ?

![image](https://user-images.githubusercontent.com/25879100/104688660-39cddb00-5729-11eb-9f6a-c20743bce8bd.png)

**Comment by raineorshine** [comment]
> Should we omit tracking them into recently edited tree entirely if the path has EM_TOKEN or metaprogramming attributes ? Or should it depend on `showHiddenThoughts` ?

We should utilize `showHiddenThoughts` for the greatest flexibility.

> @raineorshine Just like this ?

Yup! Exactly

**Comment by shresthabijay** [comment]
@raineorshine How does this look ? 

![Screen Capture_select-area_20210119212758](https://user-images.githubusercontent.com/25879100/105057373-43df3900-5a9d-11eb-8e61-0c168952628b.gif)

Since `NavBar` component uses same `Breadcrumb` as `Sidebar`. I think we should create two variants. One varinat will format it just like context view. What do you think?

**Comment by raineorshine** [comment]
> How does this look ?

Looks great! Just omit the bullet at the start of the breadcrumbs.

> Since `NavBar` component uses same `Breadcrumb` as `Sidebar`. I think we should create two variants. One varinat will format it just like context view. What do you think?

There is already `Breadcrumbs` and `ContextBreadcrumbs`. Will `ContextBreadcrumbs` work?

**Comment by shresthabijay** [comment]
> There is already `Breadcrumbs` and `ContextBreadcrumbs`. Will `ContextBreadcrumbs` work?

`ContextBreadcrumbs` doesn't have `thoughtsLimit` and overflow collapsing like `Breadcrumbs`. Hoever we can have single breadcrumb component that we can pass props to have optional overflow collapsing feature. What do you think ?

**Comment by shresthabijay** [comment]
> Just omit the bullet at the start of the breadcrumbs.

@raineorshine Following predicate allows showing bullet infront of breadcrumb when screen is not touch screen. Is this correct behavior ?
 https://github.com/cybersemics/em/blob/6c393c3306e72471647461d789bb104e6a7f27e8/src/components/Breadcrumbs.tsx#L81

**Comment by raineorshine** [comment]
> > There is already `Breadcrumbs` and `ContextBreadcrumbs`. Will `ContextBreadcrumbs` work?
> 
> `ContextBreadcrumbs` doesn't have `thoughtsLimit` and overflow collapsing like `Breadcrumbs`. Hoever we can have single breadcrumb component that we can pass props to have optional overflow collapsing feature. What do you think ?

Let's not combine `Breadcrumbs` and `ContextBreadcrumbs` since the `ContextBreadcrumbs` implementation is so much simpler. 

Having discussed some possibilities, I will leave it up to you how you'd like to organize the Recently Edited breadcrumb component. I trust your decision.

> > Just omit the bullet at the start of the breadcrumbs.
> 
> @raineorshine Following predicate allows showing bullet infront of breadcrumb when screen is not touch screen. Is this correct behavior ?
> https://github.com/cybersemics/em/blob/6c393c3306e72471647461d789bb104e6a7f27e8/src/components/Breadcrumbs.tsx#L81

At one point this was intended, but I think it no longer makes sense. It had to due with the way it looked on desktop and mobile. It "felt" better without the leading bullet on mobile. Now I think it should probably be that way for both desktop and mobile.

**Comment by raineorshine** [comment]
> > > There is already `Breadcrumbs` and `ContextBreadcrumbs`. Will `ContextBreadcrumbs` work?
> > 
> > 
> > `ContextBreadcrumbs` doesn't have `thoughtsLimit` and overflow collapsing like `Breadcrumbs`. Hoever we can have single breadcrumb component that we can pass props to have optional overflow collapsing feature. What do you think ?
> 
> Let's not combine `Breadcrumbs` and `ContextBreadcrumbs` since the `ContextBreadcrumbs` implementation is so much simpler.

Never mind, I see this has already happened. I will review.
