### ISSUE TITLE
Unhandled Rejection when activating new note after deleting subthought

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#970]
## Steps to Reproduce

1. Create thought `a`
2. Create subthought `b`
3. Archive `b`
3. Activate new note

## Current Behavior

`Unhandled Rejection (TypeError): Cannot read property 'rank' of undefined`

> src/selectors/getPrevRank.ts:25

## Expected Behavior

New note is created without error.

**Comment by raineorshine** [comment]
I think I broke this when I added `aboveMeta` to `getPrevRank`. Could you help? Strange that there's no unit test for this.

**Comment by shresthabijay** [comment]
@raineorshine I was not able to reproduce the issue. I am not getting any unhandled rejections.

**Comment by raineorshine** [comment]
Strange, I'm not able to reproduce it now.
