### ISSUE TITLE
Feedback Modal

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#985]
The user should be able to easily submit feedback or report a bug from the main screen. 

- Add a button with a chat icon to the bottom right (position fixed). 
- Clicking the button will open a Feedback Modal component. 
- Feedback Modal consists of a textarea and a Send button. Check commit history for former Feedback component. 
- Clicking Send will call a Firebase Function that sends an email to support@emtheapp.com. 

## Mail setup
- [ ] MX records
- [ ] Mailgun
- [ ] Firebase Function

**Comment by shresthabijay** [comment]
@raineorshine I have made the changes. Please review it. Thanks!
