### ISSUE TITLE
Undo/Redo: Push changes

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#987]
Currently an undo or redo action manually updates the state. If `state.thoughts` are updated, it needs to also trigger the `pushQueue` to save the changes to the data providers (IndexedDB and Firebase). 

This can be done by calling [updateThoughts](https://github.com/cybersemics/em/blob/dev/src/reducers/updateThoughts.ts). You will need to extract the `thoughtIndex` and `contextIndex` updates from the patch to pass to `updatesThoughts`. (None of the other arguments are needed.)

Here is how to [simulate a page refresh](https://github.com/cybersemics/em/blob/cbc247e10522ec9488e918a50c46c2f77fbf3e83/src/redux-middleware/__tests__/pullQueue.ts#L76) for the test.

**Comment by raineorshine** [comment]
As discussed, call the `updateThoughts` reducer in the enhancer and merge it into the new state.

If all goes well, the updates will get propagated to IndexedDB before the `pullQueue` tries to sync. That should fix the undo/redo being negated by `pull`.

**Comment by anmolarora1** [comment]
@raineorshine Can we close this issue now?
