### ISSUE TITLE
Export: Archived option

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#989]
Add an advanced option checkbox to include archived thoughts. Default: true

**Comment by ruchijn** [comment]
QQ: Let's say, user un-checks Lossless but keeps Archived checked. Then what should be downloaded? Currently, it doesn't include Archived thoughts when Lossless is unchecked but Archived is checked. 


https://user-images.githubusercontent.com/18288628/120086953-cf06b600-c0b1-11eb-80d0-b46f36f76e08.mp4

**Comment by raineorshine** [comment]
What do you think? I don't have a strong opinion myself.

If you choose to keep the behavior shown above, we should probably tie the options together as we discussed since they are no longer fully independent: i.e. When Lossless is unchecked, it should uncheck Archived. Or you can make them fully independent.

**Comment by ruchijn** [comment]
I have tied the options together. So now when we un-check Lossless, Archived will automatically get unchecked. But checking Lossless, will not automatically check Archived. If needed, user will have to do it manually.
