### ISSUE TITLE
Import: Merge descendants

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#993]
## Steps to Reproduce

1. Create the following thoughts:
    - a
      - b
        - c
    - [empty]
2. Set the cursor on the empty thought
3. Paste the following:
    ```
    - a
      - b
        - q
      - x
        - y
    - j
    ```

## Current Behavior

- a
  - b
    - c
- a
  - b
    - q
  - x
    - y
- j

## Expected Behavior

Imported thought and its descendants should be merged with existing thoughts so that there are no duplicates.

- a
  - b
    - c
    - q
  - x
    - y
- j

## Proposed Solution

The desired behavior is achieved with the following:

1. Insert dummy thought `__IMPORT__`
2. Paste
3. Set cursor back on `__IMPORT__`
4. Activate `collapseContext`

I recommend reproducing this in a reducer flow in `importText` to avoid having to modify the import logic itself. Rename the existing function to `importTextIntoLeaf` and throw an error if the destination `path` has any children. Create a new `importText` function to be exported with the same signature as the old one and perform the reducer flow described in the above steps, calling `importTextIntoLeaf` for Step 2.

Let me know if you have any concerns about this approach!

**Comment by raineorshine** [comment]
The downside to the proposed solution above is performance. Moves currently are O(n) for all descendants.

**Comment by shresthabijay** [comment]
@raineorshine The proposed solution is failling. `collapseContext` is throws error after thoughts have been imported in the dummy thought `__IMPORT__`.

**Comment by shresthabijay** [comment]
> The downside to the proposed solution above is performance. Moves currently are O(n) for all descendants.

@raineorshine I think the proposed solution is good. Since `exisitingThoughtMove` alrady has logic to merge thoughts, we should use it. Performance will get better if we optimize `exisitingThoughtMove`.

**Comment by raineorshine** [comment]
> @raineorshine I think the proposed solution is good. Since `exisitingThoughtMove` alrady has logic to merge thoughts, we should use it. Performance will get better if we optimize `exisitingThoughtMove`.

Agreed. And no point doing extra work when #495 will make `existingThoughtMove` some optimizations irrelevant.
